// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { SendSendBasicOptions, SendSendBasicResponseSuccess } from './interfaces/send-basic.js';
import type { SendSendOptions, SendSendResponseSuccess } from './interfaces/send.js';

export class Send {
  constructor(private readonly client: Createsend) {}

  /**
   * Send: SendBasic
   * @see POST /{version}/transactional/{id}/sendbasic.{format}
   */
  async sendBasic(options: SendSendBasicOptions): Promise<Response<SendSendBasicResponseSuccess>> {
    const { id } = options;
    return this.client.post<SendSendBasicResponseSuccess>(`/transactional/${id}/sendbasic.json`, undefined);
  }

  /**
   * Send: Send
   * @see POST /{version}/transactional/{triggeredCampaign}/send.{format}
   */
  async send(options: SendSendOptions): Promise<Response<SendSendResponseSuccess>> {
    const { triggeredCampaign } = options;
    return this.client.post<SendSendResponseSuccess>(`/transactional/${triggeredCampaign}/send.json`, undefined);
  }

}