// DO NOT EDIT — generated by scripts/generate.ts
// Source: templates_copy

import type { TemplateCopyRequest } from '../../generated/schema.js';

export interface TemplatesCopyOptions {
  templateid: string;
  body: TemplateCopyRequest;
}

export type TemplatesCopyResponseSuccess = unknown;
