// DO NOT EDIT — generated by scripts/generate.ts
// Source: templates_copybranded

import type { TemplateCopyBrandedRequest } from '../../generated/schema.js';

export interface TemplatesCopyBrandedOptions {
  templateid: string;
  body: TemplateCopyBrandedRequest;
}

export type TemplatesCopyBrandedResponseSuccess = unknown;
