// DO NOT EDIT — generated by scripts/generate.ts
// Source: copyTemplate

import type { TemplateCopyRequest } from '../../generated/schema.js';

export interface TemplatesCopyTemplateOptions {
  templateId: string;
  body: TemplateCopyRequest;
}

export type TemplatesCopyTemplateResponseSuccess = unknown;
