// DO NOT EDIT — generated by scripts/generate.ts
// Source: templates_create

import type { TemplateForInput } from '../../generated/schema.js';

export interface TemplatesCreateOptions {
  clientid: string;
  body: TemplateForInput;
}

export type TemplatesCreateResponseSuccess = string;
