// DO NOT EDIT — generated by scripts/generate.ts
// Source: createTemplate

import type { TemplateForInput } from '../../generated/schema.js';

export interface TemplatesCreateTemplateOptions {
  clientId: string;
  body: TemplateForInput;
}

export type TemplatesCreateTemplateResponseSuccess = string;
