// DO NOT EDIT — generated by scripts/generate.ts
// Source: templates_delete

export interface TemplatesDeleteOptions {
  templateid: string;
}

export type TemplatesDeleteResponseSuccess = unknown;
