// DO NOT EDIT — generated by scripts/generate.ts
// Source: deleteTemplate

export interface TemplatesDeleteTemplateOptions {
  templateId: string;
}

export type TemplatesDeleteTemplateResponseSuccess = unknown;
