// DO NOT EDIT — generated by scripts/generate.ts
// Source: getTemplate

import type { Template } from '../../generated/schema.js';

export interface TemplatesGetTemplateOptions {
  templateId: string;
}

export type TemplatesGetTemplateResponseSuccess = Template;
