// DO NOT EDIT — generated by scripts/generate.ts
// Source: templates_get

import type { Template } from '../../generated/schema.js';

export interface TemplatesGetOptions {
  templateid: string;
}

export type TemplatesGetResponseSuccess = Template;
