// DO NOT EDIT — generated by scripts/generate.ts
// Source: templates_update

import type { TemplateForInput } from '../../generated/schema.js';

export interface TemplatesUpdateOptions {
  templateid: string;
  body: TemplateForInput;
}

export type TemplatesUpdateResponseSuccess = unknown;
