// DO NOT EDIT — generated by scripts/generate.ts
// Source: updateTemplate

import type { TemplateForInput } from '../../generated/schema.js';

export interface TemplatesUpdateTemplateOptions {
  templateId: string;
  body: TemplateForInput;
}

export type TemplatesUpdateTemplateResponseSuccess = unknown;
