// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { WorkflowsSummaryOptions, WorkflowsSummaryResponseSuccess } from './interfaces/summary.js';
import type { WorkflowsCopyOptions, WorkflowsCopyResponseSuccess } from './interfaces/copy.js';
import type { WorkflowsUpdateStatusOptions, WorkflowsUpdateStatusResponseSuccess } from './interfaces/update-status.js';

export class Workflows {
  constructor(private readonly client: Createsend) {}

  /**
   * Workflows: Summary
   * GET journeys/{journeyid}.{format}
   * @see GET /{version}/journeys/{journeyid}.{format}
   */
  async summary(options: WorkflowsSummaryOptions): Promise<Response<WorkflowsSummaryResponseSuccess>> {
    const { journeyid } = options;
    return this.client.get<WorkflowsSummaryResponseSuccess>(`/journeys/${journeyid}.json`);
  }

  /**
   * Workflows: Copy
   * This is an undocumented endpoint, not supported by any of our wrappers, built specifically for one customer (see UX2-118). POST journeys/{journeyid}/copy.{format}
   * @see POST /{version}/journeys/{journeyid}/copy.{format}
   */
  async copy(options: WorkflowsCopyOptions): Promise<Response<WorkflowsCopyResponseSuccess>> {
    const { journeyid, body } = options;
    return this.client.post<WorkflowsCopyResponseSuccess>(`/journeys/${journeyid}/copy.json`, body);
  }

  /**
   * Workflows: Updatestatus
   * Undocumented endpoint, not supported by any of our wrappers and built for one customer (unrelated to the method above).See COM-597. PUT journeys/{journeyid}/updatestatus.{format}
   * @see PUT /{version}/journeys/{journeyid}/updatestatus.{format}
   */
  async updateStatus(options: WorkflowsUpdateStatusOptions): Promise<Response<WorkflowsUpdateStatusResponseSuccess>> {
    const { journeyid, body } = options;
    return this.client.put<WorkflowsUpdateStatusResponseSuccess>(`/journeys/${journeyid}/updatestatus.json`, body);
  }

}