// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { WorkflowsGetWorkflowSummaryOptions, WorkflowsGetWorkflowSummaryResponseSuccess } from './interfaces/get-workflow-summary.js';
import type { WorkflowsCopyWorkflowOptions, WorkflowsCopyWorkflowResponseSuccess } from './interfaces/copy-workflow.js';

export class Workflows {
  constructor(private readonly client: Createsend) {}

  /**
   * Workflows: GetWorkflowSummary
   * GET journeys/{journeyid}.{format}
   * @see GET /{version}/journeys/{journeyId}.{format}
   */
  async getWorkflowSummary(options: WorkflowsGetWorkflowSummaryOptions): Promise<Response<WorkflowsGetWorkflowSummaryResponseSuccess>> {
    const { journeyId } = options;
    return this.client.get<WorkflowsGetWorkflowSummaryResponseSuccess>(`/journeys/${journeyId}.json`);
  }

  /**
   * Workflows: Copy
   * This is an undocumented endpoint, not supported by any of our wrappers, built specifically for one customer (see UX2-118). POST journeys/{journeyid}/copy.{format}
   * @see POST /{version}/journeys/{journeyId}/copy.{format}
   */
  async copyWorkflow(options: WorkflowsCopyWorkflowOptions): Promise<Response<WorkflowsCopyWorkflowResponseSuccess>> {
    const { journeyId, body } = options;
    return this.client.post<WorkflowsCopyWorkflowResponseSuccess>(`/journeys/${journeyId}/copy.json`, body);
  }

}