// DO NOT EDIT — generated by scripts/generate.ts
// Source: workflows_copy

import type { WorkflowCopyRequest } from '../../generated/schema.js';

export interface WorkflowsCopyOptions {
  journeyid: string;
  body: WorkflowCopyRequest;
}

export type WorkflowsCopyResponseSuccess = unknown;
