// DO NOT EDIT — generated by scripts/generate.ts
// Source: copyWorkflow

import type { WorkflowCopyRequest } from '../../generated/schema.js';

export interface WorkflowsCopyWorkflowOptions {
  journeyId: string;
  body: WorkflowCopyRequest;
}

export type WorkflowsCopyWorkflowResponseSuccess = unknown;
