// DO NOT EDIT — generated by scripts/generate.ts
// Source: getWorkflowSummary

export interface WorkflowsGetWorkflowSummaryOptions {
  journeyId: string;
}

export type WorkflowsGetWorkflowSummaryResponseSuccess = unknown;
