// DO NOT EDIT — generated by scripts/generate.ts
// Source: workflows_summary

export interface WorkflowsSummaryOptions {
  journeyid: string;
}

export type WorkflowsSummaryResponseSuccess = unknown;
