// DO NOT EDIT — generated by scripts/generate.ts
// Source: workflows_updatestatus

import type { UpdateJourneyStatusRequest, WorkflowStatusChangeResponse } from '../../generated/schema.js';

export interface WorkflowsUpdateStatusOptions {
  journeyid: string;
  body: UpdateJourneyStatusRequest;
}

export type WorkflowsUpdateStatusResponseSuccess = WorkflowStatusChangeResponse;
