// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { SubscribersDeleteOptions, SubscribersDeleteResponseSuccess } from './interfaces/delete.js';
import type { SubscribersHistoryOptions, SubscribersHistoryResponseSuccess } from './interfaces/history.js';
import type { SubscribersImportStatusOptions, SubscribersImportStatusResponseSuccess } from './interfaces/import-status.js';
import type { SubscribersUnsubscribeOptions, SubscribersUnsubscribeResponseSuccess } from './interfaces/unsubscribe.js';

export class Subscribers {
  constructor(private readonly client: Createsend) {}

  /**
   * Subscribers: Delete
   * DELETE subscribers/{listid}.{format}?email={email}
   * @see DELETE /{version}/subscribers/{listid}.{format}
   */
  async delete(options: SubscribersDeleteOptions): Promise<Response<SubscribersDeleteResponseSuccess>> {
    const { listid, query } = options;
    return this.client.delete<SubscribersDeleteResponseSuccess>(`/subscribers/${listid}.json`, { query });
  }

  /**
   * Subscribers: History
   * GET subscribers/{listid}/history.{format}?email={email}
   * @see GET /{version}/subscribers/{listid}/history.{format}
   */
  async history(options: SubscribersHistoryOptions): Promise<Response<SubscribersHistoryResponseSuccess>> {
    const { listid, query } = options;
    return this.client.get<SubscribersHistoryResponseSuccess>(`/subscribers/${listid}/history.json`, { query });
  }

  /**
   * Subscribers: Importstatus
   * GET subscribers/{listid}/importstatus/{requestid}.{format} GET subscribers/{listid}/importstatus.{format}
   * @see GET /{version}/subscribers/{listid}/importstatus.{format}
   */
  async importStatus(options: SubscribersImportStatusOptions): Promise<Response<SubscribersImportStatusResponseSuccess>> {
    const { listid, query } = options;
    return this.client.get<SubscribersImportStatusResponseSuccess>(`/subscribers/${listid}/importstatus.json`, { query });
  }

  /**
   * Subscribers: Unsubscribe
   * POST subscribers/{listid}/unsubscribe.{format}
   * @see POST /{version}/subscribers/{listid}/unsubscribe.{format}
   */
  async unsubscribe(options: SubscribersUnsubscribeOptions): Promise<Response<SubscribersUnsubscribeResponseSuccess>> {
    const { listid, body } = options;
    return this.client.post<SubscribersUnsubscribeResponseSuccess>(`/subscribers/${listid}/unsubscribe.json`, body);
  }

}