// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { SubscribersDeleteSubscriberOptions, SubscribersDeleteSubscriberResponseSuccess } from './interfaces/delete-subscriber.js';
import type { SubscribersGetSubscriberHistoryOptions, SubscribersGetSubscriberHistoryResponseSuccess } from './interfaces/get-subscriber-history.js';
import type { SubscribersUnsubscribeSubscriberOptions, SubscribersUnsubscribeSubscriberResponseSuccess } from './interfaces/unsubscribe-subscriber.js';

export class Subscribers {
  constructor(private readonly client: Createsend) {}

  /**
   * Subscribers: Delete
   * DELETE subscribers/{listid}.{format}?email={email}
   * @see DELETE /{version}/subscribers/{listId}.{format}
   */
  async deleteSubscriber(options: SubscribersDeleteSubscriberOptions): Promise<Response<SubscribersDeleteSubscriberResponseSuccess>> {
    const { listId, query } = options;
    return this.client.delete<SubscribersDeleteSubscriberResponseSuccess>(`/subscribers/${listId}.json`, { query });
  }

  /**
   * Subscribers: GetSubscriberHistory
   * GET subscribers/{listid}/history.{format}?email={email}
   * @see GET /{version}/subscribers/{listId}/history.{format}
   */
  async getSubscriberHistory(options: SubscribersGetSubscriberHistoryOptions): Promise<Response<SubscribersGetSubscriberHistoryResponseSuccess>> {
    const { listId, query } = options;
    return this.client.get<SubscribersGetSubscriberHistoryResponseSuccess>(`/subscribers/${listId}/history.json`, { query });
  }

  /**
   * Subscribers: Unsubscribe
   * POST subscribers/{listid}/unsubscribe.{format}
   * @see POST /{version}/subscribers/{listId}/unsubscribe.{format}
   */
  async unsubscribeSubscriber(options: SubscribersUnsubscribeSubscriberOptions): Promise<Response<SubscribersUnsubscribeSubscriberResponseSuccess>> {
    const { listId, body } = options;
    return this.client.post<SubscribersUnsubscribeSubscriberResponseSuccess>(`/subscribers/${listId}/unsubscribe.json`, body);
  }

}