// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { UtilBillingDetailsOptions, UtilBillingDetailsResponseSuccess } from './interfaces/billing-details.js';
import type { UtilGetUtilClientsOptions, UtilGetUtilClientsResponseSuccess } from './interfaces/get-util-clients.js';
import type { UtilGetUtilCountriesOptions, UtilGetUtilCountriesResponseSuccess } from './interfaces/get-util-countries.js';
import type { UtilExternalSessionOptions, UtilExternalSessionResponseSuccess } from './interfaces/external-session.js';
import type { UtilSystemDateOptions, UtilSystemDateResponseSuccess } from './interfaces/system-date.js';
import type { UtilGetUtilTimezonesOptions, UtilGetUtilTimezonesResponseSuccess } from './interfaces/get-util-timezones.js';

export class Util {
  constructor(private readonly client: Createsend) {}

  /**
   * Util: BillingDetails
   * GET billingdetails.{format}
   * @see GET /{version}/billingdetails.{format}
   */
  async billingDetails(): Promise<Response<UtilBillingDetailsResponseSuccess>> {
    return this.client.get<UtilBillingDetailsResponseSuccess>(`/billingdetails.json`);
  }

  /**
   * Util: GetUtilClients
   * GET clients.{format}
   * @see GET /{version}/clients.{format}
   */
  async getUtilClients(options: UtilGetUtilClientsOptions): Promise<Response<UtilGetUtilClientsResponseSuccess>> {
    const { query } = options;
    return this.client.get<UtilGetUtilClientsResponseSuccess>(`/clients.json`, { query });
  }

  /**
   * Util: GetUtilCountries
   * GET countries.{format}
   * @see GET /{version}/countries.{format}
   */
  async getUtilCountries(): Promise<Response<UtilGetUtilCountriesResponseSuccess>> {
    return this.client.get<UtilGetUtilCountriesResponseSuccess>(`/countries.json`);
  }

  /**
   * Util: ExternalSession
   * PUT externalsession.{format}
   * @see PUT /{version}/externalsession.{format}
   */
  async externalSession(options: UtilExternalSessionOptions): Promise<Response<UtilExternalSessionResponseSuccess>> {
    const { body } = options;
    return this.client.put<UtilExternalSessionResponseSuccess>(`/externalsession.json`, body);
  }

  /**
   * Util: SystemDate
   * GET systemdate.{format}
   * @see GET /{version}/systemdate.{format}
   */
  async systemDate(): Promise<Response<UtilSystemDateResponseSuccess>> {
    return this.client.get<UtilSystemDateResponseSuccess>(`/systemdate.json`);
  }

  /**
   * Util: GetUtilTimezones
   * GET timezones.{format}
   * @see GET /{version}/timezones.{format}
   */
  async getUtilTimezones(): Promise<Response<UtilGetUtilTimezonesResponseSuccess>> {
    return this.client.get<UtilGetUtilTimezonesResponseSuccess>(`/timezones.json`);
  }

}