// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { UtilApikeyOptions, UtilApikeyResponseSuccess } from './interfaces/apikey.js';
import type { UtilBillingdetailsOptions, UtilBillingdetailsResponseSuccess } from './interfaces/billingdetails.js';
import type { UtilClientsOptions, UtilClientsResponseSuccess } from './interfaces/clients.js';
import type { UtilCountriesOptions, UtilCountriesResponseSuccess } from './interfaces/countries.js';
import type { UtilExternalsessionOptions, UtilExternalsessionResponseSuccess } from './interfaces/externalsession.js';
import type { UtilMeOptions, UtilMeResponseSuccess } from './interfaces/me.js';
import type { UtilProcessCssOptions, UtilProcessCssResponseSuccess } from './interfaces/process-css.js';
import type { UtilRotateApikeyOptions, UtilRotateApikeyResponseSuccess } from './interfaces/rotate-apikey.js';
import type { UtilSystemdateOptions, UtilSystemdateResponseSuccess } from './interfaces/systemdate.js';
import type { UtilTimezonesOptions, UtilTimezonesResponseSuccess } from './interfaces/timezones.js';

export class Util {
  constructor(private readonly client: Createsend) {}

  /**
   * Util: ApiKey
   * GET: /apikey
   * @see GET /{version}/apikey.{format}
   */
  async apikey(): Promise<Response<UtilApikeyResponseSuccess>> {
    return this.client.get<UtilApikeyResponseSuccess>(`/apikey.json`);
  }

  /**
   * Util: BillingDetails
   * GET billingdetails.{format}
   * @see GET /{version}/billingdetails.{format}
   */
  async billingdetails(): Promise<Response<UtilBillingdetailsResponseSuccess>> {
    return this.client.get<UtilBillingdetailsResponseSuccess>(`/billingdetails.json`);
  }

  /**
   * Util: Clients
   * GET clients.{format}
   * @see GET /{version}/clients.{format}
   */
  async clients(options: UtilClientsOptions): Promise<Response<UtilClientsResponseSuccess>> {
    const { query } = options;
    return this.client.get<UtilClientsResponseSuccess>(`/clients.json`, { query });
  }

  /**
   * Util: Countries
   * GET countries.{format}
   * @see GET /{version}/countries.{format}
   */
  async countries(): Promise<Response<UtilCountriesResponseSuccess>> {
    return this.client.get<UtilCountriesResponseSuccess>(`/countries.json`);
  }

  /**
   * Util: Externalsession
   * PUT externalsession.{format}
   * @see PUT /{version}/externalsession.{format}
   */
  async externalsession(options: UtilExternalsessionOptions): Promise<Response<UtilExternalsessionResponseSuccess>> {
    const { body } = options;
    return this.client.put<UtilExternalsessionResponseSuccess>(`/externalsession.json`, body);
  }

  /**
   * Util: Me
   * GET me.{format}[?clientId={clientId}]
   * @see GET /{version}/me.{format}
   */
  async me(options: UtilMeOptions): Promise<Response<UtilMeResponseSuccess>> {
    const { query } = options;
    return this.client.get<UtilMeResponseSuccess>(`/me.json`, { query });
  }

  /**
   * Util: Processcss
   * POST processcss.{format}
   * @see POST /{version}/processcss.{format}
   */
  async processCss(options: UtilProcessCssOptions): Promise<Response<UtilProcessCssResponseSuccess>> {
    const { body } = options;
    return this.client.post<UtilProcessCssResponseSuccess>(`/processcss.json`, body);
  }

  /**
   * Util: Rotateapikey
   * POST: /rotateapikey
   * @see POST /{version}/rotateapikey.{format}
   */
  async rotateApikey(): Promise<Response<UtilRotateApikeyResponseSuccess>> {
    return this.client.post<UtilRotateApikeyResponseSuccess>(`/rotateapikey.json`, undefined);
  }

  /**
   * Util: SystemDate
   * GET systemdate.{format}
   * @see GET /{version}/systemdate.{format}
   */
  async systemdate(): Promise<Response<UtilSystemdateResponseSuccess>> {
    return this.client.get<UtilSystemdateResponseSuccess>(`/systemdate.json`);
  }

  /**
   * Util: Timezones
   * GET timezones.{format}
   * @see GET /{version}/timezones.{format}
   */
  async timezones(): Promise<Response<UtilTimezonesResponseSuccess>> {
    return this.client.get<UtilTimezonesResponseSuccess>(`/timezones.json`);
  }

}