// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { AdminsGetOptions, AdminsGetResponseSuccess } from './interfaces/get.js';
import type { AdminsCreateOptions, AdminsCreateResponseSuccess } from './interfaces/create.js';
import type { AdminsUpdateOptions, AdminsUpdateResponseSuccess } from './interfaces/update.js';
import type { AdminsDeleteOptions, AdminsDeleteResponseSuccess } from './interfaces/delete.js';
import type { AdminsGetPrimarycontactOptions, AdminsGetPrimarycontactResponseSuccess } from './interfaces/get-primarycontact.js';
import type { AdminsSetPrimarycontactOptions, AdminsSetPrimarycontactResponseSuccess } from './interfaces/set-primarycontact.js';

export class Admins {
  constructor(private readonly client: Createsend) {}

  /**
   * Admins: Get
   * GET /admins.{format}?email={email}
   * @see GET /{version}/admins.{format}
   */
  async get(options: AdminsGetOptions): Promise<Response<AdminsGetResponseSuccess>> {
    const { query } = options;
    return this.client.get<AdminsGetResponseSuccess>(`/admins.json`, { query });
  }

  /**
   * Admins: Create
   * POST admins.{format}
   * @see POST /{version}/admins.{format}
   */
  async create(options: AdminsCreateOptions): Promise<Response<AdminsCreateResponseSuccess>> {
    const { body } = options;
    return this.client.post<AdminsCreateResponseSuccess>(`/admins.json`, body);
  }

  /**
   * Admins: Update
   * PUT /admins.{format}?email={email}
   * @see PUT /{version}/admins.{format}
   */
  async update(options: AdminsUpdateOptions): Promise<Response<AdminsUpdateResponseSuccess>> {
    const { query, body } = options;
    return this.client.put<AdminsUpdateResponseSuccess>(`/admins.json`, body, { query });
  }

  /**
   * Admins: Delete
   * DELETE /admins.{format}?email={email}
   * @see DELETE /{version}/admins.{format}
   */
  async delete(options: AdminsDeleteOptions): Promise<Response<AdminsDeleteResponseSuccess>> {
    const { query } = options;
    return this.client.delete<AdminsDeleteResponseSuccess>(`/admins.json`, { query });
  }

  /**
   * Admins: Getprimarycontact
   * GET /primarycontact.{format}
   * @see GET /{version}/primarycontact.{format}
   */
  async getPrimarycontact(): Promise<Response<AdminsGetPrimarycontactResponseSuccess>> {
    return this.client.get<AdminsGetPrimarycontactResponseSuccess>(`/primarycontact.json`);
  }

  /**
   * Admins: Setprimarycontact
   * PUT /primarycontact.{format}
   * @see PUT /{version}/primarycontact.{format}
   */
  async setPrimarycontact(options: AdminsSetPrimarycontactOptions): Promise<Response<AdminsSetPrimarycontactResponseSuccess>> {
    const { query } = options;
    return this.client.put<AdminsSetPrimarycontactResponseSuccess>(`/primarycontact.json`, undefined, { query });
  }

}