// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { AdminsGetAdminOptions, AdminsGetAdminResponseSuccess } from './interfaces/get-admin.js';
import type { AdminsCreateAdminOptions, AdminsCreateAdminResponseSuccess } from './interfaces/create-admin.js';
import type { AdminsUpdateAdminOptions, AdminsUpdateAdminResponseSuccess } from './interfaces/update-admin.js';
import type { AdminsDeleteAdminOptions, AdminsDeleteAdminResponseSuccess } from './interfaces/delete-admin.js';
import type { AdminsGetPrimaryContactOptions, AdminsGetPrimaryContactResponseSuccess } from './interfaces/get-primary-contact.js';
import type { AdminsSetPrimaryContactOptions, AdminsSetPrimaryContactResponseSuccess } from './interfaces/set-primary-contact.js';

export class Admins {
  constructor(private readonly client: Createsend) {}

  /**
   * Admins: Get
   * GET /admins.{format}?email={email}
   * @see GET /{version}/admins.{format}
   */
  async getAdmin(options: AdminsGetAdminOptions): Promise<Response<AdminsGetAdminResponseSuccess>> {
    const { query } = options;
    return this.client.get<AdminsGetAdminResponseSuccess>(`/admins.json`, { query });
  }

  /**
   * Admins: Create
   * POST admins.{format}
   * @see POST /{version}/admins.{format}
   */
  async createAdmin(options: AdminsCreateAdminOptions): Promise<Response<AdminsCreateAdminResponseSuccess>> {
    const { body } = options;
    return this.client.post<AdminsCreateAdminResponseSuccess>(`/admins.json`, body);
  }

  /**
   * Admins: Update
   * PUT /admins.{format}?email={email}
   * @see PUT /{version}/admins.{format}
   */
  async updateAdmin(options: AdminsUpdateAdminOptions): Promise<Response<AdminsUpdateAdminResponseSuccess>> {
    const { query, body } = options;
    return this.client.put<AdminsUpdateAdminResponseSuccess>(`/admins.json`, body, { query });
  }

  /**
   * Admins: Delete
   * DELETE /admins.{format}?email={email}
   * @see DELETE /{version}/admins.{format}
   */
  async deleteAdmin(options: AdminsDeleteAdminOptions): Promise<Response<AdminsDeleteAdminResponseSuccess>> {
    const { query } = options;
    return this.client.delete<AdminsDeleteAdminResponseSuccess>(`/admins.json`, { query });
  }

  /**
   * Admins: GetPrimaryContact
   * GET /primarycontact.{format}
   * @see GET /{version}/primarycontact.{format}
   */
  async getPrimaryContact(): Promise<Response<AdminsGetPrimaryContactResponseSuccess>> {
    return this.client.get<AdminsGetPrimaryContactResponseSuccess>(`/primarycontact.json`);
  }

  /**
   * Admins: SetPrimaryContact
   * PUT /primarycontact.{format}
   * @see PUT /{version}/primarycontact.{format}
   */
  async setPrimaryContact(options: AdminsSetPrimaryContactOptions): Promise<Response<AdminsSetPrimaryContactResponseSuccess>> {
    const { query } = options;
    return this.client.put<AdminsSetPrimaryContactResponseSuccess>(`/primarycontact.json`, undefined, { query });
  }

}