// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { TemplatesCreateOptions, TemplatesCreateResponseSuccess } from './interfaces/create.js';
import type { TemplatesGetOptions, TemplatesGetResponseSuccess } from './interfaces/get.js';
import type { TemplatesUpdateOptions, TemplatesUpdateResponseSuccess } from './interfaces/update.js';
import type { TemplatesDeleteOptions, TemplatesDeleteResponseSuccess } from './interfaces/delete.js';
import type { TemplatesCopyOptions, TemplatesCopyResponseSuccess } from './interfaces/copy.js';
import type { TemplatesCopyBrandedOptions, TemplatesCopyBrandedResponseSuccess } from './interfaces/copy-branded.js';

export class Templates {
  constructor(private readonly client: Createsend) {}

  /**
   * Templates: Create
   * POST templates/{clientid}.{format}
   * @see POST /{version}/templates/{clientid}.{format}
   */
  async create(options: TemplatesCreateOptions): Promise<Response<TemplatesCreateResponseSuccess>> {
    const { clientid, body } = options;
    return this.client.post<TemplatesCreateResponseSuccess>(`/templates/${clientid}.json`, body);
  }

  /**
   * Templates: Get
   * GET templates/{templateid}.{format}
   * @see GET /{version}/templates/{templateid}.{format}
   */
  async get(options: TemplatesGetOptions): Promise<Response<TemplatesGetResponseSuccess>> {
    const { templateid } = options;
    return this.client.get<TemplatesGetResponseSuccess>(`/templates/${templateid}.json`);
  }

  /**
   * Templates: Update
   * PUT templates/{templateid}.{format}
   * @see PUT /{version}/templates/{templateid}.{format}
   */
  async update(options: TemplatesUpdateOptions): Promise<Response<TemplatesUpdateResponseSuccess>> {
    const { templateid, body } = options;
    return this.client.put<TemplatesUpdateResponseSuccess>(`/templates/${templateid}.json`, body);
  }

  /**
   * Templates: Delete
   * DELETE: templates/{templateid}.{format}
   * @see DELETE /{version}/templates/{templateid}.{format}
   */
  async delete(options: TemplatesDeleteOptions): Promise<Response<TemplatesDeleteResponseSuccess>> {
    const { templateid } = options;
    return this.client.delete<TemplatesDeleteResponseSuccess>(`/templates/${templateid}.json`);
  }

  /**
   * Templates: Copy
   * This is an undocumented endpoint, not supported by any of our wrappers, built specifically for one customer (see UX2-118). POST templates/{templateid}/copy.{format}
   * @see POST /{version}/templates/{templateid}/copy.{format}
   */
  async copy(options: TemplatesCopyOptions): Promise<Response<TemplatesCopyResponseSuccess>> {
    const { templateid, body } = options;
    return this.client.post<TemplatesCopyResponseSuccess>(`/templates/${templateid}/copy.json`, body);
  }

  /**
   * Templates: Copybranded
   * POST templates/{templateid}/copy/branded.{format}
   * @see POST /{version}/templates/{templateid}/copy/branded.{format}
   */
  async copyBranded(options: TemplatesCopyBrandedOptions): Promise<Response<TemplatesCopyBrandedResponseSuccess>> {
    const { templateid, body } = options;
    return this.client.post<TemplatesCopyBrandedResponseSuccess>(`/templates/${templateid}/copy/branded.json`, body);
  }

}