// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { TemplatesCreateTemplateOptions, TemplatesCreateTemplateResponseSuccess } from './interfaces/create-template.js';
import type { TemplatesGetTemplateOptions, TemplatesGetTemplateResponseSuccess } from './interfaces/get-template.js';
import type { TemplatesUpdateTemplateOptions, TemplatesUpdateTemplateResponseSuccess } from './interfaces/update-template.js';
import type { TemplatesDeleteTemplateOptions, TemplatesDeleteTemplateResponseSuccess } from './interfaces/delete-template.js';
import type { TemplatesCopyTemplateOptions, TemplatesCopyTemplateResponseSuccess } from './interfaces/copy-template.js';

export class Templates {
  constructor(private readonly client: Createsend) {}

  /**
   * Templates: Create
   * POST templates/{clientid}.{format}
   * @see POST /{version}/templates/{clientId}.{format}
   */
  async createTemplate(options: TemplatesCreateTemplateOptions): Promise<Response<TemplatesCreateTemplateResponseSuccess>> {
    const { clientId, body } = options;
    return this.client.post<TemplatesCreateTemplateResponseSuccess>(`/templates/${clientId}.json`, body);
  }

  /**
   * Templates: Get
   * GET templates/{templateid}.{format}
   * @see GET /{version}/templates/{templateId}.{format}
   */
  async getTemplate(options: TemplatesGetTemplateOptions): Promise<Response<TemplatesGetTemplateResponseSuccess>> {
    const { templateId } = options;
    return this.client.get<TemplatesGetTemplateResponseSuccess>(`/templates/${templateId}.json`);
  }

  /**
   * Templates: Update
   * PUT templates/{templateid}.{format}
   * @see PUT /{version}/templates/{templateId}.{format}
   */
  async updateTemplate(options: TemplatesUpdateTemplateOptions): Promise<Response<TemplatesUpdateTemplateResponseSuccess>> {
    const { templateId, body } = options;
    return this.client.put<TemplatesUpdateTemplateResponseSuccess>(`/templates/${templateId}.json`, body);
  }

  /**
   * Templates: Delete
   * DELETE: templates/{templateid}.{format}
   * @see DELETE /{version}/templates/{templateId}.{format}
   */
  async deleteTemplate(options: TemplatesDeleteTemplateOptions): Promise<Response<TemplatesDeleteTemplateResponseSuccess>> {
    const { templateId } = options;
    return this.client.delete<TemplatesDeleteTemplateResponseSuccess>(`/templates/${templateId}.json`);
  }

  /**
   * Templates: Copy
   * This is an undocumented endpoint, not supported by any of our wrappers, built specifically for one customer (see UX2-118). POST templates/{templateid}/copy.{format}
   * @see POST /{version}/templates/{templateId}/copy.{format}
   */
  async copyTemplate(options: TemplatesCopyTemplateOptions): Promise<Response<TemplatesCopyTemplateResponseSuccess>> {
    const { templateId, body } = options;
    return this.client.post<TemplatesCopyTemplateResponseSuccess>(`/templates/${templateId}/copy.json`, body);
  }

}