// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { MessageGetMessageTimelineOptions, MessageGetMessageTimelineResponseSuccess } from './interfaces/get-message-timeline.js';
import type { MessageMessageDetailsOptions, MessageMessageDetailsResponseSuccess } from './interfaces/message-details.js';
import type { MessageResendMessageOptions, MessageResendMessageResponseSuccess } from './interfaces/resend-message.js';

export class Message {
  constructor(private readonly client: Createsend) {}

  /**
   * Message: GetMessageTimeline
   * Timeline of transactional events for a client
   * @see GET /{version}/transactional/messages
   */
  async getMessageTimeline(options: MessageGetMessageTimelineOptions): Promise<Response<MessageGetMessageTimelineResponseSuccess>> {
    const { query } = options;
    return this.client.get<MessageGetMessageTimelineResponseSuccess>(`/transactional/messages`, { query });
  }

  /**
   * Message: MessageDetails
   * Details for a single message
   * @see GET /{version}/transactional/messages/{messageId}
   */
  async messageDetails(options: MessageMessageDetailsOptions): Promise<Response<MessageMessageDetailsResponseSuccess>> {
    const { messageId } = options;
    return this.client.get<MessageMessageDetailsResponseSuccess>(`/transactional/messages/${messageId}`);
  }

  /**
   * Message: Resend
   * @see POST /{version}/transactional/messages/{messageId}/resend
   */
  async resendMessage(options: MessageResendMessageOptions): Promise<Response<MessageResendMessageResponseSuccess>> {
    const { messageId, body } = options;
    return this.client.post<MessageResendMessageResponseSuccess>(`/transactional/messages/${messageId}/resend`, body);
  }

}