// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { MessageTimelineOptions, MessageTimelineResponseSuccess } from './interfaces/timeline.js';
import type { MessageMessagedetailsOptions, MessageMessagedetailsResponseSuccess } from './interfaces/messagedetails.js';
import type { MessageResendOptions, MessageResendResponseSuccess } from './interfaces/resend.js';

export class Message {
  constructor(private readonly client: Createsend) {}

  /**
   * Message: Timeline
   * Timeline of transactional events for a client
   * @see GET /{version}/transactional/messages.{format}
   */
  async timeline(): Promise<Response<MessageTimelineResponseSuccess>> {
    return this.client.get<MessageTimelineResponseSuccess>(`/transactional/messages.json`);
  }

  /**
   * Message: MessageDetails
   * Details for a single message
   * @see GET /{version}/transactional/messages/{messageId}.{format}
   */
  async messagedetails(options: MessageMessagedetailsOptions): Promise<Response<MessageMessagedetailsResponseSuccess>> {
    const { messageId } = options;
    return this.client.get<MessageMessagedetailsResponseSuccess>(`/transactional/messages/${messageId}.json`);
  }

  /**
   * Message: Resend
   * @see POST /{version}/transactional/messages/{messageId}/resend.{format}
   */
  async resend(options: MessageResendOptions): Promise<Response<MessageResendResponseSuccess>> {
    const { messageId, body } = options;
    return this.client.post<MessageResendResponseSuccess>(`/transactional/messages/${messageId}/resend.json`, body);
  }

}