// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { PeopleGetPersonOptions, PeopleGetPersonResponseSuccess } from './interfaces/get-person.js';
import type { PeopleCreatePersonOptions, PeopleCreatePersonResponseSuccess } from './interfaces/create-person.js';
import type { PeopleUpdatePersonOptions, PeopleUpdatePersonResponseSuccess } from './interfaces/update-person.js';
import type { PeopleDeletePersonOptions, PeopleDeletePersonResponseSuccess } from './interfaces/delete-person.js';
import type { PeopleGetPrimaryContactClientsIdPrimarycontactFormatOptions, PeopleGetPrimaryContactClientsIdPrimarycontactFormatResponseSuccess } from './interfaces/get-primary-contact-clients-id-primarycontact-format.js';
import type { PeopleSetPrimaryContactClientsIdPrimarycontactFormatOptions, PeopleSetPrimaryContactClientsIdPrimarycontactFormatResponseSuccess } from './interfaces/set-primary-contact-clients-id-primarycontact-format.js';

export class People {
  constructor(private readonly client: Createsend) {}

  /**
   * People: Get
   * GET /clients/{id}/people.{format}?email={email}&includeLastLoginUtc={includeLastLoginUtc}&includeTwoFactorStatus={includeTwoFactorStatus} EL-991 - includeLastLoginUtc and includeTwoFactorStatus is not a published API feature
   * @see GET /{version}/clients/{id}/people.{format}
   */
  async getPerson(options: PeopleGetPersonOptions): Promise<Response<PeopleGetPersonResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<PeopleGetPersonResponseSuccess>(`/clients/${id}/people.json`, { query });
  }

  /**
   * People: Create
   * POST clients/{id}/people.{format}
   * @see POST /{version}/clients/{id}/people.{format}
   */
  async createPerson(options: PeopleCreatePersonOptions): Promise<Response<PeopleCreatePersonResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<PeopleCreatePersonResponseSuccess>(`/clients/${id}/people.json`, body);
  }

  /**
   * People: Update
   * PUT /clients/{id}/people.{format}?email={email}
   * @see PUT /{version}/clients/{id}/people.{format}
   */
  async updatePerson(options: PeopleUpdatePersonOptions): Promise<Response<PeopleUpdatePersonResponseSuccess>> {
    const { id, query, body } = options;
    return this.client.put<PeopleUpdatePersonResponseSuccess>(`/clients/${id}/people.json`, body, { query });
  }

  /**
   * People: Delete
   * DELETE /clients/{id}/people.{format}?email={email}
   * @see DELETE /{version}/clients/{id}/people.{format}
   */
  async deletePerson(options: PeopleDeletePersonOptions): Promise<Response<PeopleDeletePersonResponseSuccess>> {
    const { id, query } = options;
    return this.client.delete<PeopleDeletePersonResponseSuccess>(`/clients/${id}/people.json`, { query });
  }

  /**
   * People: GetPrimaryContact
   * GET /clients/{id}/primarycontact.{format}
   * @see GET /{version}/clients/{id}/primarycontact.{format}
   */
  async getPrimaryContactClientsIdPrimarycontactFormat(options: PeopleGetPrimaryContactClientsIdPrimarycontactFormatOptions): Promise<Response<PeopleGetPrimaryContactClientsIdPrimarycontactFormatResponseSuccess>> {
    const { id } = options;
    return this.client.get<PeopleGetPrimaryContactClientsIdPrimarycontactFormatResponseSuccess>(`/clients/${id}/primarycontact.json`);
  }

  /**
   * People: SetPrimaryContact
   * PUT /clients/{id}/primarycontact.{format}
   * @see PUT /{version}/clients/{id}/primarycontact.{format}
   */
  async setPrimaryContactClientsIdPrimarycontactFormat(options: PeopleSetPrimaryContactClientsIdPrimarycontactFormatOptions): Promise<Response<PeopleSetPrimaryContactClientsIdPrimarycontactFormatResponseSuccess>> {
    const { id, query } = options;
    return this.client.put<PeopleSetPrimaryContactClientsIdPrimarycontactFormatResponseSuccess>(`/clients/${id}/primarycontact.json`, undefined, { query });
  }

}