// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { PeopleGetOptions, PeopleGetResponseSuccess } from './interfaces/get.js';
import type { PeopleCreateOptions, PeopleCreateResponseSuccess } from './interfaces/create.js';
import type { PeopleUpdateOptions, PeopleUpdateResponseSuccess } from './interfaces/update.js';
import type { PeopleDeleteOptions, PeopleDeleteResponseSuccess } from './interfaces/delete.js';
import type { PeopleGetPrimarycontactOptions, PeopleGetPrimarycontactResponseSuccess } from './interfaces/get-primarycontact.js';
import type { PeopleSetPrimarycontactOptions, PeopleSetPrimarycontactResponseSuccess } from './interfaces/set-primarycontact.js';

export class People {
  constructor(private readonly client: Createsend) {}

  /**
   * People: Get
   * GET /clients/{id}/people.{format}?email={email}&includeLastLoginUtc={includeLastLoginUtc}&includeTwoFactorStatus={includeTwoFactorStatus} EL-991 - includeLastLoginUtc and includeTwoFactorStatus is not a published API feature
   * @see GET /{version}/clients/{id}/people.{format}
   */
  async get(options: PeopleGetOptions): Promise<Response<PeopleGetResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<PeopleGetResponseSuccess>(`/clients/${id}/people.json`, { query });
  }

  /**
   * People: Create
   * POST clients/{id}/people.{format}
   * @see POST /{version}/clients/{id}/people.{format}
   */
  async create(options: PeopleCreateOptions): Promise<Response<PeopleCreateResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<PeopleCreateResponseSuccess>(`/clients/${id}/people.json`, body);
  }

  /**
   * People: Update
   * PUT /clients/{id}/people.{format}?email={email}
   * @see PUT /{version}/clients/{id}/people.{format}
   */
  async update(options: PeopleUpdateOptions): Promise<Response<PeopleUpdateResponseSuccess>> {
    const { id, query, body } = options;
    return this.client.put<PeopleUpdateResponseSuccess>(`/clients/${id}/people.json`, body, { query });
  }

  /**
   * People: Delete
   * DELETE /clients/{id}/people.{format}?email={email}
   * @see DELETE /{version}/clients/{id}/people.{format}
   */
  async delete(options: PeopleDeleteOptions): Promise<Response<PeopleDeleteResponseSuccess>> {
    const { id, query } = options;
    return this.client.delete<PeopleDeleteResponseSuccess>(`/clients/${id}/people.json`, { query });
  }

  /**
   * People: Getprimarycontact
   * GET /clients/{id}/primarycontact.{format}
   * @see GET /{version}/clients/{id}/primarycontact.{format}
   */
  async getPrimarycontact(options: PeopleGetPrimarycontactOptions): Promise<Response<PeopleGetPrimarycontactResponseSuccess>> {
    const { id } = options;
    return this.client.get<PeopleGetPrimarycontactResponseSuccess>(`/clients/${id}/primarycontact.json`);
  }

  /**
   * People: Setprimarycontact
   * PUT /clients/{id}/primarycontact.{format}
   * @see PUT /{version}/clients/{id}/primarycontact.{format}
   */
  async setPrimarycontact(options: PeopleSetPrimarycontactOptions): Promise<Response<PeopleSetPrimarycontactResponseSuccess>> {
    const { id, query } = options;
    return this.client.put<PeopleSetPrimarycontactResponseSuccess>(`/clients/${id}/primarycontact.json`, undefined, { query });
  }

}