// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { SegmentsNewCreateOptions, SegmentsNewCreateResponseSuccess } from './interfaces/new-create.js';
import type { SegmentsNewGetOptions, SegmentsNewGetResponseSuccess } from './interfaces/new-get.js';
import type { SegmentsNewUpdateOptions, SegmentsNewUpdateResponseSuccess } from './interfaces/new-update.js';
import type { SegmentsDeleteSegmentOptions, SegmentsDeleteSegmentResponseSuccess } from './interfaces/delete-segment.js';
import type { SegmentsGetSegmentSubscribersWithListJoinedDateOptions, SegmentsGetSegmentSubscribersWithListJoinedDateResponseSuccess } from './interfaces/get-segment-subscribers-with-list-joined-date.js';
import type { SegmentsNewAddRuleOptions, SegmentsNewAddRuleResponseSuccess } from './interfaces/new-add-rule.js';
import type { SegmentsClearRulesOptions, SegmentsClearRulesResponseSuccess } from './interfaces/clear-rules.js';

export class Segments {
  constructor(private readonly client: Createsend) {}

  /**
   * Segments: NewCreate
   * POST v3.1/segments/{listid}.{format}
   * @see POST /{version}/segments/{listId}.{format}
   */
  async newCreate(options: SegmentsNewCreateOptions): Promise<Response<SegmentsNewCreateResponseSuccess>> {
    const { listId, body } = options;
    return this.client.post<SegmentsNewCreateResponseSuccess>(`/segments/${listId}.json`, body);
  }

  /**
   * Segments: NewGet
   * GET segments/{segmentid}.{format}
   * @see GET /{version}/segments/{segmentId}.{format}
   */
  async newGet(options: SegmentsNewGetOptions): Promise<Response<SegmentsNewGetResponseSuccess>> {
    const { segmentId } = options;
    return this.client.get<SegmentsNewGetResponseSuccess>(`/segments/${segmentId}.json`);
  }

  /**
   * Segments: NewUpdate
   * PUT v3.1/segments/{segmentid}.{format}
   * @see PUT /{version}/segments/{segmentId}.{format}
   */
  async newUpdate(options: SegmentsNewUpdateOptions): Promise<Response<SegmentsNewUpdateResponseSuccess>> {
    const { segmentId, body } = options;
    return this.client.put<SegmentsNewUpdateResponseSuccess>(`/segments/${segmentId}.json`, body);
  }

  /**
   * Segments: Delete
   * DELETE segments/{segmentid}.{format}
   * @see DELETE /{version}/segments/{segmentId}.{format}
   */
  async deleteSegment(options: SegmentsDeleteSegmentOptions): Promise<Response<SegmentsDeleteSegmentResponseSuccess>> {
    const { segmentId } = options;
    return this.client.delete<SegmentsDeleteSegmentResponseSuccess>(`/segments/${segmentId}.json`);
  }

  /**
   * Segments: GetSegmentSubscribersWithListJoinedDate
   * @see GET /{version}/segments/{segmentId}/active.{format}
   */
  async getSegmentSubscribersWithListJoinedDate(options: SegmentsGetSegmentSubscribersWithListJoinedDateOptions): Promise<Response<SegmentsGetSegmentSubscribersWithListJoinedDateResponseSuccess>> {
    const { segmentId, query } = options;
    return this.client.get<SegmentsGetSegmentSubscribersWithListJoinedDateResponseSuccess>(`/segments/${segmentId}/active.json`, { query });
  }

  /**
   * Segments: NewAddRule
   * POST v3.1/segments/{segmentid}/rules.{format}
   * @see POST /{version}/segments/{segmentId}/rules.{format}
   */
  async newAddRule(options: SegmentsNewAddRuleOptions): Promise<Response<SegmentsNewAddRuleResponseSuccess>> {
    const { segmentId, body } = options;
    return this.client.post<SegmentsNewAddRuleResponseSuccess>(`/segments/${segmentId}/rules.json`, body);
  }

  /**
   * Segments: ClearRules
   * DELETE segments/{segmentid}/rules.{format}
   * @see DELETE /{version}/segments/{segmentId}/rules.{format}
   */
  async clearRules(options: SegmentsClearRulesOptions): Promise<Response<SegmentsClearRulesResponseSuccess>> {
    const { segmentId } = options;
    return this.client.delete<SegmentsClearRulesResponseSuccess>(`/segments/${segmentId}/rules.json`);
  }

}