// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { SegmentsNewCreateOptions, SegmentsNewCreateResponseSuccess } from './interfaces/new-create.js';
import type { SegmentsGetSegmentsubscriberswithlistjoineddateOptions, SegmentsGetSegmentsubscriberswithlistjoineddateResponseSuccess } from './interfaces/get-segmentsubscriberswithlistjoineddate.js';
import type { SegmentsNewGetOptions, SegmentsNewGetResponseSuccess } from './interfaces/new-get.js';
import type { SegmentsNewUpdateOptions, SegmentsNewUpdateResponseSuccess } from './interfaces/new-update.js';
import type { SegmentsDeleteOptions, SegmentsDeleteResponseSuccess } from './interfaces/delete.js';
import type { SegmentsGetSegmentsubscribersOptions, SegmentsGetSegmentsubscribersResponseSuccess } from './interfaces/get-segmentsubscribers.js';
import type { SegmentsNewAddruleOptions, SegmentsNewAddruleResponseSuccess } from './interfaces/new-addrule.js';
import type { SegmentsClearrulesOptions, SegmentsClearrulesResponseSuccess } from './interfaces/clearrules.js';

export class Segments {
  constructor(private readonly client: Createsend) {}

  /**
   * Segments: Newcreate
   * POST v3.1/segments/{listid}.{format}
   * @see POST /{version}/segments/{listid}.{format}
   */
  async newCreate(options: SegmentsNewCreateOptions): Promise<Response<SegmentsNewCreateResponseSuccess>> {
    const { listid, body } = options;
    return this.client.post<SegmentsNewCreateResponseSuccess>(`/segments/${listid}.json`, body);
  }

  /**
   * Segments: Getsegmentsubscriberswithlistjoineddate
   * @see GET /{version}/segments/{segmentId}/active.{format}
   */
  async getSegmentsubscriberswithlistjoineddate(options: SegmentsGetSegmentsubscriberswithlistjoineddateOptions): Promise<Response<SegmentsGetSegmentsubscriberswithlistjoineddateResponseSuccess>> {
    const { segmentId, query } = options;
    return this.client.get<SegmentsGetSegmentsubscriberswithlistjoineddateResponseSuccess>(`/segments/${segmentId}/active.json`, { query });
  }

  /**
   * Segments: Newget
   * GET segments/{segmentid}.{format}
   * @see GET /{version}/segments/{segmentid}.{format}
   */
  async newGet(options: SegmentsNewGetOptions): Promise<Response<SegmentsNewGetResponseSuccess>> {
    const { segmentid } = options;
    return this.client.get<SegmentsNewGetResponseSuccess>(`/segments/${segmentid}.json`);
  }

  /**
   * Segments: Newupdate
   * PUT v3.1/segments/{segmentid}.{format}
   * @see PUT /{version}/segments/{segmentid}.{format}
   */
  async newUpdate(options: SegmentsNewUpdateOptions): Promise<Response<SegmentsNewUpdateResponseSuccess>> {
    const { segmentid, body } = options;
    return this.client.put<SegmentsNewUpdateResponseSuccess>(`/segments/${segmentid}.json`, body);
  }

  /**
   * Segments: Delete
   * DELETE segments/{segmentid}.{format}
   * @see DELETE /{version}/segments/{segmentid}.{format}
   */
  async delete(options: SegmentsDeleteOptions): Promise<Response<SegmentsDeleteResponseSuccess>> {
    const { segmentid } = options;
    return this.client.delete<SegmentsDeleteResponseSuccess>(`/segments/${segmentid}.json`);
  }

  /**
   * Segments: Getsegmentsubscribers
   * @see GET /{version}/segments/{segmentid}/active.{format}
   */
  async getSegmentsubscribers(options: SegmentsGetSegmentsubscribersOptions): Promise<Response<SegmentsGetSegmentsubscribersResponseSuccess>> {
    const { segmentid, query } = options;
    return this.client.get<SegmentsGetSegmentsubscribersResponseSuccess>(`/segments/${segmentid}/active.json`, { query });
  }

  /**
   * Segments: Newaddrule
   * POST v3.1/segments/{segmentid}/rules.{format}
   * @see POST /{version}/segments/{segmentid}/rules.{format}
   */
  async newAddrule(options: SegmentsNewAddruleOptions): Promise<Response<SegmentsNewAddruleResponseSuccess>> {
    const { segmentid, body } = options;
    return this.client.post<SegmentsNewAddruleResponseSuccess>(`/segments/${segmentid}/rules.json`, body);
  }

  /**
   * Segments: Clearrules
   * DELETE segments/{segmentid}/rules.{format}
   * @see DELETE /{version}/segments/{segmentid}/rules.{format}
   */
  async clearrules(options: SegmentsClearrulesOptions): Promise<Response<SegmentsClearrulesResponseSuccess>> {
    const { segmentid } = options;
    return this.client.delete<SegmentsClearrulesResponseSuccess>(`/segments/${segmentid}/rules.json`);
  }

}