// DO NOT EDIT — generated by scripts/generate.ts
// Source: accounts_create

import type { AccountProvisioningModel } from '../../generated/schema.js';

export interface AccountsCreateOptions {
  body: AccountProvisioningModel;
}

export type AccountsCreateResponseSuccess = {
  dbid?: string;
  accountid?: number;
  clientid?: number;
  globalAccountId?: string;
  accessUrl?: string;
  username?: string;
  tempPassword?: string;
};
