// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { StatisticsIndexOptions, StatisticsIndexResponseSuccess } from './interfaces/index-get.js';

export class Statistics {
  constructor(private readonly client: Createsend) {}

  /**
   * Statistics: Index
   * @see GET /{version}/transactional/statistics.{format}
   */
  async index(): Promise<Response<StatisticsIndexResponseSuccess>> {
    return this.client.get<StatisticsIndexResponseSuccess>(`/transactional/statistics.json`);
  }

}