// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { StatisticsIndexStatisticOptions, StatisticsIndexStatisticResponseSuccess } from './interfaces/index-statistic.js';

export class Statistics {
  constructor(private readonly client: Createsend) {}

  /**
   * Statistics: Index
   * @see GET /{version}/transactional/statistics
   */
  async indexStatistic(options: StatisticsIndexStatisticOptions): Promise<Response<StatisticsIndexStatisticResponseSuccess>> {
    const { query } = options;
    return this.client.get<StatisticsIndexStatisticResponseSuccess>(`/transactional/statistics`, { query });
  }

}