// DO NOT EDIT — generated by scripts/generate.ts
// Source: people_create

import type { AddPerson, AddPersonReponse } from '../../generated/schema.js';

export interface PeopleCreateOptions {
  id: string;
  body: AddPerson;
}

export type PeopleCreateResponseSuccess = AddPersonReponse;
