// DO NOT EDIT — generated by scripts/generate.ts
// Source: createPerson

import type { AddPerson, AddPersonReponse } from '../../generated/schema.js';

export interface PeopleCreatePersonOptions {
  id: string;
  body: AddPerson;
}

export type PeopleCreatePersonResponseSuccess = AddPersonReponse;
