// DO NOT EDIT — generated by scripts/generate.ts
// Source: people_delete

export interface PeopleDeleteQuery {
  [key: string]: unknown;
  email: string;
}

export interface PeopleDeleteOptions {
  id: string;
  query?: PeopleDeleteQuery;
}

export type PeopleDeleteResponseSuccess = unknown;
