// DO NOT EDIT — generated by scripts/generate.ts
// Source: deletePerson

export interface PeopleDeletePersonQuery {
  [key: string]: unknown;
  email: string;
}

export interface PeopleDeletePersonOptions {
  id: string;
  query?: PeopleDeletePersonQuery;
}

export type PeopleDeletePersonResponseSuccess = unknown;
