// DO NOT EDIT — generated by scripts/generate.ts
// Source: getPrimaryContactClientsIdPrimarycontactFormat

import type { PrimaryContact } from '../../generated/schema.js';

export interface PeopleGetPrimaryContactClientsIdPrimarycontactFormatOptions {
  id: string;
}

export type PeopleGetPrimaryContactClientsIdPrimarycontactFormatResponseSuccess = PrimaryContact;
