// DO NOT EDIT — generated by scripts/generate.ts
// Source: people_getprimarycontact

import type { PrimaryContact } from '../../generated/schema.js';

export interface PeopleGetPrimarycontactOptions {
  id: string;
}

export type PeopleGetPrimarycontactResponseSuccess = PrimaryContact;
