// DO NOT EDIT — generated by scripts/generate.ts
// Source: getPerson

import type { Person } from '../../generated/schema.js';

export interface PeopleGetPersonQuery {
  [key: string]: unknown;
  email: string;
  includeLastLoginUtc?: boolean;
  includeTwoFactorStatus?: boolean;
}

export interface PeopleGetPersonOptions {
  id: string;
  query?: PeopleGetPersonQuery;
}

export type PeopleGetPersonResponseSuccess = Person;
