// DO NOT EDIT — generated by scripts/generate.ts
// Source: people_get

import type { Person } from '../../generated/schema.js';

export interface PeopleGetQuery {
  [key: string]: unknown;
  email: string;
  includeLastLoginUtc?: boolean;
  includeTwoFactorStatus?: boolean;
}

export interface PeopleGetOptions {
  id: string;
  query?: PeopleGetQuery;
}

export type PeopleGetResponseSuccess = Array<Person>;
