// DO NOT EDIT — generated by scripts/generate.ts

export type { PeopleGetOptions, PeopleGetResponseSuccess } from './get.js';
export type { PeopleCreateOptions, PeopleCreateResponseSuccess } from './create.js';
export type { PeopleUpdateOptions, PeopleUpdateResponseSuccess } from './update.js';
export type { PeopleDeleteOptions, PeopleDeleteResponseSuccess } from './delete.js';
export type { PeopleGetPrimarycontactOptions, PeopleGetPrimarycontactResponseSuccess } from './get-primarycontact.js';
export type { PeopleSetPrimarycontactOptions, PeopleSetPrimarycontactResponseSuccess } from './set-primarycontact.js';
