// DO NOT EDIT — generated by scripts/generate.ts

export type { PeopleGetPersonOptions, PeopleGetPersonResponseSuccess } from './get-person.js';
export type { PeopleCreatePersonOptions, PeopleCreatePersonResponseSuccess } from './create-person.js';
export type { PeopleUpdatePersonOptions, PeopleUpdatePersonResponseSuccess } from './update-person.js';
export type { PeopleDeletePersonOptions, PeopleDeletePersonResponseSuccess } from './delete-person.js';
export type { PeopleGetPrimaryContactClientsIdPrimarycontactFormatOptions, PeopleGetPrimaryContactClientsIdPrimarycontactFormatResponseSuccess } from './get-primary-contact-clients-id-primarycontact-format.js';
export type { PeopleSetPrimaryContactClientsIdPrimarycontactFormatOptions, PeopleSetPrimaryContactClientsIdPrimarycontactFormatResponseSuccess } from './set-primary-contact-clients-id-primarycontact-format.js';
