// DO NOT EDIT — generated by scripts/generate.ts
// Source: people_setprimarycontact

import type { PrimaryContact } from '../../generated/schema.js';

export interface PeopleSetPrimarycontactQuery {
  [key: string]: unknown;
  email: string;
}

export interface PeopleSetPrimarycontactOptions {
  id: string;
  query?: PeopleSetPrimarycontactQuery;
}

export type PeopleSetPrimarycontactResponseSuccess = PrimaryContact;
