// DO NOT EDIT — generated by scripts/generate.ts
// Source: setPrimaryContactClientsIdPrimarycontactFormat

import type { PrimaryContact } from '../../generated/schema.js';

export interface PeopleSetPrimaryContactClientsIdPrimarycontactFormatQuery {
  [key: string]: unknown;
  email: string;
}

export interface PeopleSetPrimaryContactClientsIdPrimarycontactFormatOptions {
  id: string;
  query?: PeopleSetPrimaryContactClientsIdPrimarycontactFormatQuery;
}

export type PeopleSetPrimaryContactClientsIdPrimarycontactFormatResponseSuccess = PrimaryContact;
