// DO NOT EDIT — generated by scripts/generate.ts
// Source: people_update

import type { UpdatePerson, UpdatePersonReponse } from '../../generated/schema.js';

export interface PeopleUpdateQuery {
  [key: string]: unknown;
  email: string;
}

export interface PeopleUpdateOptions {
  id: string;
  query?: PeopleUpdateQuery;
  body: UpdatePerson;
}

export type PeopleUpdateResponseSuccess = UpdatePersonReponse;
