// DO NOT EDIT — generated by scripts/generate.ts
// Source: updatePerson

import type { UpdatePerson, UpdatePersonReponse } from '../../generated/schema.js';

export interface PeopleUpdatePersonQuery {
  [key: string]: unknown;
  email: string;
}

export interface PeopleUpdatePersonOptions {
  id: string;
  query?: PeopleUpdatePersonQuery;
  body: UpdatePerson;
}

export type PeopleUpdatePersonResponseSuccess = UpdatePersonReponse;
