// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { WorkflowemailsEmailbouncesOptions, WorkflowemailsEmailbouncesResponseSuccess } from './interfaces/emailbounces.js';
import type { WorkflowemailsEmailclicksOptions, WorkflowemailsEmailclicksResponseSuccess } from './interfaces/emailclicks.js';
import type { WorkflowemailsEmailopensOptions, WorkflowemailsEmailopensResponseSuccess } from './interfaces/emailopens.js';
import type { WorkflowemailsEmailrecipientsOptions, WorkflowemailsEmailrecipientsResponseSuccess } from './interfaces/emailrecipients.js';
import type { WorkflowemailsEmailunsubscribesOptions, WorkflowemailsEmailunsubscribesResponseSuccess } from './interfaces/emailunsubscribes.js';

export class Workflowemails {
  constructor(private readonly client: Createsend) {}

  /**
   * Workflowemails: Emailbounces
   * GET /journeys/email/{emailId}/bounces.{format}
   * @see GET /{version}/journeys/email/{emailid}/bounces.{format}
   */
  async emailbounces(options: WorkflowemailsEmailbouncesOptions): Promise<Response<WorkflowemailsEmailbouncesResponseSuccess>> {
    const { emailid, query } = options;
    return this.client.get<WorkflowemailsEmailbouncesResponseSuccess>(`/journeys/email/${emailid}/bounces.json`, { query });
  }

  /**
   * Workflowemails: Emailclicks
   * GET /journeys/email/{emailId}/clicks.{format}
   * @see GET /{version}/journeys/email/{emailid}/clicks.{format}
   */
  async emailclicks(options: WorkflowemailsEmailclicksOptions): Promise<Response<WorkflowemailsEmailclicksResponseSuccess>> {
    const { emailid, query } = options;
    return this.client.get<WorkflowemailsEmailclicksResponseSuccess>(`/journeys/email/${emailid}/clicks.json`, { query });
  }

  /**
   * Workflowemails: Emailopens
   * GET /journeys/email/{emailId}/opens.{format}
   * @see GET /{version}/journeys/email/{emailid}/opens.{format}
   */
  async emailopens(options: WorkflowemailsEmailopensOptions): Promise<Response<WorkflowemailsEmailopensResponseSuccess>> {
    const { emailid, query } = options;
    return this.client.get<WorkflowemailsEmailopensResponseSuccess>(`/journeys/email/${emailid}/opens.json`, { query });
  }

  /**
   * Workflowemails: Emailrecipients
   * GET /journeys/email/{emailId}/recipients.{format}
   * @see GET /{version}/journeys/email/{emailid}/recipients.{format}
   */
  async emailrecipients(options: WorkflowemailsEmailrecipientsOptions): Promise<Response<WorkflowemailsEmailrecipientsResponseSuccess>> {
    const { emailid, query } = options;
    return this.client.get<WorkflowemailsEmailrecipientsResponseSuccess>(`/journeys/email/${emailid}/recipients.json`, { query });
  }

  /**
   * Workflowemails: Emailunsubscribes
   * GET /journeys/email/{emailId}/unsubscribes.{format}
   * @see GET /{version}/journeys/email/{emailid}/unsubscribes.{format}
   */
  async emailunsubscribes(options: WorkflowemailsEmailunsubscribesOptions): Promise<Response<WorkflowemailsEmailunsubscribesResponseSuccess>> {
    const { emailid, query } = options;
    return this.client.get<WorkflowemailsEmailunsubscribesResponseSuccess>(`/journeys/email/${emailid}/unsubscribes.json`, { query });
  }

}