// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { AnonymousJsontorssOptions, AnonymousJsontorssResponseSuccess } from './interfaces/jsontorss.js';

export class Anonymous {
  constructor(private readonly client: Createsend) {}

  /**
   * Anonymous: Jsontorss
   * @see GET /{version}/jsontorss.xml
   */
  async jsontorss(options: AnonymousJsontorssOptions): Promise<Response<AnonymousJsontorssResponseSuccess>> {
    const { query } = options;
    return this.client.get<AnonymousJsontorssResponseSuccess>(`/jsontorss.xml`, { query });
  }

}