// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { CampaignsCreateOptions, CampaignsCreateResponseSuccess } from './interfaces/create.js';
import type { CampaignsDeleteOptions, CampaignsDeleteResponseSuccess } from './interfaces/delete.js';
import type { CampaignsBouncesOptions, CampaignsBouncesResponseSuccess } from './interfaces/bounces.js';
import type { CampaignsClicksOptions, CampaignsClicksResponseSuccess } from './interfaces/clicks.js';
import type { CampaignsClicksummaryOptions, CampaignsClicksummaryResponseSuccess } from './interfaces/clicksummary.js';
import type { CampaignsCountrysummaryOptions, CampaignsCountrysummaryResponseSuccess } from './interfaces/countrysummary.js';
import type { CampaignsEmailclientusageOptions, CampaignsEmailclientusageResponseSuccess } from './interfaces/emailclientusage.js';
import type { CampaignsCreateFromtemplateOptions, CampaignsCreateFromtemplateResponseSuccess } from './interfaces/create-fromtemplate.js';
import type { CampaignsListSandsegmentsOptions, CampaignsListSandsegmentsResponseSuccess } from './interfaces/list-sandsegments.js';
import type { CampaignsOpensOptions, CampaignsOpensResponseSuccess } from './interfaces/opens.js';
import type { CampaignsRecipientactivityOptions, CampaignsRecipientactivityResponseSuccess } from './interfaces/recipientactivity.js';
import type { CampaignsRecipientsOptions, CampaignsRecipientsResponseSuccess } from './interfaces/recipients.js';
import type { CampaignsSendOptions, CampaignsSendResponseSuccess } from './interfaces/send.js';
import type { CampaignsSendPreviewOptions, CampaignsSendPreviewResponseSuccess } from './interfaces/send-preview.js';
import type { CampaignsSpamOptions, CampaignsSpamResponseSuccess } from './interfaces/spam.js';
import type { CampaignsSummarywithnameOptions, CampaignsSummarywithnameResponseSuccess } from './interfaces/summarywithname.js';
import type { CampaignsTimelineOptions, CampaignsTimelineResponseSuccess } from './interfaces/timeline.js';
import type { CampaignsUnscheduleasyncOptions, CampaignsUnscheduleasyncResponseSuccess } from './interfaces/unscheduleasync.js';
import type { CampaignsUnsubscribesOptions, CampaignsUnsubscribesResponseSuccess } from './interfaces/unsubscribes.js';

export class Campaigns {
  constructor(private readonly client: Createsend) {}

  /**
   * Campaigns: Create
   * POST campaigns/{id}.{format}
   * @see POST /{version}/campaigns/{id}.{format}
   */
  async create(options: CampaignsCreateOptions): Promise<Response<CampaignsCreateResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<CampaignsCreateResponseSuccess>(`/campaigns/${id}.json`, body);
  }

  /**
   * Campaigns: Delete
   * DELETE campaigns/{id}.{format}
   * @see DELETE /{version}/campaigns/{id}.{format}
   */
  async delete(options: CampaignsDeleteOptions): Promise<Response<CampaignsDeleteResponseSuccess>> {
    const { id } = options;
    return this.client.delete<CampaignsDeleteResponseSuccess>(`/campaigns/${id}.json`);
  }

  /**
   * Campaigns: Bounces
   * GET campaigns/{id}/bounces.{format}?date={YYYY-MM-DD HH:MM:SS}
   * @see GET /{version}/campaigns/{id}/bounces.{format}
   */
  async bounces(options: CampaignsBouncesOptions): Promise<Response<CampaignsBouncesResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsBouncesResponseSuccess>(`/campaigns/${id}/bounces.json`, { query });
  }

  /**
   * Campaigns: Clicks
   * GET campaigns/{id}/clicks.{format}?date={YYYY-MM-DD HH:MM:SS}
   * @see GET /{version}/campaigns/{id}/clicks.{format}
   */
  async clicks(options: CampaignsClicksOptions): Promise<Response<CampaignsClicksResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsClicksResponseSuccess>(`/campaigns/${id}/clicks.json`, { query });
  }

  /**
   * Campaigns: Clicksummary
   * GET campaigns/{campaignid}/clicksummary.{format}
   * @see GET /{version}/campaigns/{id}/clicksummary.{format}
   */
  async clicksummary(options: CampaignsClicksummaryOptions): Promise<Response<CampaignsClicksummaryResponseSuccess>> {
    const { id } = options;
    return this.client.get<CampaignsClicksummaryResponseSuccess>(`/campaigns/${id}/clicksummary.json`);
  }

  /**
   * Campaigns: CountrySummary
   * GET campaigns/{campaignid}/countrysummary.{format}
   * @see GET /{version}/campaigns/{id}/countrysummary.{format}
   */
  async countrysummary(options: CampaignsCountrysummaryOptions): Promise<Response<CampaignsCountrysummaryResponseSuccess>> {
    const { id } = options;
    return this.client.get<CampaignsCountrysummaryResponseSuccess>(`/campaigns/${id}/countrysummary.json`);
  }

  /**
   * Campaigns: EmailClientUsage
   * GET campaigns/{id}/emailclientusage.{format}
   * @see GET /{version}/campaigns/{id}/emailclientusage.{format}
   */
  async emailclientusage(options: CampaignsEmailclientusageOptions): Promise<Response<CampaignsEmailclientusageResponseSuccess>> {
    const { id } = options;
    return this.client.get<CampaignsEmailclientusageResponseSuccess>(`/campaigns/${id}/emailclientusage.json`);
  }

  /**
   * Campaigns: Createfromtemplate
   * POST campaigns/{id}/fromtemplate.{format}
   * @see POST /{version}/campaigns/{id}/fromtemplate.{format}
   */
  async createFromtemplate(options: CampaignsCreateFromtemplateOptions): Promise<Response<CampaignsCreateFromtemplateResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<CampaignsCreateFromtemplateResponseSuccess>(`/campaigns/${id}/fromtemplate.json`, body);
  }

  /**
   * Campaigns: ListsAndSegments
   * GET campaigns/{id}/listsandsegments.{format}
   * @see GET /{version}/campaigns/{id}/listsandsegments.{format}
   */
  async listSandsegments(options: CampaignsListSandsegmentsOptions): Promise<Response<CampaignsListSandsegmentsResponseSuccess>> {
    const { id } = options;
    return this.client.get<CampaignsListSandsegmentsResponseSuccess>(`/campaigns/${id}/listsandsegments.json`);
  }

  /**
   * Campaigns: Opens
   * GET campaigns/{id}/opens.{format}?date={YYYY-MM-DD HH:MM:SS}
   * @see GET /{version}/campaigns/{id}/opens.{format}
   */
  async opens(options: CampaignsOpensOptions): Promise<Response<CampaignsOpensResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsOpensResponseSuccess>(`/campaigns/${id}/opens.json`, { query });
  }

  /**
   * Campaigns: RecipientActivity
   * GET campaigns/{campaignid}/recipientActivity.{format}
   * @see GET /{version}/campaigns/{id}/recipientactivity.{format}
   */
  async recipientactivity(options: CampaignsRecipientactivityOptions): Promise<Response<CampaignsRecipientactivityResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsRecipientactivityResponseSuccess>(`/campaigns/${id}/recipientactivity.json`, { query });
  }

  /**
   * Campaigns: Recipients
   * GET campaigns/{id}/recipients.{format}
   * @see GET /{version}/campaigns/{id}/recipients.{format}
   */
  async recipients(options: CampaignsRecipientsOptions): Promise<Response<CampaignsRecipientsResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsRecipientsResponseSuccess>(`/campaigns/${id}/recipients.json`, { query });
  }

  /**
   * Campaigns: Send
   * @see POST /{version}/campaigns/{id}/send.{format}
   */
  async send(options: CampaignsSendOptions): Promise<Response<CampaignsSendResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<CampaignsSendResponseSuccess>(`/campaigns/${id}/send.json`, body);
  }

  /**
   * Campaigns: Sendpreview
   * POST campaigns/{id}/sendpreview.{format}
   * @see POST /{version}/campaigns/{id}/sendpreview.{format}
   */
  async sendPreview(options: CampaignsSendPreviewOptions): Promise<Response<CampaignsSendPreviewResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<CampaignsSendPreviewResponseSuccess>(`/campaigns/${id}/sendpreview.json`, body);
  }

  /**
   * Campaigns: Spam
   * GET campaigns/{id}/spam.{format}?date={YYYY-MM-DD HH:MM:SS}
   * @see GET /{version}/campaigns/{id}/spam.{format}
   */
  async spam(options: CampaignsSpamOptions): Promise<Response<CampaignsSpamResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsSpamResponseSuccess>(`/campaigns/${id}/spam.json`, { query });
  }

  /**
   * Campaigns: Summarywithname
   * GET campaigns/{id}/summary.{format} - v3.3 and up
   * @see GET /{version}/campaigns/{id}/summary.{format}
   */
  async summarywithname(options: CampaignsSummarywithnameOptions): Promise<Response<CampaignsSummarywithnameResponseSuccess>> {
    const { id } = options;
    return this.client.get<CampaignsSummarywithnameResponseSuccess>(`/campaigns/${id}/summary.json`);
  }

  /**
   * Campaigns: Timeline
   * GET campaigns/{campaignid}/timeline.{format}
   * @see GET /{version}/campaigns/{id}/timeline.{format}
   */
  async timeline(options: CampaignsTimelineOptions): Promise<Response<CampaignsTimelineResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsTimelineResponseSuccess>(`/campaigns/${id}/timeline.json`, { query });
  }

  /**
   * Campaigns: Unscheduleasync
   * POST campaigns/{id}/unschedule.{format}
   * @see POST /{version}/campaigns/{id}/unschedule.{format}
   */
  async unscheduleasync(options: CampaignsUnscheduleasyncOptions): Promise<Response<CampaignsUnscheduleasyncResponseSuccess>> {
    const { id } = options;
    return this.client.post<CampaignsUnscheduleasyncResponseSuccess>(`/campaigns/${id}/unschedule.json`, undefined);
  }

  /**
   * Campaigns: Unsubscribes
   * GET campaigns/{id}/unsubscribes.{format}?date={YYYY-MM-DD HH:MM:SS}
   * @see GET /{version}/campaigns/{id}/unsubscribes.{format}
   */
  async unsubscribes(options: CampaignsUnsubscribesOptions): Promise<Response<CampaignsUnsubscribesResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsUnsubscribesResponseSuccess>(`/campaigns/${id}/unsubscribes.json`, { query });
  }

}