// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { CampaignsCreateCampaignOptions, CampaignsCreateCampaignResponseSuccess } from './interfaces/create-campaign.js';
import type { CampaignsDeleteCampaignOptions, CampaignsDeleteCampaignResponseSuccess } from './interfaces/delete-campaign.js';
import type { CampaignsGetCampaignBouncesOptions, CampaignsGetCampaignBouncesResponseSuccess } from './interfaces/get-campaign-bounces.js';
import type { CampaignsGetCampaignClicksOptions, CampaignsGetCampaignClicksResponseSuccess } from './interfaces/get-campaign-clicks.js';
import type { CampaignsEmailClientUsageOptions, CampaignsEmailClientUsageResponseSuccess } from './interfaces/email-client-usage.js';
import type { CampaignsCreateFromTemplateOptions, CampaignsCreateFromTemplateResponseSuccess } from './interfaces/create-from-template.js';
import type { CampaignsListSAndSegmentsOptions, CampaignsListSAndSegmentsResponseSuccess } from './interfaces/list-sand-segments.js';
import type { CampaignsGetCampaignOpensOptions, CampaignsGetCampaignOpensResponseSuccess } from './interfaces/get-campaign-opens.js';
import type { CampaignsGetCampaignRecipientsOptions, CampaignsGetCampaignRecipientsResponseSuccess } from './interfaces/get-campaign-recipients.js';
import type { CampaignsSendCampaignOptions, CampaignsSendCampaignResponseSuccess } from './interfaces/send-campaign.js';
import type { CampaignsSendPreviewOptions, CampaignsSendPreviewResponseSuccess } from './interfaces/send-preview.js';
import type { CampaignsGetCampaignSpamOptions, CampaignsGetCampaignSpamResponseSuccess } from './interfaces/get-campaign-spam.js';
import type { CampaignsSummaryWithNameOptions, CampaignsSummaryWithNameResponseSuccess } from './interfaces/summary-with-name.js';
import type { CampaignsUnscheduleAsyncOptions, CampaignsUnscheduleAsyncResponseSuccess } from './interfaces/unschedule-async.js';
import type { CampaignsGetCampaignUnsubscribesOptions, CampaignsGetCampaignUnsubscribesResponseSuccess } from './interfaces/get-campaign-unsubscribes.js';

export class Campaigns {
  constructor(private readonly client: Createsend) {}

  /**
   * Campaigns: Create
   * POST campaigns/{id}.{format}
   * @see POST /{version}/campaigns/{clientId}.{format}
   */
  async createCampaign(options: CampaignsCreateCampaignOptions): Promise<Response<CampaignsCreateCampaignResponseSuccess>> {
    const { clientId, body } = options;
    return this.client.post<CampaignsCreateCampaignResponseSuccess>(`/campaigns/${clientId}.json`, body);
  }

  /**
   * Campaigns: Delete
   * DELETE campaigns/{id}.{format}
   * @see DELETE /{version}/campaigns/{clientId}.{format}
   */
  async deleteCampaign(options: CampaignsDeleteCampaignOptions): Promise<Response<CampaignsDeleteCampaignResponseSuccess>> {
    const { clientId } = options;
    return this.client.delete<CampaignsDeleteCampaignResponseSuccess>(`/campaigns/${clientId}.json`);
  }

  /**
   * Campaigns: GetCampaignBounces
   * GET campaigns/{id}/bounces.{format}?date={YYYY-MM-DD HH:MM:SS}
   * @see GET /{version}/campaigns/{id}/bounces.{format}
   */
  async getCampaignBounces(options: CampaignsGetCampaignBouncesOptions): Promise<Response<CampaignsGetCampaignBouncesResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsGetCampaignBouncesResponseSuccess>(`/campaigns/${id}/bounces.json`, { query });
  }

  /**
   * Campaigns: GetCampaignClicks
   * GET campaigns/{id}/clicks.{format}?date={YYYY-MM-DD HH:MM:SS}
   * @see GET /{version}/campaigns/{id}/clicks.{format}
   */
  async getCampaignClicks(options: CampaignsGetCampaignClicksOptions): Promise<Response<CampaignsGetCampaignClicksResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsGetCampaignClicksResponseSuccess>(`/campaigns/${id}/clicks.json`, { query });
  }

  /**
   * Campaigns: EmailClientUsage
   * GET campaigns/{id}/emailclientusage.{format}
   * @see GET /{version}/campaigns/{id}/emailclientusage.{format}
   */
  async emailClientUsage(options: CampaignsEmailClientUsageOptions): Promise<Response<CampaignsEmailClientUsageResponseSuccess>> {
    const { id } = options;
    return this.client.get<CampaignsEmailClientUsageResponseSuccess>(`/campaigns/${id}/emailclientusage.json`);
  }

  /**
   * Campaigns: CreateFromTemplate
   * POST campaigns/{id}/fromtemplate.{format}
   * @see POST /{version}/campaigns/{id}/fromtemplate.{format}
   */
  async createFromTemplate(options: CampaignsCreateFromTemplateOptions): Promise<Response<CampaignsCreateFromTemplateResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<CampaignsCreateFromTemplateResponseSuccess>(`/campaigns/${id}/fromtemplate.json`, body);
  }

  /**
   * Campaigns: ListsAndSegments
   * GET campaigns/{id}/listsandsegments.{format}
   * @see GET /{version}/campaigns/{id}/listsandsegments.{format}
   */
  async listSAndSegments(options: CampaignsListSAndSegmentsOptions): Promise<Response<CampaignsListSAndSegmentsResponseSuccess>> {
    const { id } = options;
    return this.client.get<CampaignsListSAndSegmentsResponseSuccess>(`/campaigns/${id}/listsandsegments.json`);
  }

  /**
   * Campaigns: GetCampaignOpens
   * GET campaigns/{id}/opens.{format}?date={YYYY-MM-DD HH:MM:SS}
   * @see GET /{version}/campaigns/{id}/opens.{format}
   */
  async getCampaignOpens(options: CampaignsGetCampaignOpensOptions): Promise<Response<CampaignsGetCampaignOpensResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsGetCampaignOpensResponseSuccess>(`/campaigns/${id}/opens.json`, { query });
  }

  /**
   * Campaigns: GetCampaignRecipients
   * GET campaigns/{id}/recipients.{format}
   * @see GET /{version}/campaigns/{id}/recipients.{format}
   */
  async getCampaignRecipients(options: CampaignsGetCampaignRecipientsOptions): Promise<Response<CampaignsGetCampaignRecipientsResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsGetCampaignRecipientsResponseSuccess>(`/campaigns/${id}/recipients.json`, { query });
  }

  /**
   * Campaigns: Send
   * @see POST /{version}/campaigns/{id}/send.{format}
   */
  async sendCampaign(options: CampaignsSendCampaignOptions): Promise<Response<CampaignsSendCampaignResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<CampaignsSendCampaignResponseSuccess>(`/campaigns/${id}/send.json`, body);
  }

  /**
   * Campaigns: SendPreview
   * POST campaigns/{id}/sendpreview.{format}
   * @see POST /{version}/campaigns/{id}/sendpreview.{format}
   */
  async sendPreview(options: CampaignsSendPreviewOptions): Promise<Response<CampaignsSendPreviewResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<CampaignsSendPreviewResponseSuccess>(`/campaigns/${id}/sendpreview.json`, body);
  }

  /**
   * Campaigns: GetCampaignSpam
   * GET campaigns/{id}/spam.{format}?date={YYYY-MM-DD HH:MM:SS}
   * @see GET /{version}/campaigns/{id}/spam.{format}
   */
  async getCampaignSpam(options: CampaignsGetCampaignSpamOptions): Promise<Response<CampaignsGetCampaignSpamResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsGetCampaignSpamResponseSuccess>(`/campaigns/${id}/spam.json`, { query });
  }

  /**
   * Campaigns: SummaryWithName
   * GET campaigns/{id}/summary.{format} - v3.3 and up
   * @see GET /{version}/campaigns/{id}/summary.{format}
   */
  async summaryWithName(options: CampaignsSummaryWithNameOptions): Promise<Response<CampaignsSummaryWithNameResponseSuccess>> {
    const { id } = options;
    return this.client.get<CampaignsSummaryWithNameResponseSuccess>(`/campaigns/${id}/summary.json`);
  }

  /**
   * Campaigns: UnscheduleAsync
   * POST campaigns/{id}/unschedule.{format}
   * @see POST /{version}/campaigns/{id}/unschedule.{format}
   */
  async unscheduleAsync(options: CampaignsUnscheduleAsyncOptions): Promise<Response<CampaignsUnscheduleAsyncResponseSuccess>> {
    const { id } = options;
    return this.client.post<CampaignsUnscheduleAsyncResponseSuccess>(`/campaigns/${id}/unschedule.json`, undefined);
  }

  /**
   * Campaigns: GetCampaignUnsubscribes
   * GET campaigns/{id}/unsubscribes.{format}?date={YYYY-MM-DD HH:MM:SS}
   * @see GET /{version}/campaigns/{id}/unsubscribes.{format}
   */
  async getCampaignUnsubscribes(options: CampaignsGetCampaignUnsubscribesOptions): Promise<Response<CampaignsGetCampaignUnsubscribesResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<CampaignsGetCampaignUnsubscribesResponseSuccess>(`/campaigns/${id}/unsubscribes.json`, { query });
  }

}