// DO NOT EDIT — generated by scripts/generate.ts
// Source: addSubscribersConsentToTrack

import type { SubscriberForCreation } from '../../generated/schema.js';

export interface SubscribersConsentToTrackAddSubscribersConsentToTrackOptions {
  listId: string;
  body: SubscriberForCreation;
}

export type SubscribersConsentToTrackAddSubscribersConsentToTrackResponseSuccess = string;
