// DO NOT EDIT — generated by scripts/generate.ts
// Source: subscribersconsenttotrack_add

import type { SubscriberForCreation } from '../../generated/schema.js';

export interface SubscribersConsentToTrackAddOptions {
  listid: string;
  body: SubscriberForCreation;
}

export type SubscribersConsentToTrackAddResponseSuccess = string;
