// DO NOT EDIT — generated by scripts/generate.ts
// Source: getWithListJoinedDate

import type { RESTfulApiResultOfSubscriber } from '../../generated/schema.js';

export interface SubscribersConsentToTrackGetWithListJoinedDateQuery {
  [key: string]: unknown;
  email: string;
  includeTrackingPreference?: boolean;
}

export interface SubscribersConsentToTrackGetWithListJoinedDateOptions {
  listId: string;
  query?: SubscribersConsentToTrackGetWithListJoinedDateQuery;
}

export type SubscribersConsentToTrackGetWithListJoinedDateResponseSuccess = RESTfulApiResultOfSubscriber;
