// DO NOT EDIT — generated by scripts/generate.ts
// Source: subscribersconsenttotrack_getwithlistjoineddate

import type { RESTfulApiResult_DataAPIModelsExternalSubscriber } from '../../generated/schema.js';

export interface SubscribersConsentToTrackGetWithlistjoineddateQuery {
  [key: string]: unknown;
  email: string;
  includeTrackingPreference?: boolean;
}

export interface SubscribersConsentToTrackGetWithlistjoineddateOptions {
  listid: string;
  query?: SubscribersConsentToTrackGetWithlistjoineddateQuery;
}

export type SubscribersConsentToTrackGetWithlistjoineddateResponseSuccess = RESTfulApiResult_DataAPIModelsExternalSubscriber;
