// DO NOT EDIT — generated by scripts/generate.ts
// Source: subscribersconsenttotrack_import

import type { AsyncBulkImport, SubscribersForCreation } from '../../generated/schema.js';

export interface SubscribersConsentToTrackImportQuery {
  [key: string]: unknown;
  async?: boolean;
}

export interface SubscribersConsentToTrackImportOptions {
  listid: string;
  query?: SubscribersConsentToTrackImportQuery;
  body: SubscribersForCreation;
}

export type SubscribersConsentToTrackImportResponseSuccess = AsyncBulkImport;
