// DO NOT EDIT — generated by scripts/generate.ts
// Source: importSubscribersConsentToTrack

import type { BulkImportResults, SubscribersForCreation } from '../../generated/schema.js';

export interface SubscribersConsentToTrackImportSubscribersConsentToTrackQuery {
  [key: string]: unknown;
  async?: boolean;
}

export interface SubscribersConsentToTrackImportSubscribersConsentToTrackOptions {
  listId: string;
  query?: SubscribersConsentToTrackImportSubscribersConsentToTrackQuery;
  body: SubscribersForCreation;
}

export type SubscribersConsentToTrackImportSubscribersConsentToTrackResponseSuccess = BulkImportResults;
