// DO NOT EDIT — generated by scripts/generate.ts
// Source: updateSubscribersConsentToTrack

import type { SubscriberForCreation } from '../../generated/schema.js';

export interface SubscribersConsentToTrackUpdateSubscribersConsentToTrackQuery {
  [key: string]: unknown;
  email: string;
}

export interface SubscribersConsentToTrackUpdateSubscribersConsentToTrackOptions {
  listId: string;
  query?: SubscribersConsentToTrackUpdateSubscribersConsentToTrackQuery;
  body: SubscriberForCreation;
}

export type SubscribersConsentToTrackUpdateSubscribersConsentToTrackResponseSuccess = unknown;
