// DO NOT EDIT — generated by scripts/generate.ts
// Source: subscribersconsenttotrack_update

import type { SubscriberForCreation } from '../../generated/schema.js';

export interface SubscribersConsentToTrackUpdateQuery {
  [key: string]: unknown;
  email: string;
}

export interface SubscribersConsentToTrackUpdateOptions {
  listid: string;
  query?: SubscribersConsentToTrackUpdateQuery;
  body: SubscriberForCreation;
}

export type SubscribersConsentToTrackUpdateResponseSuccess = unknown;
