// DO NOT EDIT — generated by scripts/generate.ts
// Source: util_billingdetails

import type { BillingDetails } from '../../generated/schema.js';

export type UtilBillingdetailsOptions = Record<string, never>;

export type UtilBillingdetailsResponseSuccess = BillingDetails;
