// DO NOT EDIT — generated by scripts/generate.ts
// Source: billingDetails

import type { BillingDetails } from '../../generated/schema.js';

export type UtilBillingDetailsOptions = Record<string, never>;

export type UtilBillingDetailsResponseSuccess = BillingDetails;
