// DO NOT EDIT — generated by scripts/generate.ts
// Source: util_clients

import type { IDataSetCollection } from '../../generated/schema.js';

export interface UtilClientsQuery {
  [key: string]: unknown;
  includeTimeZone?: string;
}

export interface UtilClientsOptions {
  query?: UtilClientsQuery;
}

export type UtilClientsResponseSuccess = IDataSetCollection;
