// DO NOT EDIT — generated by scripts/generate.ts
// Source: util_externalsession

import type { ExternalSessionResult, SessionOptions } from '../../generated/schema.js';

export interface UtilExternalsessionOptions {
  body: SessionOptions;
}

export type UtilExternalsessionResponseSuccess = ExternalSessionResult;
