// DO NOT EDIT — generated by scripts/generate.ts
// Source: externalSession

import type { ExternalSessionResult, SessionOptions } from '../../generated/schema.js';

export interface UtilExternalSessionOptions {
  body: SessionOptions;
}

export type UtilExternalSessionResponseSuccess = ExternalSessionResult;
