// DO NOT EDIT — generated by scripts/generate.ts
// Source: getUtilTimezones

export type UtilGetUtilTimezonesOptions = Record<string, never>;

export type UtilGetUtilTimezonesResponseSuccess = Array<string>;
