// DO NOT EDIT — generated by scripts/generate.ts
// Source: getUtilClients

import type { IDataSetCollection } from '../../generated/schema.js';

export interface UtilGetUtilClientsQuery {
  [key: string]: unknown;
  includeTimeZone?: string;
}

export interface UtilGetUtilClientsOptions {
  query?: UtilGetUtilClientsQuery;
}

export type UtilGetUtilClientsResponseSuccess = IDataSetCollection;
