// DO NOT EDIT — generated by scripts/generate.ts
// Source: getUtilCountries

export type UtilGetUtilCountriesOptions = Record<string, never>;

export type UtilGetUtilCountriesResponseSuccess = Array<string>;
