// DO NOT EDIT — generated by scripts/generate.ts
// Source: util_me

import type { BaseIdentity } from '../../generated/schema.js';

export interface UtilMeQuery {
  [key: string]: unknown;
  clientId: string;
}

export interface UtilMeOptions {
  query?: UtilMeQuery;
}

export type UtilMeResponseSuccess = BaseIdentity;
