// DO NOT EDIT — generated by scripts/generate.ts
// Source: util_processcss

import type { CSSProcessingOptions, CSSProcessingResult } from '../../generated/schema.js';

export interface UtilProcessCssOptions {
  body: CSSProcessingOptions;
}

export type UtilProcessCssResponseSuccess = CSSProcessingResult;
