// DO NOT EDIT — generated by scripts/generate.ts
// Source: util_rotateapikey

import type { ApiKeyResult } from '../../generated/schema.js';

export type UtilRotateApikeyOptions = Record<string, never>;

export type UtilRotateApikeyResponseSuccess = ApiKeyResult;
