// DO NOT EDIT — generated by scripts/generate.ts
// Source: util_timezones

import type { TimeZoneCollection } from '../../generated/schema.js';

export type UtilTimezonesOptions = Record<string, never>;

export type UtilTimezonesResponseSuccess = TimeZoneCollection;
