// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { SubscribersConsentToTrackGetWithlistjoineddateOptions, SubscribersConsentToTrackGetWithlistjoineddateResponseSuccess } from './interfaces/get-withlistjoineddate.js';
import type { SubscribersConsentToTrackAddOptions, SubscribersConsentToTrackAddResponseSuccess } from './interfaces/add.js';
import type { SubscribersConsentToTrackUpdateOptions, SubscribersConsentToTrackUpdateResponseSuccess } from './interfaces/update.js';
import type { SubscribersConsentToTrackImportOptions, SubscribersConsentToTrackImportResponseSuccess } from './interfaces/import.js';

export class SubscribersConsentToTrack {
  constructor(private readonly client: Createsend) {}

  /**
   * SubscribersConsentToTrack: GetWithListJoinedDate
   * GET v3.3 subscribers/{listid}.{format}?email={email}
   * @see GET /{version}/subscribers/{listid}.{format}
   */
  async getWithlistjoineddate(options: SubscribersConsentToTrackGetWithlistjoineddateOptions): Promise<Response<SubscribersConsentToTrackGetWithlistjoineddateResponseSuccess>> {
    const { listid, query } = options;
    return this.client.get<SubscribersConsentToTrackGetWithlistjoineddateResponseSuccess>(`/subscribers/${listid}.json`, { query });
  }

  /**
   * SubscribersConsentToTrack: Add
   * subscribers/{listid}.{format}
   * @see POST /{version}/subscribers/{listid}.{format}
   */
  async add(options: SubscribersConsentToTrackAddOptions): Promise<Response<SubscribersConsentToTrackAddResponseSuccess>> {
    const { listid, body } = options;
    return this.client.post<SubscribersConsentToTrackAddResponseSuccess>(`/subscribers/${listid}.json`, body);
  }

  /**
   * SubscribersConsentToTrack: Update
   * subscribers/{listid}.{format}?email={email}
   * @see PUT /{version}/subscribers/{listid}.{format}
   */
  async update(options: SubscribersConsentToTrackUpdateOptions): Promise<Response<SubscribersConsentToTrackUpdateResponseSuccess>> {
    const { listid, query, body } = options;
    return this.client.put<SubscribersConsentToTrackUpdateResponseSuccess>(`/subscribers/${listid}.json`, body, { query });
  }

  /**
   * SubscribersConsentToTrack: Import
   * @see POST /{version}/subscribers/{listid}/import.{format}
   */
  async import(options: SubscribersConsentToTrackImportOptions): Promise<Response<SubscribersConsentToTrackImportResponseSuccess>> {
    const { listid, query, body } = options;
    return this.client.post<SubscribersConsentToTrackImportResponseSuccess>(`/subscribers/${listid}/import.json`, body, { query });
  }

}