// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { SubscribersConsentToTrackGetWithListJoinedDateOptions, SubscribersConsentToTrackGetWithListJoinedDateResponseSuccess } from './interfaces/get-with-list-joined-date.js';
import type { SubscribersConsentToTrackAddSubscribersConsentToTrackOptions, SubscribersConsentToTrackAddSubscribersConsentToTrackResponseSuccess } from './interfaces/add-subscribers-consent-to-track.js';
import type { SubscribersConsentToTrackUpdateSubscribersConsentToTrackOptions, SubscribersConsentToTrackUpdateSubscribersConsentToTrackResponseSuccess } from './interfaces/update-subscribers-consent-to-track.js';
import type { SubscribersConsentToTrackImportSubscribersConsentToTrackOptions, SubscribersConsentToTrackImportSubscribersConsentToTrackResponseSuccess } from './interfaces/import-subscribers-consent-to-track.js';

export class SubscribersConsentToTrack {
  constructor(private readonly client: Createsend) {}

  /**
   * SubscribersConsentToTrack: GetWithListJoinedDate
   * GET v3.3 subscribers/{listid}.{format}?email={email}
   * @see GET /{version}/subscribers/{listId}.{format}
   */
  async getWithListJoinedDate(options: SubscribersConsentToTrackGetWithListJoinedDateOptions): Promise<Response<SubscribersConsentToTrackGetWithListJoinedDateResponseSuccess>> {
    const { listId, query } = options;
    return this.client.get<SubscribersConsentToTrackGetWithListJoinedDateResponseSuccess>(`/subscribers/${listId}.json`, { query });
  }

  /**
   * SubscribersConsentToTrack: Add
   * subscribers/{listid}.{format}
   * @see POST /{version}/subscribers/{listId}.{format}
   */
  async addSubscribersConsentToTrack(options: SubscribersConsentToTrackAddSubscribersConsentToTrackOptions): Promise<Response<SubscribersConsentToTrackAddSubscribersConsentToTrackResponseSuccess>> {
    const { listId, body } = options;
    return this.client.post<SubscribersConsentToTrackAddSubscribersConsentToTrackResponseSuccess>(`/subscribers/${listId}.json`, body);
  }

  /**
   * SubscribersConsentToTrack: Update
   * subscribers/{listid}.{format}?email={email}
   * @see PUT /{version}/subscribers/{listId}.{format}
   */
  async updateSubscribersConsentToTrack(options: SubscribersConsentToTrackUpdateSubscribersConsentToTrackOptions): Promise<Response<SubscribersConsentToTrackUpdateSubscribersConsentToTrackResponseSuccess>> {
    const { listId, query, body } = options;
    return this.client.put<SubscribersConsentToTrackUpdateSubscribersConsentToTrackResponseSuccess>(`/subscribers/${listId}.json`, body, { query });
  }

  /**
   * SubscribersConsentToTrack: Import
   * @see POST /{version}/subscribers/{listId}/import.{format}
   */
  async importSubscribersConsentToTrack(options: SubscribersConsentToTrackImportSubscribersConsentToTrackOptions): Promise<Response<SubscribersConsentToTrackImportSubscribersConsentToTrackResponseSuccess>> {
    const { listId, query, body } = options;
    return this.client.post<SubscribersConsentToTrackImportSubscribersConsentToTrackResponseSuccess>(`/subscribers/${listId}/import.json`, body, { query });
  }

}