// DO NOT EDIT — generated by scripts/generate.ts
// Source: getfeedback_account

import type { GetFeedbackAccountDetails } from '../../generated/schema.js';

export interface GetfeedbackAccountOptions {
  id: string;
  body: GetFeedbackAccountDetails;
}

export type GetfeedbackAccountResponseSuccess = {
  token?: string;
  clientId?: string;
};
