// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { ClientsCreateOptions, ClientsCreateResponseSuccess } from './interfaces/create.js';
import type { ClientsGetOptions, ClientsGetResponseSuccess } from './interfaces/get.js';
import type { ClientsDeleteOptions, ClientsDeleteResponseSuccess } from './interfaces/delete.js';
import type { ClientsAddBrandingtojourneyemailsOptions, ClientsAddBrandingtojourneyemailsResponseSuccess } from './interfaces/add-brandingtojourneyemails.js';
import type { ClientsPagedcampaignsOptions, ClientsPagedcampaignsResponseSuccess } from './interfaces/pagedcampaigns.js';
import type { ClientsTransfercreditsOptions, ClientsTransfercreditsResponseSuccess } from './interfaces/transfercredits.js';
import type { ClientsCustomfieldlimitOptions, ClientsCustomfieldlimitResponseSuccess } from './interfaces/customfieldlimit.js';
import type { ClientsDetailedlistsOptions, ClientsDetailedlistsResponseSuccess } from './interfaces/detailedlists.js';
import type { ClientsDetaileddraftsOptions, ClientsDetaileddraftsResponseSuccess } from './interfaces/detaileddrafts.js';
import type { ClientsPagedworkflowsOptions, ClientsPagedworkflowsResponseSuccess } from './interfaces/pagedworkflows.js';
import type { ClientsListSOptions, ClientsListSResponseSuccess } from './interfaces/list-s.js';
import type { ClientsListSforemailOptions, ClientsListSforemailResponseSuccess } from './interfaces/list-sforemail.js';
import type { ClientsDetailedscheduledOptions, ClientsDetailedscheduledResponseSuccess } from './interfaces/detailedscheduled.js';
import type { ClientsSegmentsOptions, ClientsSegmentsResponseSuccess } from './interfaces/segments.js';
import type { ClientsSendIngdomainsOptions, ClientsSendIngdomainsResponseSuccess } from './interfaces/send-ingdomains.js';
import type { ClientsAddSendingdomainOptions, ClientsAddSendingdomainResponseSuccess } from './interfaces/add-sendingdomain.js';
import type { ClientsDeleteSendingdomainOptions, ClientsDeleteSendingdomainResponseSuccess } from './interfaces/delete-sendingdomain.js';
import type { ClientsAuthenticatesendingdomainOptions, ClientsAuthenticatesendingdomainResponseSuccess } from './interfaces/authenticatesendingdomain.js';
import type { ClientsCopySendingdomainOptions, ClientsCopySendingdomainResponseSuccess } from './interfaces/copy-sendingdomain.js';
import type { ClientsSetAccessOptions, ClientsSetAccessResponseSuccess } from './interfaces/set-access.js';
import type { ClientsSetBasicsOptions, ClientsSetBasicsResponseSuccess } from './interfaces/set-basics.js';
import type { ClientsSetMonthlybillingOptions, ClientsSetMonthlybillingResponseSuccess } from './interfaces/set-monthlybilling.js';
import type { ClientsSetPaygbillingOptions, ClientsSetPaygbillingResponseSuccess } from './interfaces/set-paygbilling.js';
import type { ClientsSubscribersforemailornameOptions, ClientsSubscribersforemailornameResponseSuccess } from './interfaces/subscribersforemailorname.js';
import type { ClientsSuppressOptions, ClientsSuppressResponseSuccess } from './interfaces/suppress.js';
import type { ClientsSuppressionlistOptions, ClientsSuppressionlistResponseSuccess } from './interfaces/suppressionlist.js';
import type { ClientsTagsOptions, ClientsTagsResponseSuccess } from './interfaces/tags.js';
import type { ClientsTemplatesOptions, ClientsTemplatesResponseSuccess } from './interfaces/templates.js';
import type { ClientsTimelineOptions, ClientsTimelineResponseSuccess } from './interfaces/timeline.js';
import type { ClientsUnsuppressOptions, ClientsUnsuppressResponseSuccess } from './interfaces/unsuppress.js';

export class Clients {
  constructor(private readonly client: Createsend) {}

  /**
   * Clients: Create
   * POST clients.{format}
   * @see POST /{version}/clients.{format}
   */
  async create(options: ClientsCreateOptions): Promise<Response<ClientsCreateResponseSuccess>> {
    const { body } = options;
    return this.client.post<ClientsCreateResponseSuccess>(`/clients.json`, body);
  }

  /**
   * Clients: Get
   * GET clients/{id}.{format}
   * @see GET /{version}/clients/{id}.{format}
   */
  async get(options: ClientsGetOptions): Promise<Response<ClientsGetResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsGetResponseSuccess>(`/clients/${id}.json`);
  }

  /**
   * Clients: Delete
   * DELETE clients/{id}.{format}
   * @see DELETE /{version}/clients/{id}.{format}
   */
  async delete(options: ClientsDeleteOptions): Promise<Response<ClientsDeleteResponseSuccess>> {
    const { id } = options;
    return this.client.delete<ClientsDeleteResponseSuccess>(`/clients/${id}.json`);
  }

  /**
   * Clients: Addbrandingtojourneyemails
   * undocumented endpoint, build for COM-578 POST /clients/{clientId}/addbrandingtojourneyemails.{format}
   * @see POST /{version}/clients/{id}/addbrandingtojourneyemails.{format}
   */
  async addBrandingtojourneyemails(options: ClientsAddBrandingtojourneyemailsOptions): Promise<Response<ClientsAddBrandingtojourneyemailsResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<ClientsAddBrandingtojourneyemailsResponseSuccess>(`/clients/${id}/addbrandingtojourneyemails.json`, body);
  }

  /**
   * Clients: Pagedcampaigns
   * GET clients/{id}/campaigns.{format} V3.3
   * @see GET /{version}/clients/{id}/campaigns.{format}
   */
  async pagedcampaigns(options: ClientsPagedcampaignsOptions): Promise<Response<ClientsPagedcampaignsResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<ClientsPagedcampaignsResponseSuccess>(`/clients/${id}/campaigns.json`, { query });
  }

  /**
   * Clients: Transfercredits
   * POST clients/{id}/credits.{format}
   * @see POST /{version}/clients/{id}/credits.{format}
   */
  async transfercredits(options: ClientsTransfercreditsOptions): Promise<Response<ClientsTransfercreditsResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<ClientsTransfercreditsResponseSuccess>(`/clients/${id}/credits.json`, body);
  }

  /**
   * Clients: Customfieldlimit
   * GET clients/{id}/customfieldlimit.{format}
   * @see GET /{version}/clients/{id}/customfieldlimit.{format}
   */
  async customfieldlimit(options: ClientsCustomfieldlimitOptions): Promise<Response<ClientsCustomfieldlimitResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsCustomfieldlimitResponseSuccess>(`/clients/${id}/customfieldlimit.json`);
  }

  /**
   * Clients: Detailedlists
   * GET clients/{id}/detailedlists.{format}
   * @see GET /{version}/clients/{id}/detailedlists.{format}
   */
  async detailedlists(options: ClientsDetailedlistsOptions): Promise<Response<ClientsDetailedlistsResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsDetailedlistsResponseSuccess>(`/clients/${id}/detailedlists.json`);
  }

  /**
   * Clients: Detaileddrafts
   * GET clients/{id}/drafts.{format} v3.3
   * @see GET /{version}/clients/{id}/drafts.{format}
   */
  async detaileddrafts(options: ClientsDetaileddraftsOptions): Promise<Response<ClientsDetaileddraftsResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsDetaileddraftsResponseSuccess>(`/clients/${id}/drafts.json`);
  }

  /**
   * Clients: Pagedworkflows
   * GET clients/{id}/journeys.{format} v3.4
   * @see GET /{version}/clients/{id}/journeys.{format}
   */
  async pagedworkflows(options: ClientsPagedworkflowsOptions): Promise<Response<ClientsPagedworkflowsResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<ClientsPagedworkflowsResponseSuccess>(`/clients/${id}/journeys.json`, { query });
  }

  /**
   * Clients: Lists
   * GET clients/{id}/lists.{format}
   * @see GET /{version}/clients/{id}/lists.{format}
   */
  async listS(options: ClientsListSOptions): Promise<Response<ClientsListSResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsListSResponseSuccess>(`/clients/${id}/lists.json`);
  }

  /**
   * Clients: Listsforemail
   * GET clients/{id}/listsforemail.{format}?email={email}
   * @see GET /{version}/clients/{id}/listsforemail.{format}
   */
  async listSforemail(options: ClientsListSforemailOptions): Promise<Response<ClientsListSforemailResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<ClientsListSforemailResponseSuccess>(`/clients/${id}/listsforemail.json`, { query });
  }

  /**
   * Clients: Detailedscheduled
   * GET clients/{id}/scheduled.{format} v3.3
   * @see GET /{version}/clients/{id}/scheduled.{format}
   */
  async detailedscheduled(options: ClientsDetailedscheduledOptions): Promise<Response<ClientsDetailedscheduledResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsDetailedscheduledResponseSuccess>(`/clients/${id}/scheduled.json`);
  }

  /**
   * Clients: Segments
   * GET clients/{id}/segments.{format}
   * @see GET /{version}/clients/{id}/segments.{format}
   */
  async segments(options: ClientsSegmentsOptions): Promise<Response<ClientsSegmentsResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsSegmentsResponseSuccess>(`/clients/${id}/segments.json`);
  }

  /**
   * Clients: Sendingdomains
   * GET clients/{id}/sendingdomains.{format}?sendingDomain={sendingDomain}?selector={selector} v3.3
   * @see GET /{version}/clients/{id}/sendingdomains.{format}
   */
  async sendIngdomains(options: ClientsSendIngdomainsOptions): Promise<Response<ClientsSendIngdomainsResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<ClientsSendIngdomainsResponseSuccess>(`/clients/${id}/sendingdomains.json`, { query });
  }

  /**
   * Clients: Addsendingdomain
   * POST clients/{id}/sendingdomains.{format} v3.3
   * @see POST /{version}/clients/{id}/sendingdomains.{format}
   */
  async addSendingdomain(options: ClientsAddSendingdomainOptions): Promise<Response<ClientsAddSendingdomainResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<ClientsAddSendingdomainResponseSuccess>(`/clients/${id}/sendingdomains.json`, body);
  }

  /**
   * Clients: Deletesendingdomain
   * DELETE clients/{id}/sendingdomains.{format}?sendingDomain={sendingDomain}?selector={selector} v3.3
   * @see DELETE /{version}/clients/{id}/sendingdomains.{format}
   */
  async deleteSendingdomain(options: ClientsDeleteSendingdomainOptions): Promise<Response<ClientsDeleteSendingdomainResponseSuccess>> {
    const { id, query } = options;
    return this.client.delete<ClientsDeleteSendingdomainResponseSuccess>(`/clients/${id}/sendingdomains.json`, { query });
  }

  /**
   * Clients: Authenticatesendingdomain
   * PUT clients/{id}/sendingdomains/authenticate.{format} v3.3
   * @see PUT /{version}/clients/{id}/sendingdomains/authenticate.{format}
   */
  async authenticatesendingdomain(options: ClientsAuthenticatesendingdomainOptions): Promise<Response<ClientsAuthenticatesendingdomainResponseSuccess>> {
    const { id, query } = options;
    return this.client.put<ClientsAuthenticatesendingdomainResponseSuccess>(`/clients/${id}/sendingdomains/authenticate.json`, undefined, { query });
  }

  /**
   * Clients: Copysendingdomain
   * POST clients/{id}/sendingdomains/copy.{format} v3.3
   * @see POST /{version}/clients/{id}/sendingdomains/copy.{format}
   */
  async copySendingdomain(options: ClientsCopySendingdomainOptions): Promise<Response<ClientsCopySendingdomainResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<ClientsCopySendingdomainResponseSuccess>(`/clients/${id}/sendingdomains/copy.json`, body);
  }

  /**
   * Clients: Setaccess
   * PUT clients/{id}/setaccess.{format}
   * @see PUT /{version}/clients/{id}/setaccess.{format}
   */
  async setAccess(options: ClientsSetAccessOptions): Promise<Response<ClientsSetAccessResponseSuccess>> {
    const { id, body } = options;
    return this.client.put<ClientsSetAccessResponseSuccess>(`/clients/${id}/setaccess.json`, body);
  }

  /**
   * Clients: Setbasics
   * PUT clients/{id}/setbasics.{format}
   * @see PUT /{version}/clients/{id}/setbasics.{format}
   */
  async setBasics(options: ClientsSetBasicsOptions): Promise<Response<ClientsSetBasicsResponseSuccess>> {
    const { id, body } = options;
    return this.client.put<ClientsSetBasicsResponseSuccess>(`/clients/${id}/setbasics.json`, body);
  }

  /**
   * Clients: Setmonthlybilling
   * PUT clients/{id}/setmonthlybilling.{format}
   * @see PUT /{version}/clients/{id}/setmonthlybilling.{format}
   */
  async setMonthlybilling(options: ClientsSetMonthlybillingOptions): Promise<Response<ClientsSetMonthlybillingResponseSuccess>> {
    const { id, body } = options;
    return this.client.put<ClientsSetMonthlybillingResponseSuccess>(`/clients/${id}/setmonthlybilling.json`, body);
  }

  /**
   * Clients: Setpaygbilling
   * PUT clients/{id}/setpaygbilling.{format}
   * @see PUT /{version}/clients/{id}/setpaygbilling.{format}
   */
  async setPaygbilling(options: ClientsSetPaygbillingOptions): Promise<Response<ClientsSetPaygbillingResponseSuccess>> {
    const { id, body } = options;
    return this.client.put<ClientsSetPaygbillingResponseSuccess>(`/clients/${id}/setpaygbilling.json`, body);
  }

  /**
   * Clients: Subscribersforemailorname
   * GET clients/{id}/SubscribersForEmailOrName.{format}?query={emailOrName}
   * @see GET /{version}/clients/{id}/subscribersforemailorname.{format}
   */
  async subscribersforemailorname(options: ClientsSubscribersforemailornameOptions): Promise<Response<ClientsSubscribersforemailornameResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<ClientsSubscribersforemailornameResponseSuccess>(`/clients/${id}/subscribersforemailorname.json`, { query });
  }

  /**
   * Clients: Suppress
   * POST clients/{id}/suppress.{format}
   * @see POST /{version}/clients/{id}/suppress.{format}
   */
  async suppress(options: ClientsSuppressOptions): Promise<Response<ClientsSuppressResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<ClientsSuppressResponseSuccess>(`/clients/${id}/suppress.json`, body);
  }

  /**
   * Clients: Suppressionlist
   * GET clients/{id}/suppressionlist.{format}
   * @see GET /{version}/clients/{id}/suppressionlist.{format}
   */
  async suppressionlist(options: ClientsSuppressionlistOptions): Promise<Response<ClientsSuppressionlistResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<ClientsSuppressionlistResponseSuccess>(`/clients/${id}/suppressionlist.json`, { query });
  }

  /**
   * Clients: Tags
   * GET clients/{id}/tags.{format} v3.3
   * @see GET /{version}/clients/{id}/tags.{format}
   */
  async tags(options: ClientsTagsOptions): Promise<Response<ClientsTagsResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsTagsResponseSuccess>(`/clients/${id}/tags.json`);
  }

  /**
   * Clients: Templates
   * GET clients/{id}/templates.{format}
   * @see GET /{version}/clients/{id}/templates.{format}
   */
  async templates(options: ClientsTemplatesOptions): Promise<Response<ClientsTemplatesResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsTemplatesResponseSuccess>(`/clients/${id}/templates.json`);
  }

  /**
   * Clients: Timeline
   * GET clients/{clientid}/timeline.{format}?count={count}
   * @see GET /{version}/clients/{id}/timeline.{format}
   */
  async timeline(options: ClientsTimelineOptions): Promise<Response<ClientsTimelineResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<ClientsTimelineResponseSuccess>(`/clients/${id}/timeline.json`, { query });
  }

  /**
   * Clients: Unsuppress
   * PUT clients/{id}/unsuppress.{format}?email={email}
   * @see PUT /{version}/clients/{id}/unsuppress.{format}
   */
  async unsuppress(options: ClientsUnsuppressOptions): Promise<Response<ClientsUnsuppressResponseSuccess>> {
    const { id, query } = options;
    return this.client.put<ClientsUnsuppressResponseSuccess>(`/clients/${id}/unsuppress.json`, undefined, { query });
  }

}