// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { ClientsCreateClientOptions, ClientsCreateClientResponseSuccess } from './interfaces/create-client.js';
import type { ClientsGetClientOptions, ClientsGetClientResponseSuccess } from './interfaces/get-client.js';
import type { ClientsDeleteClientOptions, ClientsDeleteClientResponseSuccess } from './interfaces/delete-client.js';
import type { ClientsPagedCampaignsOptions, ClientsPagedCampaignsResponseSuccess } from './interfaces/paged-campaigns.js';
import type { ClientsTransferCreditsOptions, ClientsTransferCreditsResponseSuccess } from './interfaces/transfer-credits.js';
import type { ClientsDetailedDraftsOptions, ClientsDetailedDraftsResponseSuccess } from './interfaces/detailed-drafts.js';
import type { ClientsGetClientListsOptions, ClientsGetClientListsResponseSuccess } from './interfaces/get-client-lists.js';
import type { ClientsListSForEmailOptions, ClientsListSForEmailResponseSuccess } from './interfaces/list-sfor-email.js';
import type { ClientsDetailedScheduledOptions, ClientsDetailedScheduledResponseSuccess } from './interfaces/detailed-scheduled.js';
import type { ClientsGetClientSegmentsOptions, ClientsGetClientSegmentsResponseSuccess } from './interfaces/get-client-segments.js';
import type { ClientsSendIngDomainsOptions, ClientsSendIngDomainsResponseSuccess } from './interfaces/send-ing-domains.js';
import type { ClientsAddSendingDomainOptions, ClientsAddSendingDomainResponseSuccess } from './interfaces/add-sending-domain.js';
import type { ClientsDeleteSendingDomainOptions, ClientsDeleteSendingDomainResponseSuccess } from './interfaces/delete-sending-domain.js';
import type { ClientsAuthenticateSendingDomainOptions, ClientsAuthenticateSendingDomainResponseSuccess } from './interfaces/authenticate-sending-domain.js';
import type { ClientsCopySendingDomainOptions, ClientsCopySendingDomainResponseSuccess } from './interfaces/copy-sending-domain.js';
import type { ClientsSetBasicsOptions, ClientsSetBasicsResponseSuccess } from './interfaces/set-basics.js';
import type { ClientsSetMonthlyBillingOptions, ClientsSetMonthlyBillingResponseSuccess } from './interfaces/set-monthly-billing.js';
import type { ClientsSetPaygBillingOptions, ClientsSetPaygBillingResponseSuccess } from './interfaces/set-payg-billing.js';
import type { ClientsSuppressClientOptions, ClientsSuppressClientResponseSuccess } from './interfaces/suppress-client.js';
import type { ClientsSuppressionListOptions, ClientsSuppressionListResponseSuccess } from './interfaces/suppression-list.js';
import type { ClientsGetClientTagsOptions, ClientsGetClientTagsResponseSuccess } from './interfaces/get-client-tags.js';
import type { ClientsGetClientTemplatesOptions, ClientsGetClientTemplatesResponseSuccess } from './interfaces/get-client-templates.js';
import type { ClientsUnsuppressClientOptions, ClientsUnsuppressClientResponseSuccess } from './interfaces/unsuppress-client.js';

export class Clients {
  constructor(private readonly client: Createsend) {}

  /**
   * Clients: Create
   * POST clients.{format}
   * @see POST /{version}/clients.{format}
   */
  async createClient(options: ClientsCreateClientOptions): Promise<Response<ClientsCreateClientResponseSuccess>> {
    const { body } = options;
    return this.client.post<ClientsCreateClientResponseSuccess>(`/clients.json`, body);
  }

  /**
   * Clients: Get
   * GET clients/{id}.{format}
   * @see GET /{version}/clients/{id}.{format}
   */
  async getClient(options: ClientsGetClientOptions): Promise<Response<ClientsGetClientResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsGetClientResponseSuccess>(`/clients/${id}.json`);
  }

  /**
   * Clients: Delete
   * DELETE clients/{id}.{format}
   * @see DELETE /{version}/clients/{id}.{format}
   */
  async deleteClient(options: ClientsDeleteClientOptions): Promise<Response<ClientsDeleteClientResponseSuccess>> {
    const { id } = options;
    return this.client.delete<ClientsDeleteClientResponseSuccess>(`/clients/${id}.json`);
  }

  /**
   * Clients: PagedCampaigns
   * GET clients/{id}/campaigns.{format} V3.3
   * @see GET /{version}/clients/{id}/campaigns.{format}
   */
  async pagedCampaigns(options: ClientsPagedCampaignsOptions): Promise<Response<ClientsPagedCampaignsResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<ClientsPagedCampaignsResponseSuccess>(`/clients/${id}/campaigns.json`, { query });
  }

  /**
   * Clients: TransferCredits
   * POST clients/{id}/credits.{format}
   * @see POST /{version}/clients/{id}/credits.{format}
   */
  async transferCredits(options: ClientsTransferCreditsOptions): Promise<Response<ClientsTransferCreditsResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<ClientsTransferCreditsResponseSuccess>(`/clients/${id}/credits.json`, body);
  }

  /**
   * Clients: DetailedDrafts
   * GET clients/{id}/drafts.{format} v3.3
   * @see GET /{version}/clients/{id}/drafts.{format}
   */
  async detailedDrafts(options: ClientsDetailedDraftsOptions): Promise<Response<ClientsDetailedDraftsResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsDetailedDraftsResponseSuccess>(`/clients/${id}/drafts.json`);
  }

  /**
   * Clients: GetClientLists
   * GET clients/{id}/lists.{format}
   * @see GET /{version}/clients/{id}/lists.{format}
   */
  async getClientLists(options: ClientsGetClientListsOptions): Promise<Response<ClientsGetClientListsResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsGetClientListsResponseSuccess>(`/clients/${id}/lists.json`);
  }

  /**
   * Clients: ListsForEmail
   * GET clients/{id}/listsforemail.{format}?email={email}
   * @see GET /{version}/clients/{id}/listsforemail.{format}
   */
  async listSForEmail(options: ClientsListSForEmailOptions): Promise<Response<ClientsListSForEmailResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<ClientsListSForEmailResponseSuccess>(`/clients/${id}/listsforemail.json`, { query });
  }

  /**
   * Clients: DetailedScheduled
   * GET clients/{id}/scheduled.{format} v3.3
   * @see GET /{version}/clients/{id}/scheduled.{format}
   */
  async detailedScheduled(options: ClientsDetailedScheduledOptions): Promise<Response<ClientsDetailedScheduledResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsDetailedScheduledResponseSuccess>(`/clients/${id}/scheduled.json`);
  }

  /**
   * Clients: GetClientSegments
   * GET clients/{id}/segments.{format}
   * @see GET /{version}/clients/{id}/segments.{format}
   */
  async getClientSegments(options: ClientsGetClientSegmentsOptions): Promise<Response<ClientsGetClientSegmentsResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsGetClientSegmentsResponseSuccess>(`/clients/${id}/segments.json`);
  }

  /**
   * Clients: SendingDomains
   * GET clients/{id}/sendingdomains.{format}?sendingDomain={sendingDomain}?selector={selector} v3.3
   * @see GET /{version}/clients/{id}/sendingdomains.{format}
   */
  async sendIngDomains(options: ClientsSendIngDomainsOptions): Promise<Response<ClientsSendIngDomainsResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<ClientsSendIngDomainsResponseSuccess>(`/clients/${id}/sendingdomains.json`, { query });
  }

  /**
   * Clients: AddSendingDomain
   * POST clients/{id}/sendingdomains.{format} v3.3
   * @see POST /{version}/clients/{id}/sendingdomains.{format}
   */
  async addSendingDomain(options: ClientsAddSendingDomainOptions): Promise<Response<ClientsAddSendingDomainResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<ClientsAddSendingDomainResponseSuccess>(`/clients/${id}/sendingdomains.json`, body);
  }

  /**
   * Clients: DeleteSendingDomain
   * DELETE clients/{id}/sendingdomains.{format}?sendingDomain={sendingDomain}?selector={selector} v3.3
   * @see DELETE /{version}/clients/{id}/sendingdomains.{format}
   */
  async deleteSendingDomain(options: ClientsDeleteSendingDomainOptions): Promise<Response<ClientsDeleteSendingDomainResponseSuccess>> {
    const { id, query } = options;
    return this.client.delete<ClientsDeleteSendingDomainResponseSuccess>(`/clients/${id}/sendingdomains.json`, { query });
  }

  /**
   * Clients: AuthenticateSendingDomain
   * PUT clients/{id}/sendingdomains/authenticate.{format} v3.3
   * @see PUT /{version}/clients/{id}/sendingdomains/authenticate.{format}
   */
  async authenticateSendingDomain(options: ClientsAuthenticateSendingDomainOptions): Promise<Response<ClientsAuthenticateSendingDomainResponseSuccess>> {
    const { id, query } = options;
    return this.client.put<ClientsAuthenticateSendingDomainResponseSuccess>(`/clients/${id}/sendingdomains/authenticate.json`, undefined, { query });
  }

  /**
   * Clients: CopySendingDomain
   * POST clients/{id}/sendingdomains/copy.{format} v3.3
   * @see POST /{version}/clients/{id}/sendingdomains/copy.{format}
   */
  async copySendingDomain(options: ClientsCopySendingDomainOptions): Promise<Response<ClientsCopySendingDomainResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<ClientsCopySendingDomainResponseSuccess>(`/clients/${id}/sendingdomains/copy.json`, body);
  }

  /**
   * Clients: SetBasics
   * PUT clients/{id}/setbasics.{format}
   * @see PUT /{version}/clients/{id}/setbasics.{format}
   */
  async setBasics(options: ClientsSetBasicsOptions): Promise<Response<ClientsSetBasicsResponseSuccess>> {
    const { id, body } = options;
    return this.client.put<ClientsSetBasicsResponseSuccess>(`/clients/${id}/setbasics.json`, body);
  }

  /**
   * Clients: SetMonthlyBilling
   * PUT clients/{id}/setmonthlybilling.{format}
   * @see PUT /{version}/clients/{id}/setmonthlybilling.{format}
   */
  async setMonthlyBilling(options: ClientsSetMonthlyBillingOptions): Promise<Response<ClientsSetMonthlyBillingResponseSuccess>> {
    const { id, body } = options;
    return this.client.put<ClientsSetMonthlyBillingResponseSuccess>(`/clients/${id}/setmonthlybilling.json`, body);
  }

  /**
   * Clients: SetPaygBilling
   * PUT clients/{id}/setpaygbilling.{format}
   * @see PUT /{version}/clients/{id}/setpaygbilling.{format}
   */
  async setPaygBilling(options: ClientsSetPaygBillingOptions): Promise<Response<ClientsSetPaygBillingResponseSuccess>> {
    const { id, body } = options;
    return this.client.put<ClientsSetPaygBillingResponseSuccess>(`/clients/${id}/setpaygbilling.json`, body);
  }

  /**
   * Clients: Suppress
   * POST clients/{id}/suppress.{format}
   * @see POST /{version}/clients/{id}/suppress.{format}
   */
  async suppressClient(options: ClientsSuppressClientOptions): Promise<Response<ClientsSuppressClientResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<ClientsSuppressClientResponseSuccess>(`/clients/${id}/suppress.json`, body);
  }

  /**
   * Clients: SuppressionList
   * GET clients/{id}/suppressionlist.{format}
   * @see GET /{version}/clients/{id}/suppressionlist.{format}
   */
  async suppressionList(options: ClientsSuppressionListOptions): Promise<Response<ClientsSuppressionListResponseSuccess>> {
    const { id, query } = options;
    return this.client.get<ClientsSuppressionListResponseSuccess>(`/clients/${id}/suppressionlist.json`, { query });
  }

  /**
   * Clients: GetClientTags
   * GET clients/{id}/tags.{format} v3.3
   * @see GET /{version}/clients/{id}/tags.{format}
   */
  async getClientTags(options: ClientsGetClientTagsOptions): Promise<Response<ClientsGetClientTagsResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsGetClientTagsResponseSuccess>(`/clients/${id}/tags.json`);
  }

  /**
   * Clients: GetClientTemplates
   * GET clients/{id}/templates.{format}
   * @see GET /{version}/clients/{id}/templates.{format}
   */
  async getClientTemplates(options: ClientsGetClientTemplatesOptions): Promise<Response<ClientsGetClientTemplatesResponseSuccess>> {
    const { id } = options;
    return this.client.get<ClientsGetClientTemplatesResponseSuccess>(`/clients/${id}/templates.json`);
  }

  /**
   * Clients: Unsuppress
   * PUT clients/{id}/unsuppress.{format}?email={email}
   * @see PUT /{version}/clients/{id}/unsuppress.{format}
   */
  async unsuppressClient(options: ClientsUnsuppressClientOptions): Promise<Response<ClientsUnsuppressClientResponseSuccess>> {
    const { id, query } = options;
    return this.client.put<ClientsUnsuppressClientResponseSuccess>(`/clients/${id}/unsuppress.json`, undefined, { query });
  }

}