// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { QueryStatusOptions, QueryStatusResponseSuccess } from './interfaces/status.js';

export class Query {
  constructor(private readonly client: Createsend) {}

  /**
   * Query: Status
   * @see GET /{version}/transactional/{sendId}/status.{format}
   */
  async status(options: QueryStatusOptions): Promise<Response<QueryStatusResponseSuccess>> {
    const { sendId } = options;
    return this.client.get<QueryStatusResponseSuccess>(`/transactional/${sendId}/status.json`);
  }

}