// DO NOT EDIT — generated by scripts/generate.ts
// Source: basicemail_basicemail

import type { ApiBasicEmailCollectionResponse, BasicEmail } from '../../generated/schema.js';

export interface BasicEmailBasicemailOptions {
  body: BasicEmail;
}

export type BasicEmailBasicemailResponseSuccess = ApiBasicEmailCollectionResponse;
