// DO NOT EDIT — generated by scripts/generate.ts
// Source: getClassicEmailGroups

export interface BasicEmailGetClassicEmailGroupsQuery {
  [key: string]: unknown;
  clientID?: string;
}

export interface BasicEmailGetClassicEmailGroupsOptions {
  query?: BasicEmailGetClassicEmailGroupsQuery;
}

export type BasicEmailGetClassicEmailGroupsResponseSuccess = Array<{
  Group?: Record<string, unknown>;
  CreatedAt?: Record<string, unknown>;
}>;
