// DO NOT EDIT — generated by scripts/generate.ts

export type { BasicEmailGetClassicEmailGroupsOptions, BasicEmailGetClassicEmailGroupsResponseSuccess } from './get-classic-email-groups.js';
export type { BasicEmailSendClassicEmailOptions, BasicEmailSendClassicEmailResponseSuccess } from './send-classic-email.js';
