// DO NOT EDIT — generated by scripts/generate.ts
// Source: basicemail_listing

export type BasicEmailListIngOptions = Record<string, never>;

export type BasicEmailListIngResponseSuccess = Array<{
  Group?: Record<string, unknown>;
  CreatedAt?: Record<string, unknown>;
}>;
