// DO NOT EDIT — generated by scripts/generate.ts
// Source: sendClassicEmail

import type { BasicEmail, BasicEmailResponse } from '../../generated/schema.js';

export interface BasicEmailSendClassicEmailQuery {
  [key: string]: unknown;
  clientID?: string;
}

export interface BasicEmailSendClassicEmailOptions {
  query?: BasicEmailSendClassicEmailQuery;
  body: BasicEmail;
}

export type BasicEmailSendClassicEmailResponseSuccess = Array<BasicEmailResponse>;
