// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_addbrandingtojourneyemails

import type { WorkflowBrandingRequest } from '../../generated/schema.js';

export interface ClientsAddBrandingtojourneyemailsOptions {
  id: string;
  body: WorkflowBrandingRequest;
}

export type ClientsAddBrandingtojourneyemailsResponseSuccess = unknown;
