// DO NOT EDIT — generated by scripts/generate.ts
// Source: addSendingDomain

import type { SendingDomainModel, SendingDomainRequest } from '../../generated/schema.js';

export interface ClientsAddSendingDomainOptions {
  id: string;
  body: SendingDomainRequest;
}

export type ClientsAddSendingDomainResponseSuccess = SendingDomainModel;
