// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_addsendingdomain

import type { SendingDomainModel, SendingDomainRequest } from '../../generated/schema.js';

export interface ClientsAddSendingdomainOptions {
  id: string;
  body: SendingDomainRequest;
}

export type ClientsAddSendingdomainResponseSuccess = SendingDomainModel;
