// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_authenticatesendingdomain

import type { SendingDomainCollection } from '../../generated/schema.js';

export interface ClientsAuthenticatesendingdomainQuery {
  [key: string]: unknown;
  sendingDomain: string;
  selector: string;
}

export interface ClientsAuthenticatesendingdomainOptions {
  id: string;
  query?: ClientsAuthenticatesendingdomainQuery;
}

export type ClientsAuthenticatesendingdomainResponseSuccess = SendingDomainCollection;
