// DO NOT EDIT — generated by scripts/generate.ts
// Source: authenticateSendingDomain

import type { SendingDomainModel } from '../../generated/schema.js';

export interface ClientsAuthenticateSendingDomainQuery {
  [key: string]: unknown;
  sendingDomain: string;
  selector: string;
}

export interface ClientsAuthenticateSendingDomainOptions {
  id: string;
  query?: ClientsAuthenticateSendingDomainQuery;
}

export type ClientsAuthenticateSendingDomainResponseSuccess = Array<SendingDomainModel>;
