// DO NOT EDIT — generated by scripts/generate.ts
// Source: copySendingDomain

import type { SendingDomainRequest } from '../../generated/schema.js';

export interface ClientsCopySendingDomainOptions {
  id: string;
  body: SendingDomainRequest;
}

export type ClientsCopySendingDomainResponseSuccess = number;
