// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_copysendingdomain

import type { SendingDomainRequest } from '../../generated/schema.js';

export interface ClientsCopySendingdomainOptions {
  id: string;
  body: SendingDomainRequest;
}

export type ClientsCopySendingdomainResponseSuccess = number;
