// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_create

import type { ClientDetail } from '../../generated/schema.js';

export interface ClientsCreateOptions {
  body: ClientDetail;
}

export type ClientsCreateResponseSuccess = string;
