// DO NOT EDIT — generated by scripts/generate.ts
// Source: createClient

import type { ClientDetail } from '../../generated/schema.js';

export interface ClientsCreateClientOptions {
  body: ClientDetail;
}

export type ClientsCreateClientResponseSuccess = string;
