// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_customfieldlimit

export interface ClientsCustomfieldlimitOptions {
  id: string;
}

export type ClientsCustomfieldlimitResponseSuccess = number;
