// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_deletesendingdomain

export interface ClientsDeleteSendingdomainQuery {
  [key: string]: unknown;
  sendingDomain: string;
  selector: string;
}

export interface ClientsDeleteSendingdomainOptions {
  id: string;
  query?: ClientsDeleteSendingdomainQuery;
}

export type ClientsDeleteSendingdomainResponseSuccess = unknown;
