// DO NOT EDIT — generated by scripts/generate.ts
// Source: deleteSendingDomain

export interface ClientsDeleteSendingDomainQuery {
  [key: string]: unknown;
  sendingDomain: string;
  selector: string;
}

export interface ClientsDeleteSendingDomainOptions {
  id: string;
  query?: ClientsDeleteSendingDomainQuery;
}

export type ClientsDeleteSendingDomainResponseSuccess = unknown;
