// DO NOT EDIT — generated by scripts/generate.ts
// Source: detailedScheduled

import type { DetailedScheduledCampaign } from '../../generated/schema.js';

export interface ClientsDetailedScheduledOptions {
  id: string;
}

export type ClientsDetailedScheduledResponseSuccess = Array<DetailedScheduledCampaign>;
