// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_detailedscheduled

import type { DetailedScheduledCampaignCollection } from '../../generated/schema.js';

export interface ClientsDetailedscheduledOptions {
  id: string;
}

export type ClientsDetailedscheduledResponseSuccess = DetailedScheduledCampaignCollection;
