// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_detailedlists

import type { DetailedListCollection } from '../../generated/schema.js';

export interface ClientsDetailedlistsOptions {
  id: string;
}

export type ClientsDetailedlistsResponseSuccess = DetailedListCollection;
