// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_detaileddrafts

import type { DetailedDraftCampaignCollection } from '../../generated/schema.js';

export interface ClientsDetaileddraftsOptions {
  id: string;
}

export type ClientsDetaileddraftsResponseSuccess = DetailedDraftCampaignCollection;
