// DO NOT EDIT — generated by scripts/generate.ts
// Source: detailedDrafts

import type { DetailedDraftCampaign } from '../../generated/schema.js';

export interface ClientsDetailedDraftsOptions {
  id: string;
}

export type ClientsDetailedDraftsResponseSuccess = Array<DetailedDraftCampaign>;
