// DO NOT EDIT — generated by scripts/generate.ts
// Source: getClient

import type { ClientDetailForOutput } from '../../generated/schema.js';

export interface ClientsGetClientOptions {
  id: string;
}

export type ClientsGetClientResponseSuccess = ClientDetailForOutput;
