// DO NOT EDIT — generated by scripts/generate.ts
// Source: getClientSegments

import type { ListSegment } from '../../generated/schema.js';

export interface ClientsGetClientSegmentsOptions {
  id: string;
}

export type ClientsGetClientSegmentsResponseSuccess = Array<ListSegment>;
