// DO NOT EDIT — generated by scripts/generate.ts
// Source: getClientTags

import type { ClientTag } from '../../generated/schema.js';

export interface ClientsGetClientTagsOptions {
  id: string;
}

export type ClientsGetClientTagsResponseSuccess = Array<ClientTag>;
