// DO NOT EDIT — generated by scripts/generate.ts
// Source: getClientLists

import type { List } from '../../generated/schema.js';

export interface ClientsGetClientListsOptions {
  id: string;
}

export type ClientsGetClientListsResponseSuccess = Array<List>;
