// DO NOT EDIT — generated by scripts/generate.ts
// Source: getClientTemplates

import type { TemplateCollection } from '../../generated/schema.js';

export interface ClientsGetClientTemplatesOptions {
  id: string;
}

export type ClientsGetClientTemplatesResponseSuccess = TemplateCollection;
