// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_get

import type { ClientDetailForOutput } from '../../generated/schema.js';

export interface ClientsGetOptions {
  id: string;
}

export type ClientsGetResponseSuccess = ClientDetailForOutput;
