// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_listsforemail

import type { ListForEmailCollection } from '../../generated/schema.js';

export interface ClientsListSforemailQuery {
  [key: string]: unknown;
  email: string;
}

export interface ClientsListSforemailOptions {
  id: string;
  query?: ClientsListSforemailQuery;
}

export type ClientsListSforemailResponseSuccess = ListForEmailCollection;
