// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_lists

import type { IDataSetCollection } from '../../generated/schema.js';

export interface ClientsListSOptions {
  id: string;
}

export type ClientsListSResponseSuccess = IDataSetCollection;
