// DO NOT EDIT — generated by scripts/generate.ts
// Source: listsForEmail

import type { ListForEmail } from '../../generated/schema.js';

export interface ClientsListSForEmailQuery {
  [key: string]: unknown;
  email: string;
}

export interface ClientsListSForEmailOptions {
  id: string;
  query?: ClientsListSForEmailQuery;
}

export type ClientsListSForEmailResponseSuccess = Array<ListForEmail>;
