// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_pagedcampaigns

import type { PagedResult_RESTFulDetailedCampaignCollection_DetailedCampaignWithWebversion } from '../../generated/schema.js';

export interface ClientsPagedcampaignsQuery {
  [key: string]: unknown;
  includeCampaignFormat?: string;
  tags?: string;
  page?: number;
  pagesize?: number;
  orderdirection?: string;
  sentFromDate?: string;
  sentToDate?: string;
}

export interface ClientsPagedcampaignsOptions {
  id: string;
  query?: ClientsPagedcampaignsQuery;
}

export type ClientsPagedcampaignsResponseSuccess = PagedResult_RESTFulDetailedCampaignCollection_DetailedCampaignWithWebversion;
