// DO NOT EDIT — generated by scripts/generate.ts
// Source: pagedCampaigns

import type { PagedResultOfDetailedCampaignWithWebversion } from '../../generated/schema.js';

export interface ClientsPagedCampaignsQuery {
  [key: string]: unknown;
  includeCampaignFormat?: string;
  tags?: string;
  page?: number;
  pageSize?: number;
  orderDirection?: string;
  sentFromDate?: string;
  sentToDate?: string;
}

export interface ClientsPagedCampaignsOptions {
  id: string;
  query?: ClientsPagedCampaignsQuery;
}

export type ClientsPagedCampaignsResponseSuccess = PagedResultOfDetailedCampaignWithWebversion;
