// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_pagedworkflows

import type { PagedResult_BasicWorkflowCollection_BasicWorkflowModel } from '../../generated/schema.js';

export interface ClientsPagedworkflowsQuery {
  [key: string]: unknown;
  page?: number;
  pagesize?: number;
  orderdirection?: string;
}

export interface ClientsPagedworkflowsOptions {
  id: string;
  query?: ClientsPagedworkflowsQuery;
}

export type ClientsPagedworkflowsResponseSuccess = PagedResult_BasicWorkflowCollection_BasicWorkflowModel;
