// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_segments

import type { ListSegmentCollection } from '../../generated/schema.js';

export interface ClientsSegmentsOptions {
  id: string;
}

export type ClientsSegmentsResponseSuccess = ListSegmentCollection;
