// DO NOT EDIT — generated by scripts/generate.ts
// Source: sendingDomains

import type { SendingDomainModel } from '../../generated/schema.js';

export interface ClientsSendIngDomainsQuery {
  [key: string]: unknown;
  sendingDomain: string;
  selector: string;
}

export interface ClientsSendIngDomainsOptions {
  id: string;
  query?: ClientsSendIngDomainsQuery;
}

export type ClientsSendIngDomainsResponseSuccess = Array<SendingDomainModel>;
