// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_sendingdomains

import type { SendingDomainCollection } from '../../generated/schema.js';

export interface ClientsSendIngdomainsQuery {
  [key: string]: unknown;
  sendingDomain: string;
  selector: string;
}

export interface ClientsSendIngdomainsOptions {
  id: string;
  query?: ClientsSendIngdomainsQuery;
}

export type ClientsSendIngdomainsResponseSuccess = SendingDomainCollection;
