// DO NOT EDIT — generated by scripts/generate.ts
// Source: setPaygBilling

import type { BillingOptions } from '../../generated/schema.js';

export interface ClientsSetPaygBillingOptions {
  id: string;
  body: BillingOptions;
}

export type ClientsSetPaygBillingResponseSuccess = unknown;
