// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_setmonthlybilling

import type { BillingOptions } from '../../generated/schema.js';

export interface ClientsSetMonthlybillingOptions {
  id: string;
  body: BillingOptions;
}

export type ClientsSetMonthlybillingResponseSuccess = unknown;
