// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_setaccess

import type { ClientAccessSettings } from '../../generated/schema.js';

export interface ClientsSetAccessOptions {
  id: string;
  body: ClientAccessSettings;
}

export type ClientsSetAccessResponseSuccess = unknown;
