// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_setpaygbilling

import type { BillingOptions } from '../../generated/schema.js';

export interface ClientsSetPaygbillingOptions {
  id: string;
  body: BillingOptions;
}

export type ClientsSetPaygbillingResponseSuccess = unknown;
