// DO NOT EDIT — generated by scripts/generate.ts
// Source: setMonthlyBilling

import type { BillingOptions } from '../../generated/schema.js';

export interface ClientsSetMonthlyBillingOptions {
  id: string;
  body: BillingOptions;
}

export type ClientsSetMonthlyBillingResponseSuccess = unknown;
