// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_setbasics

import type { ClientDetail } from '../../generated/schema.js';

export interface ClientsSetBasicsOptions {
  id: string;
  body: ClientDetail;
}

export type ClientsSetBasicsResponseSuccess = unknown;
