// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_subscribersforemailorname

import type { SubscribersForEmailCollection } from '../../generated/schema.js';

export interface ClientsSubscribersforemailornameQuery {
  [key: string]: unknown;
  query: string;
}

export interface ClientsSubscribersforemailornameOptions {
  id: string;
  query?: ClientsSubscribersforemailornameQuery;
}

export type ClientsSubscribersforemailornameResponseSuccess = SubscribersForEmailCollection;
