// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_suppress

import type { SuppressionDetails } from '../../generated/schema.js';

export interface ClientsSuppressOptions {
  id: string;
  body: SuppressionDetails;
}

export type ClientsSuppressResponseSuccess = unknown;
