// DO NOT EDIT — generated by scripts/generate.ts
// Source: suppressClient

import type { SuppressionDetails } from '../../generated/schema.js';

export interface ClientsSuppressClientOptions {
  id: string;
  body: SuppressionDetails;
}

export type ClientsSuppressClientResponseSuccess = unknown;
