// DO NOT EDIT — generated by scripts/generate.ts
// Source: suppressionList

import type { PagedResultOfSubscriber } from '../../generated/schema.js';

export interface ClientsSuppressionListQuery {
  [key: string]: unknown;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  date?: string;
}

export interface ClientsSuppressionListOptions {
  id: string;
  query?: ClientsSuppressionListQuery;
}

export type ClientsSuppressionListResponseSuccess = PagedResultOfSubscriber;
