// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_suppressionlist

import type { PagedResult_SubscriberCollection_DataAPIModelsExternalSubscriber } from '../../generated/schema.js';

export interface ClientsSuppressionlistQuery {
  [key: string]: unknown;
  page?: number;
  pagesize?: number;
  orderfield?: string;
  orderdirection?: string;
  date?: string;
}

export interface ClientsSuppressionlistOptions {
  id: string;
  query?: ClientsSuppressionlistQuery;
}

export type ClientsSuppressionlistResponseSuccess = PagedResult_SubscriberCollection_DataAPIModelsExternalSubscriber;
