// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_tags

import type { ClientTag } from '../../generated/schema.js';

export interface ClientsTagsOptions {
  id: string;
}

export type ClientsTagsResponseSuccess = Array<ClientTag>;
