// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_templates

import type { TemplateCollection } from '../../generated/schema.js';

export interface ClientsTemplatesOptions {
  id: string;
}

export type ClientsTemplatesResponseSuccess = TemplateCollection;
