// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_timeline

import type { ClientTimeline } from '../../generated/schema.js';

export interface ClientsTimelineQuery {
  [key: string]: unknown;
  count?: number;
}

export interface ClientsTimelineOptions {
  id: string;
  query?: ClientsTimelineQuery;
}

export type ClientsTimelineResponseSuccess = ClientTimeline;
