// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_transfercredits

import type { TransferCredits, TransferCreditsResult } from '../../generated/schema.js';

export interface ClientsTransfercreditsOptions {
  id: string;
  body: TransferCredits;
}

export type ClientsTransfercreditsResponseSuccess = TransferCreditsResult;
