// DO NOT EDIT — generated by scripts/generate.ts
// Source: transferCredits

import type { TransferCredits, TransferCreditsResult } from '../../generated/schema.js';

export interface ClientsTransferCreditsOptions {
  id: string;
  body: TransferCredits;
}

export type ClientsTransferCreditsResponseSuccess = TransferCreditsResult;
