// DO NOT EDIT — generated by scripts/generate.ts
// Source: unsuppressClient

export interface ClientsUnsuppressClientQuery {
  [key: string]: unknown;
  email: string;
}

export interface ClientsUnsuppressClientOptions {
  id: string;
  query?: ClientsUnsuppressClientQuery;
}

export type ClientsUnsuppressClientResponseSuccess = unknown;
