// DO NOT EDIT — generated by scripts/generate.ts
// Source: clients_unsuppress

export interface ClientsUnsuppressQuery {
  [key: string]: unknown;
  email: string;
}

export interface ClientsUnsuppressOptions {
  id: string;
  query?: ClientsUnsuppressQuery;
}

export type ClientsUnsuppressResponseSuccess = unknown;
