// DO NOT EDIT — generated by scripts/generate.ts
// Source: anonymous_jsontorss

export interface AnonymousJsontorssQuery {
  [key: string]: unknown;
  sourceUrl: string;
  mappingId?: number;
}

export interface AnonymousJsontorssOptions {
  query?: AnonymousJsontorssQuery;
}

export type AnonymousJsontorssResponseSuccess = unknown;
