// DO NOT EDIT — generated by scripts/generate.ts
// Source: createAdmin

import type { AddAdministrator, AddAdministratorResponse } from '../../generated/schema.js';

export interface AdminsCreateAdminOptions {
  body: AddAdministrator;
}

export type AdminsCreateAdminResponseSuccess = AddAdministratorResponse;
