// DO NOT EDIT — generated by scripts/generate.ts
// Source: admins_create

import type { AddAdministrator, AddAdministratorResponse } from '../../generated/schema.js';

export interface AdminsCreateOptions {
  body: AddAdministrator;
}

export type AdminsCreateResponseSuccess = AddAdministratorResponse;
