// DO NOT EDIT — generated by scripts/generate.ts
// Source: admins_delete

export interface AdminsDeleteQuery {
  [key: string]: unknown;
  email: string;
}

export interface AdminsDeleteOptions {
  query?: AdminsDeleteQuery;
}

export type AdminsDeleteResponseSuccess = unknown;
