// DO NOT EDIT — generated by scripts/generate.ts
// Source: deleteAdmin

export interface AdminsDeleteAdminQuery {
  [key: string]: unknown;
  email: string;
}

export interface AdminsDeleteAdminOptions {
  query?: AdminsDeleteAdminQuery;
}

export type AdminsDeleteAdminResponseSuccess = unknown;
