// DO NOT EDIT — generated by scripts/generate.ts
// Source: getAdmin

import type { Administrator } from '../../generated/schema.js';

export interface AdminsGetAdminQuery {
  [key: string]: unknown;
  email: string;
}

export interface AdminsGetAdminOptions {
  query?: AdminsGetAdminQuery;
}

export type AdminsGetAdminResponseSuccess = Administrator;
