// DO NOT EDIT — generated by scripts/generate.ts
// Source: admins_getprimarycontact

import type { PrimaryContact } from '../../generated/schema.js';

export type AdminsGetPrimarycontactOptions = Record<string, never>;

export type AdminsGetPrimarycontactResponseSuccess = PrimaryContact;
