// DO NOT EDIT — generated by scripts/generate.ts
// Source: getPrimaryContact

import type { PrimaryContact } from '../../generated/schema.js';

export type AdminsGetPrimaryContactOptions = Record<string, never>;

export type AdminsGetPrimaryContactResponseSuccess = PrimaryContact;
