// DO NOT EDIT — generated by scripts/generate.ts
// Source: admins_get

import type { AdministratorCollection } from '../../generated/schema.js';

export interface AdminsGetQuery {
  [key: string]: unknown;
  email: string;
}

export interface AdminsGetOptions {
  query?: AdminsGetQuery;
}

export type AdminsGetResponseSuccess = AdministratorCollection;
