// DO NOT EDIT — generated by scripts/generate.ts

export type { AdminsGetOptions, AdminsGetResponseSuccess } from './get.js';
export type { AdminsCreateOptions, AdminsCreateResponseSuccess } from './create.js';
export type { AdminsUpdateOptions, AdminsUpdateResponseSuccess } from './update.js';
export type { AdminsDeleteOptions, AdminsDeleteResponseSuccess } from './delete.js';
export type { AdminsGetPrimarycontactOptions, AdminsGetPrimarycontactResponseSuccess } from './get-primarycontact.js';
export type { AdminsSetPrimarycontactOptions, AdminsSetPrimarycontactResponseSuccess } from './set-primarycontact.js';
