// DO NOT EDIT — generated by scripts/generate.ts
// Source: setPrimaryContact

import type { PrimaryContact } from '../../generated/schema.js';

export interface AdminsSetPrimaryContactQuery {
  [key: string]: unknown;
  email: string;
}

export interface AdminsSetPrimaryContactOptions {
  query?: AdminsSetPrimaryContactQuery;
}

export type AdminsSetPrimaryContactResponseSuccess = PrimaryContact;
