// DO NOT EDIT — generated by scripts/generate.ts
// Source: admins_setprimarycontact

import type { PrimaryContact } from '../../generated/schema.js';

export interface AdminsSetPrimarycontactQuery {
  [key: string]: unknown;
  email: string;
}

export interface AdminsSetPrimarycontactOptions {
  query?: AdminsSetPrimarycontactQuery;
}

export type AdminsSetPrimarycontactResponseSuccess = PrimaryContact;
