// DO NOT EDIT — generated by scripts/generate.ts
// Source: admins_update

import type { UpdateAdministrator, UpdateAdministratorResponse } from '../../generated/schema.js';

export interface AdminsUpdateQuery {
  [key: string]: unknown;
  email: string;
}

export interface AdminsUpdateOptions {
  query?: AdminsUpdateQuery;
  body: UpdateAdministrator;
}

export type AdminsUpdateResponseSuccess = UpdateAdministratorResponse;
