// DO NOT EDIT — generated by scripts/generate.ts
// Source: updateAdmin

import type { UpdateAdministrator, UpdateAdministratorResponse } from '../../generated/schema.js';

export interface AdminsUpdateAdminQuery {
  [key: string]: unknown;
  email: string;
}

export interface AdminsUpdateAdminOptions {
  query?: AdminsUpdateAdminQuery;
  body: UpdateAdministrator;
}

export type AdminsUpdateAdminResponseSuccess = UpdateAdministratorResponse;
