// DO NOT EDIT — generated by scripts/generate.ts
// Source: segments_clearrules

export interface SegmentsClearrulesOptions {
  segmentid: string;
}

export type SegmentsClearrulesResponseSuccess = unknown;
