// DO NOT EDIT — generated by scripts/generate.ts
// Source: deleteSegment

export interface SegmentsDeleteSegmentOptions {
  segmentId: string;
}

export type SegmentsDeleteSegmentResponseSuccess = unknown;
