// DO NOT EDIT — generated by scripts/generate.ts
// Source: segments_getsegmentsubscribers

import type { PagedResult_SubscriberCollection_Subscriber } from '../../generated/schema.js';

export interface SegmentsGetSegmentsubscribersQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  customFieldSize?: number;
  emailOrName?: string;
  includeTrackingPreference?: boolean;
}

export interface SegmentsGetSegmentsubscribersOptions {
  segmentid: string;
  query?: SegmentsGetSegmentsubscribersQuery;
}

export type SegmentsGetSegmentsubscribersResponseSuccess = PagedResult_SubscriberCollection_Subscriber;
