// DO NOT EDIT — generated by scripts/generate.ts
// Source: getSegmentSubscribersWithListJoinedDate

import type { PagedResultOfSubscriber } from '../../generated/schema.js';

export interface SegmentsGetSegmentSubscribersWithListJoinedDateQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  customFieldSize?: number;
  emailOrName?: string;
  includeTrackingPreference?: boolean;
  includeSmsPreference?: boolean;
}

export interface SegmentsGetSegmentSubscribersWithListJoinedDateOptions {
  segmentId: string;
  query?: SegmentsGetSegmentSubscribersWithListJoinedDateQuery;
}

export type SegmentsGetSegmentSubscribersWithListJoinedDateResponseSuccess = PagedResultOfSubscriber;
