// DO NOT EDIT — generated by scripts/generate.ts
// Source: segments_getsegmentsubscriberswithlistjoineddate

import type { PagedResult_SubscriberCollection_Subscriber } from '../../generated/schema.js';

export interface SegmentsGetSegmentsubscriberswithlistjoineddateQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  customFieldSize?: number;
  emailOrName?: string;
  includeTrackingPreference?: boolean;
  includeSmsPreference?: boolean;
}

export interface SegmentsGetSegmentsubscriberswithlistjoineddateOptions {
  segmentId: string;
  query?: SegmentsGetSegmentsubscriberswithlistjoineddateQuery;
}

export type SegmentsGetSegmentsubscriberswithlistjoineddateResponseSuccess = PagedResult_SubscriberCollection_Subscriber;
