// DO NOT EDIT — generated by scripts/generate.ts

export type { SegmentsNewCreateOptions, SegmentsNewCreateResponseSuccess } from './new-create.js';
export type { SegmentsGetSegmentsubscriberswithlistjoineddateOptions, SegmentsGetSegmentsubscriberswithlistjoineddateResponseSuccess } from './get-segmentsubscriberswithlistjoineddate.js';
export type { SegmentsNewGetOptions, SegmentsNewGetResponseSuccess } from './new-get.js';
export type { SegmentsNewUpdateOptions, SegmentsNewUpdateResponseSuccess } from './new-update.js';
export type { SegmentsDeleteOptions, SegmentsDeleteResponseSuccess } from './delete.js';
export type { SegmentsGetSegmentsubscribersOptions, SegmentsGetSegmentsubscribersResponseSuccess } from './get-segmentsubscribers.js';
export type { SegmentsNewAddruleOptions, SegmentsNewAddruleResponseSuccess } from './new-addrule.js';
export type { SegmentsClearrulesOptions, SegmentsClearrulesResponseSuccess } from './clearrules.js';
