// DO NOT EDIT — generated by scripts/generate.ts

export type { SegmentsNewCreateOptions, SegmentsNewCreateResponseSuccess } from './new-create.js';
export type { SegmentsNewGetOptions, SegmentsNewGetResponseSuccess } from './new-get.js';
export type { SegmentsNewUpdateOptions, SegmentsNewUpdateResponseSuccess } from './new-update.js';
export type { SegmentsDeleteSegmentOptions, SegmentsDeleteSegmentResponseSuccess } from './delete-segment.js';
export type { SegmentsGetSegmentSubscribersWithListJoinedDateOptions, SegmentsGetSegmentSubscribersWithListJoinedDateResponseSuccess } from './get-segment-subscribers-with-list-joined-date.js';
export type { SegmentsNewAddRuleOptions, SegmentsNewAddRuleResponseSuccess } from './new-add-rule.js';
export type { SegmentsClearRulesOptions, SegmentsClearRulesResponseSuccess } from './clear-rules.js';
