// DO NOT EDIT — generated by scripts/generate.ts
// Source: newUpdate

import type { NewSegmentForUpdate } from '../../generated/schema.js';

export interface SegmentsNewUpdateOptions {
  segmentId: string;
  body: NewSegmentForUpdate;
}

export type SegmentsNewUpdateResponseSuccess = unknown;
