// DO NOT EDIT — generated by scripts/generate.ts
// Source: newGet

import type { NewSegmentDetails } from '../../generated/schema.js';

export interface SegmentsNewGetOptions {
  segmentId: string;
}

export type SegmentsNewGetResponseSuccess = NewSegmentDetails;
