// DO NOT EDIT — generated by scripts/generate.ts
// Source: segments_newupdate

import type { NewSegmentForUpdate } from '../../generated/schema.js';

export interface SegmentsNewUpdateOptions {
  segmentid: string;
  body: NewSegmentForUpdate;
}

export type SegmentsNewUpdateResponseSuccess = unknown;
