// DO NOT EDIT — generated by scripts/generate.ts
// Source: segments_newcreate

import type { NewSegmentForUpdate } from '../../generated/schema.js';

export interface SegmentsNewCreateOptions {
  listid: string;
  body: NewSegmentForUpdate;
}

export type SegmentsNewCreateResponseSuccess = string;
