// DO NOT EDIT — generated by scripts/generate.ts
// Source: segments_newget

import type { NewSegmentDetails } from '../../generated/schema.js';

export interface SegmentsNewGetOptions {
  segmentid: string;
}

export type SegmentsNewGetResponseSuccess = NewSegmentDetails;
