// DO NOT EDIT — generated by scripts/generate.ts
// Source: newAddRule

import type { RuleGroup } from '../../generated/schema.js';

export interface SegmentsNewAddRuleOptions {
  segmentId: string;
  body: RuleGroup;
}

export type SegmentsNewAddRuleResponseSuccess = unknown;
