// DO NOT EDIT — generated by scripts/generate.ts
// Source: segments_newaddrule

import type { RuleGroup } from '../../generated/schema.js';

export interface SegmentsNewAddruleOptions {
  segmentid: string;
  body: RuleGroup;
}

export type SegmentsNewAddruleResponseSuccess = unknown;
