// DO NOT EDIT — generated by scripts/generate.ts
// Source: newCreate

import type { NewSegmentForUpdate } from '../../generated/schema.js';

export interface SegmentsNewCreateOptions {
  listId: string;
  body: NewSegmentForUpdate;
}

export type SegmentsNewCreateResponseSuccess = string;
