// DO NOT EDIT — generated by scripts/generate.ts
// Source: send_sendbasic

export interface SendSendBasicOptions {
  id: string;
}

export type SendSendBasicResponseSuccess = Record<string, unknown>;
