// DO NOT EDIT — generated by scripts/generate.ts
// Source: send_send

export interface SendSendOptions {
  triggeredCampaign: string;
}

export type SendSendResponseSuccess = Record<string, unknown>;
