// DO NOT EDIT — generated by scripts/generate.ts
// Source: emailClicks

import type { PagedResultOfWorkflowEmailClick } from '../../generated/schema.js';

export interface WorkflowEmailsEmailClicksQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderDirection?: string;
}

export interface WorkflowEmailsEmailClicksOptions {
  emailId: string;
  query?: WorkflowEmailsEmailClicksQuery;
}

export type WorkflowEmailsEmailClicksResponseSuccess = PagedResultOfWorkflowEmailClick;
