// DO NOT EDIT — generated by scripts/generate.ts
// Source: emailOpens

import type { PagedResultOfWorkflowEmailOpen } from '../../generated/schema.js';

export interface WorkflowEmailsEmailOpensQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderDirection?: string;
}

export interface WorkflowEmailsEmailOpensOptions {
  emailId: string;
  query?: WorkflowEmailsEmailOpensQuery;
}

export type WorkflowEmailsEmailOpensResponseSuccess = PagedResultOfWorkflowEmailOpen;
