// DO NOT EDIT — generated by scripts/generate.ts
// Source: emailRecipients

import type { PagedResultOfWorkflowEmailRecipient } from '../../generated/schema.js';

export interface WorkflowEmailsEmailRecipientsQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderDirection?: string;
}

export interface WorkflowEmailsEmailRecipientsOptions {
  emailId: string;
  query?: WorkflowEmailsEmailRecipientsQuery;
}

export type WorkflowEmailsEmailRecipientsResponseSuccess = PagedResultOfWorkflowEmailRecipient;
