// DO NOT EDIT — generated by scripts/generate.ts
// Source: emailUnsubscribes

import type { PagedResultOfWorkflowEmailUnsubscribe } from '../../generated/schema.js';

export interface WorkflowEmailsEmailUnsubscribesQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderDirection?: string;
}

export interface WorkflowEmailsEmailUnsubscribesOptions {
  emailId: string;
  query?: WorkflowEmailsEmailUnsubscribesQuery;
}

export type WorkflowEmailsEmailUnsubscribesResponseSuccess = PagedResultOfWorkflowEmailUnsubscribe;
