// DO NOT EDIT — generated by scripts/generate.ts
// Source: emailBounces

import type { PagedResultOfWorkflowEmailBounce } from '../../generated/schema.js';

export interface WorkflowEmailsEmailBouncesQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderDirection?: string;
}

export interface WorkflowEmailsEmailBouncesOptions {
  emailId: string;
  query?: WorkflowEmailsEmailBouncesQuery;
}

export type WorkflowEmailsEmailBouncesResponseSuccess = PagedResultOfWorkflowEmailBounce;
