// DO NOT EDIT — generated by scripts/generate.ts

export type { WorkflowEmailsEmailBouncesOptions, WorkflowEmailsEmailBouncesResponseSuccess } from './email-bounces.js';
export type { WorkflowEmailsEmailClicksOptions, WorkflowEmailsEmailClicksResponseSuccess } from './email-clicks.js';
export type { WorkflowEmailsEmailOpensOptions, WorkflowEmailsEmailOpensResponseSuccess } from './email-opens.js';
export type { WorkflowEmailsEmailRecipientsOptions, WorkflowEmailsEmailRecipientsResponseSuccess } from './email-recipients.js';
export type { WorkflowEmailsEmailUnsubscribesOptions, WorkflowEmailsEmailUnsubscribesResponseSuccess } from './email-unsubscribes.js';
