// DO NOT EDIT — generated by scripts/generate.ts
// Source: subscribers_delete

export interface SubscribersDeleteQuery {
  [key: string]: unknown;
  email: string;
}

export interface SubscribersDeleteOptions {
  listid: string;
  query?: SubscribersDeleteQuery;
}

export type SubscribersDeleteResponseSuccess = unknown;
