// DO NOT EDIT — generated by scripts/generate.ts
// Source: deleteSubscriber

export interface SubscribersDeleteSubscriberQuery {
  [key: string]: unknown;
  email: string;
}

export interface SubscribersDeleteSubscriberOptions {
  listId: string;
  query?: SubscribersDeleteSubscriberQuery;
}

export type SubscribersDeleteSubscriberResponseSuccess = unknown;
