// DO NOT EDIT — generated by scripts/generate.ts
// Source: getSubscriberHistory

import type { SubscriberHistoryItem } from '../../generated/schema.js';

export interface SubscribersGetSubscriberHistoryQuery {
  [key: string]: unknown;
  email: string;
  includeWebVersionUrl?: string;
}

export interface SubscribersGetSubscriberHistoryOptions {
  listId: string;
  query?: SubscribersGetSubscriberHistoryQuery;
}

export type SubscribersGetSubscriberHistoryResponseSuccess = Array<SubscriberHistoryItem>;
