// DO NOT EDIT — generated by scripts/generate.ts
// Source: subscribers_history

import type { SubscriberHistoryItemCollection } from '../../generated/schema.js';

export interface SubscribersHistoryQuery {
  [key: string]: unknown;
  email: string;
  includeWebVersionUrl?: string;
}

export interface SubscribersHistoryOptions {
  listid: string;
  query?: SubscribersHistoryQuery;
}

export type SubscribersHistoryResponseSuccess = SubscriberHistoryItemCollection;
