// DO NOT EDIT — generated by scripts/generate.ts
// Source: subscribers_importstatus

import type { AsyncBulkImportStatus } from '../../generated/schema.js';

export interface SubscribersImportStatusQuery {
  [key: string]: unknown;
  requestId?: string;
}

export interface SubscribersImportStatusOptions {
  listid: string;
  query?: SubscribersImportStatusQuery;
}

export type SubscribersImportStatusResponseSuccess = AsyncBulkImportStatus;
