// DO NOT EDIT — generated by scripts/generate.ts
// Source: subscribers_unsubscribe

import type { Subscriber } from '../../generated/schema.js';

export interface SubscribersUnsubscribeOptions {
  listid: string;
  body: Subscriber;
}

export type SubscribersUnsubscribeResponseSuccess = unknown;
