// DO NOT EDIT — generated by scripts/generate.ts
// Source: unsubscribeSubscriber

import type { Subscriber } from '../../generated/schema.js';

export interface SubscribersUnsubscribeSubscriberOptions {
  listId: string;
  body: Subscriber;
}

export type SubscribersUnsubscribeSubscriberResponseSuccess = unknown;
