// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_bounces

import type { PagedResult_ExtendedSubscriberBounceCollection_ExtendedSubscriberBounce } from '../../generated/schema.js';

export interface CampaignsBouncesQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
}

export interface CampaignsBouncesOptions {
  id: string;
  query?: CampaignsBouncesQuery;
}

export type CampaignsBouncesResponseSuccess = PagedResult_ExtendedSubscriberBounceCollection_ExtendedSubscriberBounce;
