// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_clicksummary

import type { ClickSummary } from '../../generated/schema.js';

export interface CampaignsClicksummaryOptions {
  id: string;
}

export type CampaignsClicksummaryResponseSuccess = {
  Results?: Array<ClickSummary>;
};
