// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_clicks

import type { PagedResult_IndividualSubscriberClickCollection_IndividualSubscriberClick } from '../../generated/schema.js';

export interface CampaignsClicksQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  toDate?: string;
  classification?: string;
}

export interface CampaignsClicksOptions {
  id: string;
  query?: CampaignsClicksQuery;
}

export type CampaignsClicksResponseSuccess = PagedResult_IndividualSubscriberClickCollection_IndividualSubscriberClick;
