// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_countrysummary

import type { WorldViewCountryData } from '../../generated/schema.js';

export interface CampaignsCountrysummaryOptions {
  id: string;
}

export type CampaignsCountrysummaryResponseSuccess = {
  Results?: Array<WorldViewCountryData>;
};
