// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_createfromtemplate

import type { CampaignForCreationFromTemplate } from '../../generated/schema.js';

export interface CampaignsCreateFromtemplateOptions {
  id: string;
  body: CampaignForCreationFromTemplate;
}

export type CampaignsCreateFromtemplateResponseSuccess = string;
