// DO NOT EDIT — generated by scripts/generate.ts
// Source: createFromTemplate

import type { CampaignForCreationFromTemplate } from '../../generated/schema.js';

export interface CampaignsCreateFromTemplateOptions {
  id: string;
  body: CampaignForCreationFromTemplate;
}

export type CampaignsCreateFromTemplateResponseSuccess = string;
