// DO NOT EDIT — generated by scripts/generate.ts
// Source: createCampaign

import type { CampaignForCreation } from '../../generated/schema.js';

export interface CampaignsCreateCampaignOptions {
  clientId: string;
  body: CampaignForCreation;
}

export type CampaignsCreateCampaignResponseSuccess = string;
