// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_create

import type { CampaignForCreation } from '../../generated/schema.js';

export interface CampaignsCreateOptions {
  id: string;
  body: CampaignForCreation;
}

export type CampaignsCreateResponseSuccess = string;
