// DO NOT EDIT — generated by scripts/generate.ts
// Source: deleteCampaign

export interface CampaignsDeleteCampaignOptions {
  clientId: string;
}

export type CampaignsDeleteCampaignResponseSuccess = unknown;
