// DO NOT EDIT — generated by scripts/generate.ts
// Source: emailClientUsage

import type { EmailClient } from '../../generated/schema.js';

export interface CampaignsEmailClientUsageOptions {
  id: string;
}

export type CampaignsEmailClientUsageResponseSuccess = Array<EmailClient>;
