// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_emailclientusage

import type { EmailClientCollection } from '../../generated/schema.js';

export interface CampaignsEmailclientusageOptions {
  id: string;
}

export type CampaignsEmailclientusageResponseSuccess = EmailClientCollection;
