// DO NOT EDIT — generated by scripts/generate.ts
// Source: getCampaignClicks

import type { PagedResultOfIndividualSubscriberClick } from '../../generated/schema.js';

export interface CampaignsGetCampaignClicksQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  toDate?: string;
  classification?: string;
}

export interface CampaignsGetCampaignClicksOptions {
  id: string;
  query?: CampaignsGetCampaignClicksQuery;
}

export type CampaignsGetCampaignClicksResponseSuccess = PagedResultOfIndividualSubscriberClick;
