// DO NOT EDIT — generated by scripts/generate.ts
// Source: getCampaignOpens

import type { PagedResultOfIndividualSubscriberOpen } from '../../generated/schema.js';

export interface CampaignsGetCampaignOpensQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  toDate?: string;
}

export interface CampaignsGetCampaignOpensOptions {
  id: string;
  query?: CampaignsGetCampaignOpensQuery;
}

export type CampaignsGetCampaignOpensResponseSuccess = PagedResultOfIndividualSubscriberOpen;
