// DO NOT EDIT — generated by scripts/generate.ts
// Source: getCampaignBounces

import type { PagedResultOfExtendedSubscriberBounce } from '../../generated/schema.js';

export interface CampaignsGetCampaignBouncesQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
}

export interface CampaignsGetCampaignBouncesOptions {
  id: string;
  query?: CampaignsGetCampaignBouncesQuery;
}

export type CampaignsGetCampaignBouncesResponseSuccess = PagedResultOfExtendedSubscriberBounce;
