// DO NOT EDIT — generated by scripts/generate.ts
// Source: getCampaignSpam

import type { PagedResultOfSpamComplaint } from '../../generated/schema.js';

export interface CampaignsGetCampaignSpamQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
}

export interface CampaignsGetCampaignSpamOptions {
  id: string;
  query?: CampaignsGetCampaignSpamQuery;
}

export type CampaignsGetCampaignSpamResponseSuccess = PagedResultOfSpamComplaint;
