// DO NOT EDIT — generated by scripts/generate.ts
// Source: getCampaignRecipients

import type { PagedResultOfCampaignRecipient } from '../../generated/schema.js';

export interface CampaignsGetCampaignRecipientsQuery {
  [key: string]: unknown;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
}

export interface CampaignsGetCampaignRecipientsOptions {
  id: string;
  query?: CampaignsGetCampaignRecipientsQuery;
}

export type CampaignsGetCampaignRecipientsResponseSuccess = PagedResultOfCampaignRecipient;
