// DO NOT EDIT — generated by scripts/generate.ts
// Source: getCampaignUnsubscribes

import type { PagedResultOfIndividualSubscriberUnsubscribe } from '../../generated/schema.js';

export interface CampaignsGetCampaignUnsubscribesQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
}

export interface CampaignsGetCampaignUnsubscribesOptions {
  id: string;
  query?: CampaignsGetCampaignUnsubscribesQuery;
}

export type CampaignsGetCampaignUnsubscribesResponseSuccess = PagedResultOfIndividualSubscriberUnsubscribe;
