// DO NOT EDIT — generated by scripts/generate.ts

export type { CampaignsCreateCampaignOptions, CampaignsCreateCampaignResponseSuccess } from './create-campaign.js';
export type { CampaignsDeleteCampaignOptions, CampaignsDeleteCampaignResponseSuccess } from './delete-campaign.js';
export type { CampaignsGetCampaignBouncesOptions, CampaignsGetCampaignBouncesResponseSuccess } from './get-campaign-bounces.js';
export type { CampaignsGetCampaignClicksOptions, CampaignsGetCampaignClicksResponseSuccess } from './get-campaign-clicks.js';
export type { CampaignsEmailClientUsageOptions, CampaignsEmailClientUsageResponseSuccess } from './email-client-usage.js';
export type { CampaignsCreateFromTemplateOptions, CampaignsCreateFromTemplateResponseSuccess } from './create-from-template.js';
export type { CampaignsListSAndSegmentsOptions, CampaignsListSAndSegmentsResponseSuccess } from './list-sand-segments.js';
export type { CampaignsGetCampaignOpensOptions, CampaignsGetCampaignOpensResponseSuccess } from './get-campaign-opens.js';
export type { CampaignsGetCampaignRecipientsOptions, CampaignsGetCampaignRecipientsResponseSuccess } from './get-campaign-recipients.js';
export type { CampaignsSendCampaignOptions, CampaignsSendCampaignResponseSuccess } from './send-campaign.js';
export type { CampaignsSendPreviewOptions, CampaignsSendPreviewResponseSuccess } from './send-preview.js';
export type { CampaignsGetCampaignSpamOptions, CampaignsGetCampaignSpamResponseSuccess } from './get-campaign-spam.js';
export type { CampaignsSummaryWithNameOptions, CampaignsSummaryWithNameResponseSuccess } from './summary-with-name.js';
export type { CampaignsUnscheduleAsyncOptions, CampaignsUnscheduleAsyncResponseSuccess } from './unschedule-async.js';
export type { CampaignsGetCampaignUnsubscribesOptions, CampaignsGetCampaignUnsubscribesResponseSuccess } from './get-campaign-unsubscribes.js';
