// DO NOT EDIT — generated by scripts/generate.ts
// Source: listsAndSegments

import type { CampaignListsAndSegments } from '../../generated/schema.js';

export interface CampaignsListSAndSegmentsOptions {
  id: string;
}

export type CampaignsListSAndSegmentsResponseSuccess = CampaignListsAndSegments;
