// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_listsandsegments

import type { CampaignListsAndSegments } from '../../generated/schema.js';

export interface CampaignsListSandsegmentsOptions {
  id: string;
}

export type CampaignsListSandsegmentsResponseSuccess = CampaignListsAndSegments;
