// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_opens

import type { PagedResult_IndividualSubscriberOpenCollection_IndividualSubscriberOpen } from '../../generated/schema.js';

export interface CampaignsOpensQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  toDate?: string;
}

export interface CampaignsOpensOptions {
  id: string;
  query?: CampaignsOpensQuery;
}

export type CampaignsOpensResponseSuccess = PagedResult_IndividualSubscriberOpenCollection_IndividualSubscriberOpen;
