// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_recipientactivity

import type { PagedResult_CampaignRecipientActivityCollection_CampaignRecipientActivity } from '../../generated/schema.js';

export interface CampaignsRecipientactivityQuery {
  [key: string]: unknown;
  type: string;
  page?: number;
  pagesize?: number;
  orderdirection?: string;
}

export interface CampaignsRecipientactivityOptions {
  id: string;
  query?: CampaignsRecipientactivityQuery;
}

export type CampaignsRecipientactivityResponseSuccess = PagedResult_CampaignRecipientActivityCollection_CampaignRecipientActivity;
