// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_recipients

import type { PagedResult_CampaignRecipientCollection_CampaignRecipient } from '../../generated/schema.js';

export interface CampaignsRecipientsQuery {
  [key: string]: unknown;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
}

export interface CampaignsRecipientsOptions {
  id: string;
  query?: CampaignsRecipientsQuery;
}

export type CampaignsRecipientsResponseSuccess = PagedResult_CampaignRecipientCollection_CampaignRecipient;
