// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_sendpreview

import type { CampaignPreviewInfo } from '../../generated/schema.js';

export interface CampaignsSendPreviewOptions {
  id: string;
  body: CampaignPreviewInfo;
}

export type CampaignsSendPreviewResponseSuccess = unknown;
