// DO NOT EDIT — generated by scripts/generate.ts
// Source: sendCampaign

import type { SchedulingInfo } from '../../generated/schema.js';

export interface CampaignsSendCampaignOptions {
  id: string;
  body: SchedulingInfo;
}

export type CampaignsSendCampaignResponseSuccess = unknown;
