// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_send

import type { SchedulingInfo } from '../../generated/schema.js';

export interface CampaignsSendOptions {
  id: string;
  body: SchedulingInfo;
}

export type CampaignsSendResponseSuccess = unknown;
