// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_spam

import type { PagedResult_SpamComplaintCollection_SpamComplaint } from '../../generated/schema.js';

export interface CampaignsSpamQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
}

export interface CampaignsSpamOptions {
  id: string;
  query?: CampaignsSpamQuery;
}

export type CampaignsSpamResponseSuccess = PagedResult_SpamComplaintCollection_SpamComplaint;
