// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_summarywithname

import type { CampaignSummaryWithName } from '../../generated/schema.js';

export interface CampaignsSummarywithnameOptions {
  id: string;
}

export type CampaignsSummarywithnameResponseSuccess = CampaignSummaryWithName;
