// DO NOT EDIT — generated by scripts/generate.ts
// Source: summaryWithName

import type { CampaignSummaryWithName } from '../../generated/schema.js';

export interface CampaignsSummaryWithNameOptions {
  id: string;
}

export type CampaignsSummaryWithNameResponseSuccess = CampaignSummaryWithName;
