// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_timeline

import type { CampaignTimeline } from '../../generated/schema.js';

export interface CampaignsTimelineQuery {
  [key: string]: unknown;
  count?: number;
}

export interface CampaignsTimelineOptions {
  id: string;
  query?: CampaignsTimelineQuery;
}

export type CampaignsTimelineResponseSuccess = CampaignTimeline;
