// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_unscheduleasync

export interface CampaignsUnscheduleasyncOptions {
  id: string;
}

export type CampaignsUnscheduleasyncResponseSuccess = unknown;
