// DO NOT EDIT — generated by scripts/generate.ts
// Source: unscheduleAsync

export interface CampaignsUnscheduleAsyncOptions {
  id: string;
}

export type CampaignsUnscheduleAsyncResponseSuccess = unknown;
