// DO NOT EDIT — generated by scripts/generate.ts
// Source: campaigns_unsubscribes

import type { PagedResult_IndividualSubscriberUnsubscribeCollection_IndividualSubscriberUnsubscribe } from '../../generated/schema.js';

export interface CampaignsUnsubscribesQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
}

export interface CampaignsUnsubscribesOptions {
  id: string;
  query?: CampaignsUnsubscribesQuery;
}

export type CampaignsUnsubscribesResponseSuccess = PagedResult_IndividualSubscriberUnsubscribeCollection_IndividualSubscriberUnsubscribe;
