// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { WorkflowEmailsEmailBouncesOptions, WorkflowEmailsEmailBouncesResponseSuccess } from './interfaces/email-bounces.js';
import type { WorkflowEmailsEmailClicksOptions, WorkflowEmailsEmailClicksResponseSuccess } from './interfaces/email-clicks.js';
import type { WorkflowEmailsEmailOpensOptions, WorkflowEmailsEmailOpensResponseSuccess } from './interfaces/email-opens.js';
import type { WorkflowEmailsEmailRecipientsOptions, WorkflowEmailsEmailRecipientsResponseSuccess } from './interfaces/email-recipients.js';
import type { WorkflowEmailsEmailUnsubscribesOptions, WorkflowEmailsEmailUnsubscribesResponseSuccess } from './interfaces/email-unsubscribes.js';

export class WorkflowEmails {
  constructor(private readonly client: Createsend) {}

  /**
   * WorkflowEmails: EmailBounces
   * GET /journeys/email/{emailId}/bounces.{format}
   * @see GET /{version}/journeys/email/{emailId}/bounces.{format}
   */
  async emailBounces(options: WorkflowEmailsEmailBouncesOptions): Promise<Response<WorkflowEmailsEmailBouncesResponseSuccess>> {
    const { emailId, query } = options;
    return this.client.get<WorkflowEmailsEmailBouncesResponseSuccess>(`/journeys/email/${emailId}/bounces.json`, { query });
  }

  /**
   * WorkflowEmails: EmailClicks
   * GET /journeys/email/{emailId}/clicks.{format}
   * @see GET /{version}/journeys/email/{emailId}/clicks.{format}
   */
  async emailClicks(options: WorkflowEmailsEmailClicksOptions): Promise<Response<WorkflowEmailsEmailClicksResponseSuccess>> {
    const { emailId, query } = options;
    return this.client.get<WorkflowEmailsEmailClicksResponseSuccess>(`/journeys/email/${emailId}/clicks.json`, { query });
  }

  /**
   * WorkflowEmails: EmailOpens
   * GET /journeys/email/{emailId}/opens.{format}
   * @see GET /{version}/journeys/email/{emailId}/opens.{format}
   */
  async emailOpens(options: WorkflowEmailsEmailOpensOptions): Promise<Response<WorkflowEmailsEmailOpensResponseSuccess>> {
    const { emailId, query } = options;
    return this.client.get<WorkflowEmailsEmailOpensResponseSuccess>(`/journeys/email/${emailId}/opens.json`, { query });
  }

  /**
   * WorkflowEmails: EmailRecipients
   * GET /journeys/email/{emailId}/recipients.{format}
   * @see GET /{version}/journeys/email/{emailId}/recipients.{format}
   */
  async emailRecipients(options: WorkflowEmailsEmailRecipientsOptions): Promise<Response<WorkflowEmailsEmailRecipientsResponseSuccess>> {
    const { emailId, query } = options;
    return this.client.get<WorkflowEmailsEmailRecipientsResponseSuccess>(`/journeys/email/${emailId}/recipients.json`, { query });
  }

  /**
   * WorkflowEmails: EmailUnsubscribes
   * GET /journeys/email/{emailId}/unsubscribes.{format}
   * @see GET /{version}/journeys/email/{emailId}/unsubscribes.{format}
   */
  async emailUnsubscribes(options: WorkflowEmailsEmailUnsubscribesOptions): Promise<Response<WorkflowEmailsEmailUnsubscribesResponseSuccess>> {
    const { emailId, query } = options;
    return this.client.get<WorkflowEmailsEmailUnsubscribesResponseSuccess>(`/journeys/email/${emailId}/unsubscribes.json`, { query });
  }

}