// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { SmartEmailListIngSmartEmailOptions, SmartEmailListIngSmartEmailResponseSuccess } from './interfaces/list-ing-smart-email.js';
import type { SmartEmailGetSmartEmailDetailsOptions, SmartEmailGetSmartEmailDetailsResponseSuccess } from './interfaces/get-smart-email-details.js';
import type { SmartEmailSendSmartEmailOptions, SmartEmailSendSmartEmailResponseSuccess } from './interfaces/send-smart-email.js';

export class SmartEmail {
  constructor(private readonly client: Createsend) {}

  /**
   * SmartEmail: Listing
   * @see GET /{version}/transactional/smartemail
   */
  async listIngSmartEmail(options: SmartEmailListIngSmartEmailOptions): Promise<Response<SmartEmailListIngSmartEmailResponseSuccess>> {
    const { query } = options;
    return this.client.get<SmartEmailListIngSmartEmailResponseSuccess>(`/transactional/smartemail`, { query });
  }

  /**
   * SmartEmail: GetSmartEmailDetails
   * @see GET /{version}/transactional/smartemail/{id}
   */
  async getSmartEmailDetails(options: SmartEmailGetSmartEmailDetailsOptions): Promise<Response<SmartEmailGetSmartEmailDetailsResponseSuccess>> {
    const { id } = options;
    return this.client.get<SmartEmailGetSmartEmailDetailsResponseSuccess>(`/transactional/smartemail/${id}`);
  }

  /**
   * SmartEmail: Send
   * @see POST /{version}/transactional/smartemail/{id}/send
   */
  async sendSmartEmail(options: SmartEmailSendSmartEmailOptions): Promise<Response<SmartEmailSendSmartEmailResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<SmartEmailSendSmartEmailResponseSuccess>(`/transactional/smartemail/${id}/send`, body);
  }

}