// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { SmartEmailListIngOptions, SmartEmailListIngResponseSuccess } from './interfaces/list-ing.js';
import type { SmartEmailDetailsOptions, SmartEmailDetailsResponseSuccess } from './interfaces/details.js';
import type { SmartEmailSendOptions, SmartEmailSendResponseSuccess } from './interfaces/send.js';

export class SmartEmail {
  constructor(private readonly client: Createsend) {}

  /**
   * SmartEmail: Listing
   * @see GET /{version}/transactional/smartemail.{format}
   */
  async listIng(): Promise<Response<SmartEmailListIngResponseSuccess>> {
    return this.client.get<SmartEmailListIngResponseSuccess>(`/transactional/smartemail.json`);
  }

  /**
   * SmartEmail: Details
   * @see GET /{version}/transactional/smartemail/{id}.{format}
   */
  async details(options: SmartEmailDetailsOptions): Promise<Response<SmartEmailDetailsResponseSuccess>> {
    const { id } = options;
    return this.client.get<SmartEmailDetailsResponseSuccess>(`/transactional/smartemail/${id}.json`);
  }

  /**
   * SmartEmail: Send
   * @see POST /{version}/transactional/smartemail/{id}/send.{format}
   */
  async send(options: SmartEmailSendOptions): Promise<Response<SmartEmailSendResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<SmartEmailSendResponseSuccess>(`/transactional/smartemail/${id}/send.json`, body);
  }

}