// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { AccountsCreateOptions, AccountsCreateResponseSuccess } from './interfaces/create.js';

export class Accounts {
  constructor(private readonly client: Createsend) {}

  /**
   * Accounts: Create
   * @see POST /{version}/accounts.{format}
   */
  async create(options: AccountsCreateOptions): Promise<Response<AccountsCreateResponseSuccess>> {
    const { body } = options;
    return this.client.post<AccountsCreateResponseSuccess>(`/accounts.json`, body);
  }

}