// DO NOT EDIT — generated by scripts/generate.ts
// Source: activateWebhook

export interface ListsActivateWebhookOptions {
  listId: string;
  webhookId: string;
}

export type ListsActivateWebhookResponseSuccess = unknown;
