// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_activatewebhook

export interface ListsActivatewebhookOptions {
  listid: string;
  webhookid: string;
}

export type ListsActivatewebhookResponseSuccess = unknown;
