// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_activewithlistjoineddate

import type { PagedResult_SubscriberCollection_Subscriber } from '../../generated/schema.js';

export interface ListsActivewithlistjoineddateQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pagesize?: number;
  orderfield?: string;
  orderdirection?: string;
  includeTrackingPreference?: boolean;
  includeSmsPreference?: boolean;
}

export interface ListsActivewithlistjoineddateOptions {
  listid: string;
  query?: ListsActivewithlistjoineddateQuery;
}

export type ListsActivewithlistjoineddateResponseSuccess = PagedResult_SubscriberCollection_Subscriber;
