// DO NOT EDIT — generated by scripts/generate.ts
// Source: activeWithListJoinedDate

import type { PagedResultOfSubscriber } from '../../generated/schema.js';

export interface ListsActiveWithListJoinedDateQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  includeTrackingPreference?: boolean;
  includeSmsPreference?: boolean;
}

export interface ListsActiveWithListJoinedDateOptions {
  listId: string;
  query?: ListsActiveWithListJoinedDateQuery;
}

export type ListsActiveWithListJoinedDateResponseSuccess = PagedResultOfSubscriber;
