// DO NOT EDIT — generated by scripts/generate.ts
// Source: bouncedWithListJoinedDate

import type { PagedResultOfSubscriber } from '../../generated/schema.js';

export interface ListsBouncedWithListJoinedDateQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  includeTrackingPreference?: boolean;
  includeSmsPreference?: boolean;
}

export interface ListsBouncedWithListJoinedDateOptions {
  listId: string;
  query?: ListsBouncedWithListJoinedDateQuery;
}

export type ListsBouncedWithListJoinedDateResponseSuccess = PagedResultOfSubscriber;
