// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_bouncedwithlistjoineddate

import type { PagedResult_SubscriberCollection_Subscriber } from '../../generated/schema.js';

export interface ListsBouncedwithlistjoineddateQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pagesize?: number;
  orderfield?: string;
  orderdirection?: string;
  includeTrackingPreference?: boolean;
  includeSmsPreference?: boolean;
}

export interface ListsBouncedwithlistjoineddateOptions {
  listid: string;
  query?: ListsBouncedwithlistjoineddateQuery;
}

export type ListsBouncedwithlistjoineddateResponseSuccess = PagedResult_SubscriberCollection_Subscriber;
