// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_create

import type { ListDetailWithUnsubscribeSetting } from '../../generated/schema.js';

export interface ListsCreateOptions {
  clientid: string;
  body: ListDetailWithUnsubscribeSetting;
}

export type ListsCreateResponseSuccess = string;
