// DO NOT EDIT — generated by scripts/generate.ts
// Source: createList

import type { ListDetailWithUnsubscribeSetting } from '../../generated/schema.js';

export interface ListsCreateListOptions {
  clientId: string;
  body: ListDetailWithUnsubscribeSetting;
}

export type ListsCreateListResponseSuccess = string;
