// DO NOT EDIT — generated by scripts/generate.ts
// Source: createWebhook

import type { ListWebhookForInput } from '../../generated/schema.js';

export interface ListsCreateWebhookOptions {
  listId: string;
  body: ListWebhookForInput;
}

export type ListsCreateWebhookResponseSuccess = string;
