// DO NOT EDIT — generated by scripts/generate.ts
// Source: createCustomField

import type { CustomFieldForInput } from '../../generated/schema.js';

export interface ListsCreateCustomFieldOptions {
  listId: string;
  body: CustomFieldForInput;
}

export type ListsCreateCustomFieldResponseSuccess = string;
