// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_createwebhook

import type { ListWebhookForInput } from '../../generated/schema.js';

export interface ListsCreateWebhookOptions {
  listid: string;
  body: ListWebhookForInput;
}

export type ListsCreateWebhookResponseSuccess = string;
