// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_createcustomfield

import type { CustomFieldForInput } from '../../generated/schema.js';

export interface ListsCreateCustomfieldOptions {
  listid: string;
  body: CustomFieldForInput;
}

export type ListsCreateCustomfieldResponseSuccess = string;
