// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_customfields

import type { ListInternalCustomFieldCollection } from '../../generated/schema.js';

export interface ListsCustomfieldsQuery {
  [key: string]: unknown;
  includeFieldID?: boolean;
}

export interface ListsCustomfieldsOptions {
  listid: string;
  query?: ListsCustomfieldsQuery;
}

export type ListsCustomfieldsResponseSuccess = ListInternalCustomFieldCollection;
