// DO NOT EDIT — generated by scripts/generate.ts
// Source: customFields

import type { ListInternalCustomField } from '../../generated/schema.js';

export interface ListsCustomFieldsQuery {
  [key: string]: unknown;
  includeFieldID?: boolean;
}

export interface ListsCustomFieldsOptions {
  listId: string;
  query?: ListsCustomFieldsQuery;
}

export type ListsCustomFieldsResponseSuccess = Array<ListInternalCustomField>;
