// DO NOT EDIT — generated by scripts/generate.ts
// Source: deactivateWebhook

export interface ListsDeactivateWebhookOptions {
  listId: string;
  webhookId: string;
}

export type ListsDeactivateWebhookResponseSuccess = unknown;
