// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_deactivatewebhook

export interface ListsDeactivatewebhookOptions {
  listid: string;
  webhookid: string;
}

export type ListsDeactivatewebhookResponseSuccess = unknown;
