// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_deletewebhook

export interface ListsDeleteWebhookOptions {
  listid: string;
  webhookid: string;
}

export type ListsDeleteWebhookResponseSuccess = unknown;
