// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_deletedwithlistjoineddate

import type { PagedResult_SubscriberCollection_Subscriber } from '../../generated/schema.js';

export interface ListsDeleteDwithlistjoineddateQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pagesize?: number;
  orderfield?: string;
  orderdirection?: string;
  includeTrackingPreference?: boolean;
  includeSmsPreference?: boolean;
}

export interface ListsDeleteDwithlistjoineddateOptions {
  listid: string;
  query?: ListsDeleteDwithlistjoineddateQuery;
}

export type ListsDeleteDwithlistjoineddateResponseSuccess = PagedResult_SubscriberCollection_Subscriber;
