// DO NOT EDIT — generated by scripts/generate.ts
// Source: deleteWebhook

export interface ListsDeleteWebhookOptions {
  listId: string;
  webhookId: string;
}

export type ListsDeleteWebhookResponseSuccess = unknown;
