// DO NOT EDIT — generated by scripts/generate.ts
// Source: deleteCustomField

export interface ListsDeleteCustomFieldOptions {
  listId: string;
  customFieldKey: string;
}

export type ListsDeleteCustomFieldResponseSuccess = unknown;
