// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_deletecustomfield

export interface ListsDeleteCustomfieldOptions {
  listid: string;
  customfieldkey: string;
}

export type ListsDeleteCustomfieldResponseSuccess = unknown;
