// DO NOT EDIT — generated by scripts/generate.ts
// Source: deletedWithListJoinedDate

import type { PagedResultOfSubscriber } from '../../generated/schema.js';

export interface ListsDeleteDWithListJoinedDateQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  includeTrackingPreference?: boolean;
  includeSmsPreference?: boolean;
}

export interface ListsDeleteDWithListJoinedDateOptions {
  listId: string;
  query?: ListsDeleteDWithListJoinedDateQuery;
}

export type ListsDeleteDWithListJoinedDateResponseSuccess = PagedResultOfSubscriber;
