// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_detailedstats

import type { DetailedListStatistics } from '../../generated/schema.js';

export interface ListsDetailedstatsOptions {
  listid: string;
}

export type ListsDetailedstatsResponseSuccess = DetailedListStatistics;
