// DO NOT EDIT — generated by scripts/generate.ts
// Source: getListSegments

import type { ListSegment } from '../../generated/schema.js';

export interface ListsGetListSegmentsOptions {
  listId: string;
}

export type ListsGetListSegmentsResponseSuccess = Array<ListSegment>;
