// DO NOT EDIT — generated by scripts/generate.ts
// Source: getListStats

import type { ListStatistics } from '../../generated/schema.js';

export interface ListsGetListStatsOptions {
  listId: string;
}

export type ListsGetListStatsResponseSuccess = ListStatistics;
