// DO NOT EDIT — generated by scripts/generate.ts
// Source: getList

import type { ListDetailWithUnsubscribeSetting } from '../../generated/schema.js';

export interface ListsGetListOptions {
  listId: string;
}

export type ListsGetListResponseSuccess = ListDetailWithUnsubscribeSetting;
