// DO NOT EDIT — generated by scripts/generate.ts
// Source: getListWebhooks

import type { ListWebhook } from '../../generated/schema.js';

export interface ListsGetListWebhooksOptions {
  listId: string;
}

export type ListsGetListWebhooksResponseSuccess = Array<ListWebhook>;
