// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_get

import type { ListDetailWithUnsubscribeSetting } from '../../generated/schema.js';

export interface ListsGetOptions {
  listid: string;
}

export type ListsGetResponseSuccess = ListDetailWithUnsubscribeSetting;
