// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_segments

import type { ListSegmentCollection } from '../../generated/schema.js';

export interface ListsSegmentsOptions {
  listid: string;
}

export type ListsSegmentsResponseSuccess = ListSegmentCollection;
