// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_stats

import type { ListStatistics } from '../../generated/schema.js';

export interface ListsStatsOptions {
  listid: string;
}

export type ListsStatsResponseSuccess = ListStatistics;
