// DO NOT EDIT — generated by scripts/generate.ts
// Source: testWebhook

export interface ListsTestWebhookOptions {
  listId: string;
  webhookId: string;
}

export type ListsTestWebhookResponseSuccess = unknown;
