// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_testwebhook

export interface ListsTestwebhookOptions {
  listid: string;
  webhookid: string;
}

export type ListsTestwebhookResponseSuccess = unknown;
