// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_timeline

import type { ListTimeline } from '../../generated/schema.js';

export interface ListsTimelineQuery {
  [key: string]: unknown;
  count?: number;
}

export interface ListsTimelineOptions {
  listid: string;
  query?: ListsTimelineQuery;
}

export type ListsTimelineResponseSuccess = ListTimeline;
