// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_unconfirmedwithlistjoineddate

import type { PagedResult_SubscriberCollection_Subscriber } from '../../generated/schema.js';

export interface ListsUnconfirmedwithlistjoineddateQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pagesize?: number;
  orderfield?: string;
  orderdirection?: string;
  includeTrackingPreference?: boolean;
  includeSmsPreference?: boolean;
}

export interface ListsUnconfirmedwithlistjoineddateOptions {
  listid: string;
  query?: ListsUnconfirmedwithlistjoineddateQuery;
}

export type ListsUnconfirmedwithlistjoineddateResponseSuccess = PagedResult_SubscriberCollection_Subscriber;
