// DO NOT EDIT — generated by scripts/generate.ts
// Source: unconfirmedWithListJoinedDate

import type { PagedResultOfSubscriber } from '../../generated/schema.js';

export interface ListsUnconfirmedWithListJoinedDateQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  includeTrackingPreference?: boolean;
  includeSmsPreference?: boolean;
}

export interface ListsUnconfirmedWithListJoinedDateOptions {
  listId: string;
  query?: ListsUnconfirmedWithListJoinedDateQuery;
}

export type ListsUnconfirmedWithListJoinedDateResponseSuccess = PagedResultOfSubscriber;
