// DO NOT EDIT — generated by scripts/generate.ts
// Source: unsubscribedWithListJoinedDate

import type { PagedResultOfSubscriber } from '../../generated/schema.js';

export interface ListsUnsubscribedWithListJoinedDateQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderField?: string;
  orderDirection?: string;
  includeTrackingPreference?: boolean;
  includeSmsPreference?: boolean;
}

export interface ListsUnsubscribedWithListJoinedDateOptions {
  listId: string;
  query?: ListsUnsubscribedWithListJoinedDateQuery;
}

export type ListsUnsubscribedWithListJoinedDateResponseSuccess = PagedResultOfSubscriber;
