// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_unsubscribedwithlistjoineddate

import type { PagedResult_SubscriberCollection_Subscriber } from '../../generated/schema.js';

export interface ListsUnsubscribedwithlistjoineddateQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pagesize?: number;
  orderfield?: string;
  orderdirection?: string;
  includeTrackingPreference?: boolean;
  includeSmsPreference?: boolean;
}

export interface ListsUnsubscribedwithlistjoineddateOptions {
  listid: string;
  query?: ListsUnsubscribedwithlistjoineddateQuery;
}

export type ListsUnsubscribedwithlistjoineddateResponseSuccess = PagedResult_SubscriberCollection_Subscriber;
