// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_updatefieldoptions

import type { FieldOptions } from '../../generated/schema.js';

export interface ListsUpdateFieldoptionsOptions {
  listid: string;
  customfieldkey: string;
  body: FieldOptions;
}

export type ListsUpdateFieldoptionsResponseSuccess = unknown;
