// DO NOT EDIT — generated by scripts/generate.ts
// Source: updateList

import type { ListDetailWithUnsubscribeSettingForUpdate } from '../../generated/schema.js';

export interface ListsUpdateListOptions {
  listId: string;
  body: ListDetailWithUnsubscribeSettingForUpdate;
}

export type ListsUpdateListResponseSuccess = unknown;
