// DO NOT EDIT — generated by scripts/generate.ts
// Source: updateCustomField

import type { CustomFieldForUpdate } from '../../generated/schema.js';

export interface ListsUpdateCustomFieldOptions {
  listId: string;
  customFieldKey: string;
  body: CustomFieldForUpdate;
}

export type ListsUpdateCustomFieldResponseSuccess = string;
