// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_update

import type { ListDetailWithUnsubscribeSettingForUpdate } from '../../generated/schema.js';

export interface ListsUpdateOptions {
  listid: string;
  body: ListDetailWithUnsubscribeSettingForUpdate;
}

export type ListsUpdateResponseSuccess = unknown;
