// DO NOT EDIT — generated by scripts/generate.ts
// Source: updateFieldOptions

import type { FieldOptions } from '../../generated/schema.js';

export interface ListsUpdateFieldOptionsOptions {
  listId: string;
  customFieldKey: string;
  body: FieldOptions;
}

export type ListsUpdateFieldOptionsResponseSuccess = unknown;
