// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_updatecustomfield

import type { CustomFieldForUpdate } from '../../generated/schema.js';

export interface ListsUpdateCustomfieldOptions {
  listid: string;
  customfieldkey: string;
  body: CustomFieldForUpdate;
}

export type ListsUpdateCustomfieldResponseSuccess = string;
