// DO NOT EDIT — generated by scripts/generate.ts
// Source: lists_webhooks

import type { ListWebhookCollection } from '../../generated/schema.js';

export interface ListsWebhooksOptions {
  listid: string;
}

export type ListsWebhooksResponseSuccess = ListWebhookCollection;
