// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { BasicEmailListIngOptions, BasicEmailListIngResponseSuccess } from './interfaces/list-ing.js';
import type { BasicEmailBasicemailOptions, BasicEmailBasicemailResponseSuccess } from './interfaces/basicemail.js';

export class BasicEmail {
  constructor(private readonly client: Createsend) {}

  /**
   * BasicEmail: Listing
   * @see GET /{version}/transactional/basicemail/groups.{format}
   */
  async listIng(): Promise<Response<BasicEmailListIngResponseSuccess>> {
    return this.client.get<BasicEmailListIngResponseSuccess>(`/transactional/basicemail/groups.json`);
  }

  /**
   * BasicEmail: BasicEmail
   * @see POST /{version}/transactional/basicemail/send.{format}
   */
  async basicemail(options: BasicEmailBasicemailOptions): Promise<Response<BasicEmailBasicemailResponseSuccess>> {
    const { body } = options;
    return this.client.post<BasicEmailBasicemailResponseSuccess>(`/transactional/basicemail/send.json`, body);
  }

}