// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { BasicEmailGetClassicEmailGroupsOptions, BasicEmailGetClassicEmailGroupsResponseSuccess } from './interfaces/get-classic-email-groups.js';
import type { BasicEmailSendClassicEmailOptions, BasicEmailSendClassicEmailResponseSuccess } from './interfaces/send-classic-email.js';

export class BasicEmail {
  constructor(private readonly client: Createsend) {}

  /**
   * BasicEmail: GetClassicEmailGroups
   * @see GET /{version}/transactional/classicemail/groups
   */
  async getClassicEmailGroups(options: BasicEmailGetClassicEmailGroupsOptions): Promise<Response<BasicEmailGetClassicEmailGroupsResponseSuccess>> {
    const { query } = options;
    return this.client.get<BasicEmailGetClassicEmailGroupsResponseSuccess>(`/transactional/classicemail/groups`, { query });
  }

  /**
   * BasicEmail: SendClassicEmail
   * @see POST /{version}/transactional/classicemail/send
   */
  async sendClassicEmail(options: BasicEmailSendClassicEmailOptions): Promise<Response<BasicEmailSendClassicEmailResponseSuccess>> {
    const { query, body } = options;
    return this.client.post<BasicEmailSendClassicEmailResponseSuccess>(`/transactional/classicemail/send`, body, { query });
  }

}