// DO NOT EDIT — generated by scripts/generate.ts
// Source: getMessageTimeline

export interface MessageGetMessageTimelineQuery {
  [key: string]: unknown;
  clientID?: string;
}

export interface MessageGetMessageTimelineOptions {
  query?: MessageGetMessageTimelineQuery;
}

export type MessageGetMessageTimelineResponseSuccess = Array<Record<string, unknown>>;
