// DO NOT EDIT — generated by scripts/generate.ts
// Source: message_messagedetails

export interface MessageMessagedetailsOptions {
  messageId: string;
}

export type MessageMessagedetailsResponseSuccess = Record<string, unknown>;
