// DO NOT EDIT — generated by scripts/generate.ts
// Source: messageDetails

import type { MessageMessageDetailsResponse } from '../../generated/schema.js';

export interface MessageMessageDetailsOptions {
  messageId: string;
}

export type MessageMessageDetailsResponseSuccess = MessageMessageDetailsResponse;
