// DO NOT EDIT — generated by scripts/generate.ts
// Source: resendMessage

import type { BasicEmailResponse, Resend } from '../../generated/schema.js';

export interface MessageResendMessageOptions {
  messageId: string;
  body: Resend;
}

export type MessageResendMessageResponseSuccess = BasicEmailResponse;
