// DO NOT EDIT — generated by scripts/generate.ts
// Source: message_resend

import type { BasicEmailResponse, Resend } from '../../generated/schema.js';

export interface MessageResendOptions {
  messageId: string;
  body: Resend;
}

export type MessageResendResponseSuccess = BasicEmailResponse;
