// DO NOT EDIT — generated by scripts/generate.ts
// Source: message_timeline

import type { ApiTimelineEventCollectionResponse } from '../../generated/schema.js';

export type MessageTimelineOptions = Record<string, never>;

export type MessageTimelineResponseSuccess = ApiTimelineEventCollectionResponse;
