// DO NOT EDIT — generated by scripts/generate.ts
// Source: indexStatistic

import type { StatisticsIndexResponse } from '../../generated/schema.js';

export interface StatisticsIndexStatisticQuery {
  [key: string]: unknown;
  clientID?: string;
}

export interface StatisticsIndexStatisticOptions {
  query?: StatisticsIndexStatisticQuery;
}

export type StatisticsIndexStatisticResponseSuccess = StatisticsIndexResponse;
