// DO NOT EDIT — generated by scripts/generate.ts
// Source: statistics_index

export type StatisticsIndexOptions = Record<string, never>;

export type StatisticsIndexResponseSuccess = {
  Query?: {
  SmartEmailID?: string;
  Group?: string;
  From?: string;
  To?: string;
  TimeZone?: Record<string, unknown>;
};
  Sent?: number;
  Bounces?: number;
  Delivered?: number;
  Opened?: number;
  Clicked?: number;
};
