// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { ListsCreateListOptions, ListsCreateListResponseSuccess } from './interfaces/create-list.js';
import type { ListsGetListOptions, ListsGetListResponseSuccess } from './interfaces/get-list.js';
import type { ListsUpdateListOptions, ListsUpdateListResponseSuccess } from './interfaces/update-list.js';
import type { ListsDeleteListOptions, ListsDeleteListResponseSuccess } from './interfaces/delete-list.js';
import type { ListsActiveWithListJoinedDateOptions, ListsActiveWithListJoinedDateResponseSuccess } from './interfaces/active-with-list-joined-date.js';
import type { ListsBouncedWithListJoinedDateOptions, ListsBouncedWithListJoinedDateResponseSuccess } from './interfaces/bounced-with-list-joined-date.js';
import type { ListsCustomFieldsOptions, ListsCustomFieldsResponseSuccess } from './interfaces/custom-fields.js';
import type { ListsCreateCustomFieldOptions, ListsCreateCustomFieldResponseSuccess } from './interfaces/create-custom-field.js';
import type { ListsUpdateCustomFieldOptions, ListsUpdateCustomFieldResponseSuccess } from './interfaces/update-custom-field.js';
import type { ListsDeleteCustomFieldOptions, ListsDeleteCustomFieldResponseSuccess } from './interfaces/delete-custom-field.js';
import type { ListsUpdateFieldOptionsOptions, ListsUpdateFieldOptionsResponseSuccess } from './interfaces/update-field-options.js';
import type { ListsDeleteDWithListJoinedDateOptions, ListsDeleteDWithListJoinedDateResponseSuccess } from './interfaces/delete-dwith-list-joined-date.js';
import type { ListsGetListSegmentsOptions, ListsGetListSegmentsResponseSuccess } from './interfaces/get-list-segments.js';
import type { ListsGetListStatsOptions, ListsGetListStatsResponseSuccess } from './interfaces/get-list-stats.js';
import type { ListsUnconfirmedWithListJoinedDateOptions, ListsUnconfirmedWithListJoinedDateResponseSuccess } from './interfaces/unconfirmed-with-list-joined-date.js';
import type { ListsUnsubscribedWithListJoinedDateOptions, ListsUnsubscribedWithListJoinedDateResponseSuccess } from './interfaces/unsubscribed-with-list-joined-date.js';
import type { ListsGetListWebhooksOptions, ListsGetListWebhooksResponseSuccess } from './interfaces/get-list-webhooks.js';
import type { ListsCreateWebhookOptions, ListsCreateWebhookResponseSuccess } from './interfaces/create-webhook.js';
import type { ListsDeleteWebhookOptions, ListsDeleteWebhookResponseSuccess } from './interfaces/delete-webhook.js';
import type { ListsActivateWebhookOptions, ListsActivateWebhookResponseSuccess } from './interfaces/activate-webhook.js';
import type { ListsDeactivateWebhookOptions, ListsDeactivateWebhookResponseSuccess } from './interfaces/deactivate-webhook.js';
import type { ListsTestWebhookOptions, ListsTestWebhookResponseSuccess } from './interfaces/test-webhook.js';

export class Lists {
  constructor(private readonly client: Createsend) {}

  /**
   * Lists: Create
   * POST lists/{clientid}.{format}
   * @see POST /{version}/lists/{clientId}.{format}
   */
  async createList(options: ListsCreateListOptions): Promise<Response<ListsCreateListResponseSuccess>> {
    const { clientId, body } = options;
    return this.client.post<ListsCreateListResponseSuccess>(`/lists/${clientId}.json`, body);
  }

  /**
   * Lists: Get
   * GET lists/{listid}.{format}
   * @see GET /{version}/lists/{listId}.{format}
   */
  async getList(options: ListsGetListOptions): Promise<Response<ListsGetListResponseSuccess>> {
    const { listId } = options;
    return this.client.get<ListsGetListResponseSuccess>(`/lists/${listId}.json`);
  }

  /**
   * Lists: Update
   * PUT lists/{listid}.{format}
   * @see PUT /{version}/lists/{listId}.{format}
   */
  async updateList(options: ListsUpdateListOptions): Promise<Response<ListsUpdateListResponseSuccess>> {
    const { listId, body } = options;
    return this.client.put<ListsUpdateListResponseSuccess>(`/lists/${listId}.json`, body);
  }

  /**
   * Lists: Delete
   * DELETE lists/{listid}.{format}
   * @see DELETE /{version}/lists/{listId}.{format}
   */
  async deleteList(options: ListsDeleteListOptions): Promise<Response<ListsDeleteListResponseSuccess>> {
    const { listId } = options;
    return this.client.delete<ListsDeleteListResponseSuccess>(`/lists/${listId}.json`);
  }

  /**
   * Lists: ActiveWithListJoinedDate
   * GET lists/{listid}/active.{format}?date={YYYY-MM-DD HH:MM:SS} (v3.3 and up)
   * @see GET /{version}/lists/{listId}/active.{format}
   */
  async activeWithListJoinedDate(options: ListsActiveWithListJoinedDateOptions): Promise<Response<ListsActiveWithListJoinedDateResponseSuccess>> {
    const { listId, query } = options;
    return this.client.get<ListsActiveWithListJoinedDateResponseSuccess>(`/lists/${listId}/active.json`, { query });
  }

  /**
   * Lists: BouncedWithListJoinedDate
   * GET lists/{listid}/bounced.{format}?date={YYYY-MM-DD HH:MM:SS} (v3.3 and up)
   * @see GET /{version}/lists/{listId}/bounced.{format}
   */
  async bouncedWithListJoinedDate(options: ListsBouncedWithListJoinedDateOptions): Promise<Response<ListsBouncedWithListJoinedDateResponseSuccess>> {
    const { listId, query } = options;
    return this.client.get<ListsBouncedWithListJoinedDateResponseSuccess>(`/lists/${listId}/bounced.json`, { query });
  }

  /**
   * Lists: CustomFields
   * GET lists/{listid}/customfields.{format}?includeFieldID={true|false}
   * @see GET /{version}/lists/{listId}/customfields.{format}
   */
  async customFields(options: ListsCustomFieldsOptions): Promise<Response<ListsCustomFieldsResponseSuccess>> {
    const { listId, query } = options;
    return this.client.get<ListsCustomFieldsResponseSuccess>(`/lists/${listId}/customfields.json`, { query });
  }

  /**
   * Lists: CreateCustomField
   * POST lists/{listid}/customfields.{format}
   * @see POST /{version}/lists/{listId}/customfields.{format}
   */
  async createCustomField(options: ListsCreateCustomFieldOptions): Promise<Response<ListsCreateCustomFieldResponseSuccess>> {
    const { listId, body } = options;
    return this.client.post<ListsCreateCustomFieldResponseSuccess>(`/lists/${listId}/customfields.json`, body);
  }

  /**
   * Lists: UpdateCustomField
   * PUT lists/{listid}/customfields/{customfieldkey}.{format}
   * @see PUT /{version}/lists/{listId}/customfields/{customFieldKey}.{format}
   */
  async updateCustomField(options: ListsUpdateCustomFieldOptions): Promise<Response<ListsUpdateCustomFieldResponseSuccess>> {
    const { listId, customFieldKey, body } = options;
    return this.client.put<ListsUpdateCustomFieldResponseSuccess>(`/lists/${listId}/customfields/${customFieldKey}.json`, body);
  }

  /**
   * Lists: DeleteCustomField
   * @see DELETE /{version}/lists/{listId}/customfields/{customFieldKey}.{format}
   */
  async deleteCustomField(options: ListsDeleteCustomFieldOptions): Promise<Response<ListsDeleteCustomFieldResponseSuccess>> {
    const { listId, customFieldKey } = options;
    return this.client.delete<ListsDeleteCustomFieldResponseSuccess>(`/lists/${listId}/customfields/${customFieldKey}.json`);
  }

  /**
   * Lists: UpdateFieldOptions
   * PUT lists/{listid}/customfields/{customfieldkey}/options.{format}
   * @see PUT /{version}/lists/{listId}/customfields/{customFieldKey}/options.{format}
   */
  async updateFieldOptions(options: ListsUpdateFieldOptionsOptions): Promise<Response<ListsUpdateFieldOptionsResponseSuccess>> {
    const { listId, customFieldKey, body } = options;
    return this.client.put<ListsUpdateFieldOptionsResponseSuccess>(`/lists/${listId}/customfields/${customFieldKey}/options.json`, body);
  }

  /**
   * Lists: DeletedWithListJoinedDate
   * GET lists/{listid}/deleted.{format}?date={YYYY-MM-DD HH:MM:SS} (v3.3 and up)
   * @see GET /{version}/lists/{listId}/deleted.{format}
   */
  async deleteDWithListJoinedDate(options: ListsDeleteDWithListJoinedDateOptions): Promise<Response<ListsDeleteDWithListJoinedDateResponseSuccess>> {
    const { listId, query } = options;
    return this.client.get<ListsDeleteDWithListJoinedDateResponseSuccess>(`/lists/${listId}/deleted.json`, { query });
  }

  /**
   * Lists: GetListSegments
   * GET lists/{listid}/segments.{format}
   * @see GET /{version}/lists/{listId}/segments.{format}
   */
  async getListSegments(options: ListsGetListSegmentsOptions): Promise<Response<ListsGetListSegmentsResponseSuccess>> {
    const { listId } = options;
    return this.client.get<ListsGetListSegmentsResponseSuccess>(`/lists/${listId}/segments.json`);
  }

  /**
   * Lists: GetListStats
   * GET lists/{listid}/stats.{format}
   * @see GET /{version}/lists/{listId}/stats.{format}
   */
  async getListStats(options: ListsGetListStatsOptions): Promise<Response<ListsGetListStatsResponseSuccess>> {
    const { listId } = options;
    return this.client.get<ListsGetListStatsResponseSuccess>(`/lists/${listId}/stats.json`);
  }

  /**
   * Lists: UnconfirmedWithListJoinedDate
   * GET lists/{listid}/unconfirmed.{format}?date={YYYY-MM-DD HH:MM:SS} (v3.3 and up)
   * @see GET /{version}/lists/{listId}/unconfirmed.{format}
   */
  async unconfirmedWithListJoinedDate(options: ListsUnconfirmedWithListJoinedDateOptions): Promise<Response<ListsUnconfirmedWithListJoinedDateResponseSuccess>> {
    const { listId, query } = options;
    return this.client.get<ListsUnconfirmedWithListJoinedDateResponseSuccess>(`/lists/${listId}/unconfirmed.json`, { query });
  }

  /**
   * Lists: UnsubscribedWithListJoinedDate
   * GET lists/{listid}/unsubscribed.{format}?date={YYYY-MM-DD HH:MM:SS} (v3.3 and up)
   * @see GET /{version}/lists/{listId}/unsubscribed.{format}
   */
  async unsubscribedWithListJoinedDate(options: ListsUnsubscribedWithListJoinedDateOptions): Promise<Response<ListsUnsubscribedWithListJoinedDateResponseSuccess>> {
    const { listId, query } = options;
    return this.client.get<ListsUnsubscribedWithListJoinedDateResponseSuccess>(`/lists/${listId}/unsubscribed.json`, { query });
  }

  /**
   * Lists: GetListWebhooks
   * GET lists/{listid}/webhooks.{format}
   * @see GET /{version}/lists/{listId}/webhooks.{format}
   */
  async getListWebhooks(options: ListsGetListWebhooksOptions): Promise<Response<ListsGetListWebhooksResponseSuccess>> {
    const { listId } = options;
    return this.client.get<ListsGetListWebhooksResponseSuccess>(`/lists/${listId}/webhooks.json`);
  }

  /**
   * Lists: CreateWebhook
   * POST lists/{listid}/webhooks.{format}
   * @see POST /{version}/lists/{listId}/webhooks.{format}
   */
  async createWebhook(options: ListsCreateWebhookOptions): Promise<Response<ListsCreateWebhookResponseSuccess>> {
    const { listId, body } = options;
    return this.client.post<ListsCreateWebhookResponseSuccess>(`/lists/${listId}/webhooks.json`, body);
  }

  /**
   * Lists: DeleteWebhook
   * DELETE lists/{listid}/webhooks/{webhookid}.{format}
   * @see DELETE /{version}/lists/{listId}/webhooks/{webhookId}.{format}
   */
  async deleteWebhook(options: ListsDeleteWebhookOptions): Promise<Response<ListsDeleteWebhookResponseSuccess>> {
    const { listId, webhookId } = options;
    return this.client.delete<ListsDeleteWebhookResponseSuccess>(`/lists/${listId}/webhooks/${webhookId}.json`);
  }

  /**
   * Lists: ActivateWebhook
   * PUT lists/{listid}/webhooks/{webhookid}/activate.{format}
   * @see PUT /{version}/lists/{listId}/webhooks/{webhookId}/activate.{format}
   */
  async activateWebhook(options: ListsActivateWebhookOptions): Promise<Response<ListsActivateWebhookResponseSuccess>> {
    const { listId, webhookId } = options;
    return this.client.put<ListsActivateWebhookResponseSuccess>(`/lists/${listId}/webhooks/${webhookId}/activate.json`, undefined);
  }

  /**
   * Lists: DeactivateWebhook
   * PUT lists/{listid}/webhooks/{webhookid}/deactivate.{format}
   * @see PUT /{version}/lists/{listId}/webhooks/{webhookId}/deactivate.{format}
   */
  async deactivateWebhook(options: ListsDeactivateWebhookOptions): Promise<Response<ListsDeactivateWebhookResponseSuccess>> {
    const { listId, webhookId } = options;
    return this.client.put<ListsDeactivateWebhookResponseSuccess>(`/lists/${listId}/webhooks/${webhookId}/deactivate.json`, undefined);
  }

  /**
   * Lists: TestWebhook
   * GET lists/{listid}/webhooks/{webhookid}/test.{format}
   * @see GET /{version}/lists/{listId}/webhooks/{webhookId}/test.{format}
   */
  async testWebhook(options: ListsTestWebhookOptions): Promise<Response<ListsTestWebhookResponseSuccess>> {
    const { listId, webhookId } = options;
    return this.client.get<ListsTestWebhookResponseSuccess>(`/lists/${listId}/webhooks/${webhookId}/test.json`);
  }

}