// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { ListsCreateOptions, ListsCreateResponseSuccess } from './interfaces/create.js';
import type { ListsGetOptions, ListsGetResponseSuccess } from './interfaces/get.js';
import type { ListsUpdateOptions, ListsUpdateResponseSuccess } from './interfaces/update.js';
import type { ListsDeleteOptions, ListsDeleteResponseSuccess } from './interfaces/delete.js';
import type { ListsActivewithlistjoineddateOptions, ListsActivewithlistjoineddateResponseSuccess } from './interfaces/activewithlistjoineddate.js';
import type { ListsBouncedwithlistjoineddateOptions, ListsBouncedwithlistjoineddateResponseSuccess } from './interfaces/bouncedwithlistjoineddate.js';
import type { ListsCustomfieldsOptions, ListsCustomfieldsResponseSuccess } from './interfaces/customfields.js';
import type { ListsCreateCustomfieldOptions, ListsCreateCustomfieldResponseSuccess } from './interfaces/create-customfield.js';
import type { ListsUpdateCustomfieldOptions, ListsUpdateCustomfieldResponseSuccess } from './interfaces/update-customfield.js';
import type { ListsDeleteCustomfieldOptions, ListsDeleteCustomfieldResponseSuccess } from './interfaces/delete-customfield.js';
import type { ListsUpdateFieldoptionsOptions, ListsUpdateFieldoptionsResponseSuccess } from './interfaces/update-fieldoptions.js';
import type { ListsDeleteDwithlistjoineddateOptions, ListsDeleteDwithlistjoineddateResponseSuccess } from './interfaces/delete-dwithlistjoineddate.js';
import type { ListsDetailedstatsOptions, ListsDetailedstatsResponseSuccess } from './interfaces/detailedstats.js';
import type { ListsSegmentsOptions, ListsSegmentsResponseSuccess } from './interfaces/segments.js';
import type { ListsStatsOptions, ListsStatsResponseSuccess } from './interfaces/stats.js';
import type { ListsTimelineOptions, ListsTimelineResponseSuccess } from './interfaces/timeline.js';
import type { ListsUnconfirmedwithlistjoineddateOptions, ListsUnconfirmedwithlistjoineddateResponseSuccess } from './interfaces/unconfirmedwithlistjoineddate.js';
import type { ListsUnsubscribedwithlistjoineddateOptions, ListsUnsubscribedwithlistjoineddateResponseSuccess } from './interfaces/unsubscribedwithlistjoineddate.js';
import type { ListsWebhooksOptions, ListsWebhooksResponseSuccess } from './interfaces/webhooks.js';
import type { ListsCreateWebhookOptions, ListsCreateWebhookResponseSuccess } from './interfaces/create-webhook.js';
import type { ListsDeleteWebhookOptions, ListsDeleteWebhookResponseSuccess } from './interfaces/delete-webhook.js';
import type { ListsActivatewebhookOptions, ListsActivatewebhookResponseSuccess } from './interfaces/activatewebhook.js';
import type { ListsDeactivatewebhookOptions, ListsDeactivatewebhookResponseSuccess } from './interfaces/deactivatewebhook.js';
import type { ListsTestwebhookOptions, ListsTestwebhookResponseSuccess } from './interfaces/testwebhook.js';

export class Lists {
  constructor(private readonly client: Createsend) {}

  /**
   * Lists: Create
   * POST lists/{clientid}.{format}
   * @see POST /{version}/lists/{clientid}.{format}
   */
  async create(options: ListsCreateOptions): Promise<Response<ListsCreateResponseSuccess>> {
    const { clientid, body } = options;
    return this.client.post<ListsCreateResponseSuccess>(`/lists/${clientid}.json`, body);
  }

  /**
   * Lists: Get
   * GET lists/{listid}.{format}
   * @see GET /{version}/lists/{listid}.{format}
   */
  async get(options: ListsGetOptions): Promise<Response<ListsGetResponseSuccess>> {
    const { listid } = options;
    return this.client.get<ListsGetResponseSuccess>(`/lists/${listid}.json`);
  }

  /**
   * Lists: Update
   * PUT lists/{listid}.{format}
   * @see PUT /{version}/lists/{listid}.{format}
   */
  async update(options: ListsUpdateOptions): Promise<Response<ListsUpdateResponseSuccess>> {
    const { listid, body } = options;
    return this.client.put<ListsUpdateResponseSuccess>(`/lists/${listid}.json`, body);
  }

  /**
   * Lists: Delete
   * DELETE lists/{listid}.{format}
   * @see DELETE /{version}/lists/{listid}.{format}
   */
  async delete(options: ListsDeleteOptions): Promise<Response<ListsDeleteResponseSuccess>> {
    const { listid } = options;
    return this.client.delete<ListsDeleteResponseSuccess>(`/lists/${listid}.json`);
  }

  /**
   * Lists: ActiveWithListJoinedDate
   * GET lists/{listid}/active.{format}?date={YYYY-MM-DD HH:MM:SS} (v3.3 and up)
   * @see GET /{version}/lists/{listid}/active.{format}
   */
  async activewithlistjoineddate(options: ListsActivewithlistjoineddateOptions): Promise<Response<ListsActivewithlistjoineddateResponseSuccess>> {
    const { listid, query } = options;
    return this.client.get<ListsActivewithlistjoineddateResponseSuccess>(`/lists/${listid}/active.json`, { query });
  }

  /**
   * Lists: BouncedWithListJoinedDate
   * GET lists/{listid}/bounced.{format}?date={YYYY-MM-DD HH:MM:SS} (v3.3 and up)
   * @see GET /{version}/lists/{listid}/bounced.{format}
   */
  async bouncedwithlistjoineddate(options: ListsBouncedwithlistjoineddateOptions): Promise<Response<ListsBouncedwithlistjoineddateResponseSuccess>> {
    const { listid, query } = options;
    return this.client.get<ListsBouncedwithlistjoineddateResponseSuccess>(`/lists/${listid}/bounced.json`, { query });
  }

  /**
   * Lists: Customfields
   * GET lists/{listid}/customfields.{format}?includeFieldID={true|false}
   * @see GET /{version}/lists/{listid}/customfields.{format}
   */
  async customfields(options: ListsCustomfieldsOptions): Promise<Response<ListsCustomfieldsResponseSuccess>> {
    const { listid, query } = options;
    return this.client.get<ListsCustomfieldsResponseSuccess>(`/lists/${listid}/customfields.json`, { query });
  }

  /**
   * Lists: Createcustomfield
   * POST lists/{listid}/customfields.{format}
   * @see POST /{version}/lists/{listid}/customfields.{format}
   */
  async createCustomfield(options: ListsCreateCustomfieldOptions): Promise<Response<ListsCreateCustomfieldResponseSuccess>> {
    const { listid, body } = options;
    return this.client.post<ListsCreateCustomfieldResponseSuccess>(`/lists/${listid}/customfields.json`, body);
  }

  /**
   * Lists: Updatecustomfield
   * PUT lists/{listid}/customfields/{customfieldkey}.{format}
   * @see PUT /{version}/lists/{listid}/customfields/{customfieldkey}.{format}
   */
  async updateCustomfield(options: ListsUpdateCustomfieldOptions): Promise<Response<ListsUpdateCustomfieldResponseSuccess>> {
    const { listid, customfieldkey, body } = options;
    return this.client.put<ListsUpdateCustomfieldResponseSuccess>(`/lists/${listid}/customfields/${customfieldkey}.json`, body);
  }

  /**
   * Lists: Deletecustomfield
   * @see DELETE /{version}/lists/{listid}/customfields/{customfieldkey}.{format}
   */
  async deleteCustomfield(options: ListsDeleteCustomfieldOptions): Promise<Response<ListsDeleteCustomfieldResponseSuccess>> {
    const { listid, customfieldkey } = options;
    return this.client.delete<ListsDeleteCustomfieldResponseSuccess>(`/lists/${listid}/customfields/${customfieldkey}.json`);
  }

  /**
   * Lists: Updatefieldoptions
   * PUT lists/{listid}/customfields/{customfieldkey}/options.{format}
   * @see PUT /{version}/lists/{listid}/customfields/{customfieldkey}/options.{format}
   */
  async updateFieldoptions(options: ListsUpdateFieldoptionsOptions): Promise<Response<ListsUpdateFieldoptionsResponseSuccess>> {
    const { listid, customfieldkey, body } = options;
    return this.client.put<ListsUpdateFieldoptionsResponseSuccess>(`/lists/${listid}/customfields/${customfieldkey}/options.json`, body);
  }

  /**
   * Lists: DeletedWithListJoinedDate
   * GET lists/{listid}/deleted.{format}?date={YYYY-MM-DD HH:MM:SS} (v3.3 and up)
   * @see GET /{version}/lists/{listid}/deleted.{format}
   */
  async deleteDwithlistjoineddate(options: ListsDeleteDwithlistjoineddateOptions): Promise<Response<ListsDeleteDwithlistjoineddateResponseSuccess>> {
    const { listid, query } = options;
    return this.client.get<ListsDeleteDwithlistjoineddateResponseSuccess>(`/lists/${listid}/deleted.json`, { query });
  }

  /**
   * Lists: Detailedstats
   * GET lists/{listid}/detailedstats.{format}
   * @see GET /{version}/lists/{listid}/detailedstats.{format}
   */
  async detailedstats(options: ListsDetailedstatsOptions): Promise<Response<ListsDetailedstatsResponseSuccess>> {
    const { listid } = options;
    return this.client.get<ListsDetailedstatsResponseSuccess>(`/lists/${listid}/detailedstats.json`);
  }

  /**
   * Lists: Segments
   * GET lists/{listid}/segments.{format}
   * @see GET /{version}/lists/{listid}/segments.{format}
   */
  async segments(options: ListsSegmentsOptions): Promise<Response<ListsSegmentsResponseSuccess>> {
    const { listid } = options;
    return this.client.get<ListsSegmentsResponseSuccess>(`/lists/${listid}/segments.json`);
  }

  /**
   * Lists: Stats
   * GET lists/{listid}/stats.{format}
   * @see GET /{version}/lists/{listid}/stats.{format}
   */
  async stats(options: ListsStatsOptions): Promise<Response<ListsStatsResponseSuccess>> {
    const { listid } = options;
    return this.client.get<ListsStatsResponseSuccess>(`/lists/${listid}/stats.json`);
  }

  /**
   * Lists: Timeline
   * GET lists/{listid}/timeline.{format}
   * @see GET /{version}/lists/{listid}/timeline.{format}
   */
  async timeline(options: ListsTimelineOptions): Promise<Response<ListsTimelineResponseSuccess>> {
    const { listid, query } = options;
    return this.client.get<ListsTimelineResponseSuccess>(`/lists/${listid}/timeline.json`, { query });
  }

  /**
   * Lists: UnconfirmedWithListJoinedDate
   * GET lists/{listid}/unconfirmed.{format}?date={YYYY-MM-DD HH:MM:SS} (v3.3 and up)
   * @see GET /{version}/lists/{listid}/unconfirmed.{format}
   */
  async unconfirmedwithlistjoineddate(options: ListsUnconfirmedwithlistjoineddateOptions): Promise<Response<ListsUnconfirmedwithlistjoineddateResponseSuccess>> {
    const { listid, query } = options;
    return this.client.get<ListsUnconfirmedwithlistjoineddateResponseSuccess>(`/lists/${listid}/unconfirmed.json`, { query });
  }

  /**
   * Lists: UnsubscribedWithListJoinedDate
   * GET lists/{listid}/unsubscribed.{format}?date={YYYY-MM-DD HH:MM:SS} (v3.3 and up)
   * @see GET /{version}/lists/{listid}/unsubscribed.{format}
   */
  async unsubscribedwithlistjoineddate(options: ListsUnsubscribedwithlistjoineddateOptions): Promise<Response<ListsUnsubscribedwithlistjoineddateResponseSuccess>> {
    const { listid, query } = options;
    return this.client.get<ListsUnsubscribedwithlistjoineddateResponseSuccess>(`/lists/${listid}/unsubscribed.json`, { query });
  }

  /**
   * Lists: Webhooks
   * GET lists/{listid}/webhooks.{format}
   * @see GET /{version}/lists/{listid}/webhooks.{format}
   */
  async webhooks(options: ListsWebhooksOptions): Promise<Response<ListsWebhooksResponseSuccess>> {
    const { listid } = options;
    return this.client.get<ListsWebhooksResponseSuccess>(`/lists/${listid}/webhooks.json`);
  }

  /**
   * Lists: Createwebhook
   * POST lists/{listid}/webhooks.{format}
   * @see POST /{version}/lists/{listid}/webhooks.{format}
   */
  async createWebhook(options: ListsCreateWebhookOptions): Promise<Response<ListsCreateWebhookResponseSuccess>> {
    const { listid, body } = options;
    return this.client.post<ListsCreateWebhookResponseSuccess>(`/lists/${listid}/webhooks.json`, body);
  }

  /**
   * Lists: Deletewebhook
   * DELETE lists/{listid}/webhooks/{webhookid}.{format}
   * @see DELETE /{version}/lists/{listid}/webhooks/{webhookid}.{format}
   */
  async deleteWebhook(options: ListsDeleteWebhookOptions): Promise<Response<ListsDeleteWebhookResponseSuccess>> {
    const { listid, webhookid } = options;
    return this.client.delete<ListsDeleteWebhookResponseSuccess>(`/lists/${listid}/webhooks/${webhookid}.json`);
  }

  /**
   * Lists: Activatewebhook
   * PUT lists/{listid}/webhooks/{webhookid}/activate.{format}
   * @see PUT /{version}/lists/{listid}/webhooks/{webhookid}/activate.{format}
   */
  async activatewebhook(options: ListsActivatewebhookOptions): Promise<Response<ListsActivatewebhookResponseSuccess>> {
    const { listid, webhookid } = options;
    return this.client.put<ListsActivatewebhookResponseSuccess>(`/lists/${listid}/webhooks/${webhookid}/activate.json`, undefined);
  }

  /**
   * Lists: Deactivatewebhook
   * PUT lists/{listid}/webhooks/{webhookid}/deactivate.{format}
   * @see PUT /{version}/lists/{listid}/webhooks/{webhookid}/deactivate.{format}
   */
  async deactivatewebhook(options: ListsDeactivatewebhookOptions): Promise<Response<ListsDeactivatewebhookResponseSuccess>> {
    const { listid, webhookid } = options;
    return this.client.put<ListsDeactivatewebhookResponseSuccess>(`/lists/${listid}/webhooks/${webhookid}/deactivate.json`, undefined);
  }

  /**
   * Lists: Testwebhook
   * GET lists/{listid}/webhooks/{webhookid}/test.{format}
   * @see GET /{version}/lists/{listid}/webhooks/{webhookid}/test.{format}
   */
  async testwebhook(options: ListsTestwebhookOptions): Promise<Response<ListsTestwebhookResponseSuccess>> {
    const { listid, webhookid } = options;
    return this.client.get<ListsTestwebhookResponseSuccess>(`/lists/${listid}/webhooks/${webhookid}/test.json`);
  }

}