// DO NOT EDIT — generated by scripts/generate.ts
import type { Response } from '../interfaces.js';
import type { Createsend } from '../createsend.js';
import type { GetfeedbackAccountOptions, GetfeedbackAccountResponseSuccess } from './interfaces/account.js';

export class Getfeedback {
  constructor(private readonly client: Createsend) {}

  /**
   * Getfeedback: Account
   * @see POST /{version}/getfeedback/{id}.{format}
   */
  async account(options: GetfeedbackAccountOptions): Promise<Response<GetfeedbackAccountResponseSuccess>> {
    const { id, body } = options;
    return this.client.post<GetfeedbackAccountResponseSuccess>(`/getfeedback/${id}.json`, body);
  }

}