// DO NOT EDIT — generated by scripts/generate.ts
// Source: query_status

import type { ApiResponse } from '../../generated/schema.js';

export interface QueryStatusOptions {
  sendId: string;
}

export type QueryStatusResponseSuccess = ApiResponse;
