// DO NOT EDIT — generated by scripts/generate.ts
// Source: workflowemails_emailbounces

import type { PagedResult_WorkflowEmailBounceCollection_WorkflowEmailBounce } from '../../generated/schema.js';

export interface WorkflowemailsEmailbouncesQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderDirection?: string;
}

export interface WorkflowemailsEmailbouncesOptions {
  emailid: string;
  query?: WorkflowemailsEmailbouncesQuery;
}

export type WorkflowemailsEmailbouncesResponseSuccess = PagedResult_WorkflowEmailBounceCollection_WorkflowEmailBounce;
