// DO NOT EDIT — generated by scripts/generate.ts
// Source: workflowemails_emailrecipients

import type { PagedResult_WorkflowEmailRecipientCollection_WorkflowEmailRecipient } from '../../generated/schema.js';

export interface WorkflowemailsEmailrecipientsQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderDirection?: string;
}

export interface WorkflowemailsEmailrecipientsOptions {
  emailid: string;
  query?: WorkflowemailsEmailrecipientsQuery;
}

export type WorkflowemailsEmailrecipientsResponseSuccess = PagedResult_WorkflowEmailRecipientCollection_WorkflowEmailRecipient;
