// DO NOT EDIT — generated by scripts/generate.ts
// Source: workflowemails_emailclicks

import type { PagedResult_WorkflowEmailClickCollection_WorkflowEmailClick } from '../../generated/schema.js';

export interface WorkflowemailsEmailclicksQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderDirection?: string;
}

export interface WorkflowemailsEmailclicksOptions {
  emailid: string;
  query?: WorkflowemailsEmailclicksQuery;
}

export type WorkflowemailsEmailclicksResponseSuccess = PagedResult_WorkflowEmailClickCollection_WorkflowEmailClick;
