// DO NOT EDIT — generated by scripts/generate.ts
// Source: workflowemails_emailopens

import type { PagedResult_WorkflowEmailOpenCollection_WorkflowEmailOpen } from '../../generated/schema.js';

export interface WorkflowemailsEmailopensQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderDirection?: string;
}

export interface WorkflowemailsEmailopensOptions {
  emailid: string;
  query?: WorkflowemailsEmailopensQuery;
}

export type WorkflowemailsEmailopensResponseSuccess = PagedResult_WorkflowEmailOpenCollection_WorkflowEmailOpen;
