// DO NOT EDIT — generated by scripts/generate.ts
// Source: workflowemails_emailunsubscribes

import type { PagedResult_WorkflowEmailUnsubscribeCollection_WorkflowEmailUnsubscribe } from '../../generated/schema.js';

export interface WorkflowemailsEmailunsubscribesQuery {
  [key: string]: unknown;
  date: string;
  page?: number;
  pageSize?: number;
  orderDirection?: string;
}

export interface WorkflowemailsEmailunsubscribesOptions {
  emailid: string;
  query?: WorkflowemailsEmailunsubscribesQuery;
}

export type WorkflowemailsEmailunsubscribesResponseSuccess = PagedResult_WorkflowEmailUnsubscribeCollection_WorkflowEmailUnsubscribe;
