// DO NOT EDIT — generated by scripts/generate.ts

export type { WorkflowemailsEmailbouncesOptions, WorkflowemailsEmailbouncesResponseSuccess } from './emailbounces.js';
export type { WorkflowemailsEmailclicksOptions, WorkflowemailsEmailclicksResponseSuccess } from './emailclicks.js';
export type { WorkflowemailsEmailopensOptions, WorkflowemailsEmailopensResponseSuccess } from './emailopens.js';
export type { WorkflowemailsEmailrecipientsOptions, WorkflowemailsEmailrecipientsResponseSuccess } from './emailrecipients.js';
export type { WorkflowemailsEmailunsubscribesOptions, WorkflowemailsEmailunsubscribesResponseSuccess } from './emailunsubscribes.js';
