// DO NOT EDIT — generated by scripts/generate.ts
// Source: smartemail_details

export interface SmartEmailDetailsOptions {
  id: string;
}

export type SmartEmailDetailsResponseSuccess = {
  SmartEmailID?: string;
  Name?: string;
  CreatedAt?: string;
  Status?: string;
  Properties?: Record<string, unknown>;
  AddRecipientsToList?: string;
};
