// DO NOT EDIT — generated by scripts/generate.ts
// Source: getSmartEmailDetails

import type { SmartEmailDetailsResponse } from '../../generated/schema.js';

export interface SmartEmailGetSmartEmailDetailsOptions {
  id: string;
}

export type SmartEmailGetSmartEmailDetailsResponseSuccess = SmartEmailDetailsResponse;
