// DO NOT EDIT — generated by scripts/generate.ts
// Source: listingSmartEmail

export interface SmartEmailListIngSmartEmailQuery {
  [key: string]: unknown;
  clientID?: string;
}

export interface SmartEmailListIngSmartEmailOptions {
  query?: SmartEmailListIngSmartEmailQuery;
}

export type SmartEmailListIngSmartEmailResponseSuccess = Array<{
  ID?: Record<string, unknown>;
  Name?: Record<string, unknown>;
  CreatedAt?: Record<string, unknown>;
  Status?: string;
}>;
