// DO NOT EDIT — generated by scripts/generate.ts
// Source: smartemail_listing

export type SmartEmailListIngOptions = Record<string, never>;

export type SmartEmailListIngResponseSuccess = Array<{
  ID?: Record<string, unknown>;
  Name?: Record<string, unknown>;
  CreatedAt?: Record<string, unknown>;
  Status?: string;
}>;
