// DO NOT EDIT — generated by scripts/generate.ts
// Source: sendSmartEmail

import type { SmartEmailSend } from '../../generated/schema.js';

export interface SmartEmailSendSmartEmailOptions {
  id: string;
  body: SmartEmailSend;
}

export type SmartEmailSendSmartEmailResponseSuccess = Array<{
  Status?: string;
  MessageID?: Record<string, unknown>;
  Recipient?: Record<string, unknown>;
}>;
