// DO NOT EDIT — generated by scripts/generate.ts
// Source: smartemail_send

import type { SmartEmailSend } from '../../generated/schema.js';

export interface SmartEmailSendOptions {
  id: string;
  body: SmartEmailSend;
}

export type SmartEmailSendResponseSuccess = Array<{
  Status?: string;
  MessageID?: Record<string, unknown>;
  Recipient?: Record<string, unknown>;
}>;
